### ISSUE TITLE
주요 테이블 변경 이력관리 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#1006]
주요 테이블 변경 이력관리 해야합니다.

**Comment by jeongjaehong** [comment]
대상 테이블하고 방법을 정해야 겠네요.

우선 tadpole_user_db_role 테이블을 대상으로 검토 시작해 보겠습니다.

**Comment by jeongjaehong** [comment]
트리거로 같은 디비내에 보관할 수 도 있지만 
텍스트 파일로 지정된 위치에 날짜별 혹은 월별로 보관하고 오래된 자료는 압축하거나 삭제하게 할수도 있을듯 합니다.
변경 로그를 조회하고 관리하는 관리자용 ui도 추가되어야 할것 같구요.

**Comment by hangum** [comment]
@jeongjaehong  이 이슈는 엔터프라이즈 쪽으로 옮겨야 겠어요.  멘션 할게요.
