### ISSUE TITLE
PostgreSQL 펑션 프로시저 이름 중복 오류

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#1007]
펑션 이나 프로시저일 경우 이름은 같으나 변수의 갯수나 타입이 틀려서 여러개인 경우가 있습니다. 
현재 테드폴에서는 변수 이름이 중복되어 표시 되어 구분도 안되고 DDL 보기 기능을 실행했을 경우 오류입니다. 

변수가 두개로 보여야 할것 같습니다. 

CREATE FUNCTION increment(i int4, j int4) RETURNS int4 AS $$ 
BEGIN 
	RETURN i + j+ 1; 
END; 
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION increment(i INT) RETURNS INT AS $$ 
BEGIN 
	RETURN i + j+ 1; 
END; 
$$ LANGUAGE plpgsql;

![image](https://user-images.githubusercontent.com/1335915/29599994-271781e8-880e-11e7-845e-f3bf454d6733.png)

**Comment by jeongjaehong** [comment]
오라클의 경우 어떻게 했었는지 기억이 안나네요...확인해 보겠습니다.

**Comment by jeongjaehong** [comment]
오라클의 경우는 패키지 내부의 함수의 경우 아래 첨부 이미지처럼 처리하고 있네요. 
일단 postgresSQL의 경우 내부 오브젝트 정보를 어떻게 관리하고 있는지 확인해 봐야 할듯 합니다. 

![image](https://user-images.githubusercontent.com/859932/29656078-28e9f4c0-88ee-11e7-8434-056bb9cb53ad.png)
