### ISSUE TITLE
운영디비와 개발디비의 에디터창을 시각적으로 구분하기 쉽도록 하면 좋겠습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1019]
데이터베이스 명을 동일하게 했을경우 에디터 창의 제목이 똑같아서 운영디비 인지 테스트 디비인지 착각의 소지가 있어 보입니다. 
앞쪽에 [P] 또는 스키마 같은 걸 함께 표시해서 구분이 되면 좋을듯 합니다.  

물론 운영디비인 경우 매번 실행전에 확인 메시지가 뜨게 할 수 도 있지만 너무 번거로울 수 있어서...그것보다는 시각적으로 표시를 다르게 하면 좋을듯 합니다. 색상같은거 라든가...

![image](https://user-images.githubusercontent.com/859932/30366417-e87a6a4c-98a5-11e7-812f-8e5aea47c91f.png)

**Comment by hangum** [comment]
네~
