### ISSUE TITLE
외부 리소스 참조 및 라이브러리 참조.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1022]
폐쇄망을 사용하는 경우 외부 인터넷과 단절된 서버에 설치된 올챙이에서 최초 로그인 시에 외부 참조 라이브러리 및 리소스를 로딩하려고 하면서 대기 시간이 길어지는 상황이 발생합니다.

타임아웃을 지정할 수 없다면 해당 리소스나 라이브러리를 내부에 두거나 제외할수 있는 시스템 관리자 설정이 필요해 보입니다.

로그인창 표시 시간이 길어지고 로그아웃 후에 다시 로그인창을 표시하도록 새로고침 될때도 시간이 많이 걸리고 있습니다.

![image](https://user-images.githubusercontent.com/859932/30409012-5526084e-993d-11e7-9030-8d0ed33f4672.png)

**Comment by jeongjaehong** [comment]
구글 통계수집 관련 js라이브러리에서 타임아웃 발생합니다.
![image](https://user-images.githubusercontent.com/859932/30409140-26b520f2-993e-11e7-8f7e-f296c80db2e7.png)

**Comment by hangum** [comment]
엔터프라이즈 고객의 바이너린 없는데 다시 드릴게요
