### ISSUE TITLE
다른컴퓨터에서 접속했을때 같은아이디의 다른 세션을 종료시켰을 경우..

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1025]
아무런 메시지 없이 작동을 안해서 오류로 인식되는 문제가 있습니다.

화면(에디터)에 작업중이던 리소스를 유지하기 위해서 화면을 그대로 유지하는건 좋은것 같은데...

사용자가 다른 데이터베이스를 선택한다거나 뭔가 메뉴를 클릭하거나 할때 세션이 종료되어 작업이 안될때 다른 곳에서 로그인 해서 현재 세션이 종료되었으니 다시 로그인 하라고 메시지가 뜨면 좋겠습니다.

![image](https://user-images.githubusercontent.com/859932/30417199-e3761f7c-9969-11e7-8e05-3504f168457d.png)

**Comment by hangum** [comment]
- 말씀하신 것은 현재화면을 그대로 유지는 것은 서버에서 사용자 세션을 종료하는 것이기에 구현하기 어렵습니다. 
- 로그아웃되는 메시지 띄우는것도 서버에서 사용자 세션을 종료하는 것이기에 구현하기 어렵습니다.
자신이 중복으로 로그인 할때 위와 같은 상황이 일어나는 것을 인지해야합니다.

**Comment by hangum** [comment]
- 중복 로그인시에 로그인 히스토리에 중복 로그인으로 로그인 했다는 정보를 남길수 있도록 하겠습니다.
