### ISSUE TITLE
'오브젝트 탐색기'의 '필터'적용 시 '테이블'탭에서 Column크기가 제대로 표기되지 않을 문제

### ISSUE THREAD

**Issue by Mabin-J** [hangum/TadpoleForDBTools#1026]
'오브젝트 탐색기'의 '테이블'탭에서 존재하는 프로시저이름을 필터적용한 후
'프로시저' 탭에 들어가서 프로시저를 확인하고,
곧바로 존재하는 테이블 이름을 필터적용하고,
'테이블'탭에 들어가면 '이름' 열의 크기가 비정상적으로 표시됩니다.

이 상태에서 다른 탭에 들어갔다가 다시 '테이블'탭으로 돌아가면
정상적으로 표기됩니다.

**Comment by hangum** [comment]
@Mabin-J 안녕하세요.

아래처럼 컬럼의 값이 작게 표시된다는 것이지요?
![image](https://user-images.githubusercontent.com/1335915/30465824-8450fcc8-9a14-11e7-9499-4e2b4ed9150b.png)

**Comment by Mabin-J** [comment]
네 맞습니다. ^^

**Comment by hangum** [comment]
@Mabin-J  감사합니다.
