### ISSUE TITLE
에디터 창에서 리소스를 편집중에 새로운 파일을 읽어올 경우...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1029]
에디터 창에서 리소스를 편집중에 새로운 파일을 읽어올 경우 새로운 에디터 창으로 열리면 좋을듯 합니다. 

또는 에디터 창에서 새로운 창으로 열기 옵션이 있다면 더 좋겠습니다.

현재는 기존 리소스 내용에 새로 읽어온 내용이 아래쪽에 추가되게 되어 있네요. ^^;

가령 리소스 제목과 파일명이 같다면 파일로 저장된 내용으로 교체( 최종 저장상태로 되돌리기...) 하거나 
새로 불러온 내용에 추가하거나 (현재는 이렇게 작동중...)
새로운 에디터 창으로 열리거나 하는 동작 조건을 사용자가 지정할 수 있으면 좋겠습니다. 

![image](https://user-images.githubusercontent.com/859932/30526814-e3238a9c-9c5b-11e7-8613-b72e3b9f4859.png)

**Comment by hangum** [comment]
좀더 편리하겠네요. 
저장내용으로 되돌리기는 뭐에요?

**Comment by jeongjaehong** [comment]
저장내용으로 되돌리기는 기존에 에디터에 있는 내용무시하고 파일에서 불러온 내용으로 에디터의 내용을 교체하는기능입니다. 

![image](https://user-images.githubusercontent.com/859932/30526934-b78b01ce-9c5d-11e7-9777-409ca10b557f.png)

**Comment by hangum** [comment]
@jeongjaehong  아아
