### ISSUE TITLE
데이터베이스 추가 대화상자의 크기에 대하여~

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1031]
macOS와 Windows에서 대화상자의 크기가 다르게 표시되는듯 합니다. 

열린후에 리사이즈 할 수 있어 내용을 입력하거나 선택할 수는 있지만 불편한 점이 있습니다. 
화면 디자인을 좀더 여백을 줘서 여유롭게 하면 어떨까요? 
- 브라우져 버젼은 크롬으로 빌드번호까지 동일합니다. os만 다른 상황입니다.

맥에서 데이터베이스 추가 버튼 클릭시...
![image](https://user-images.githubusercontent.com/859932/30527434-7a822400-9c63-11e7-943b-375f24ddbf8f.png)

윈도우에서 데이터베이스 추가버튼 클릭시...
![image](https://user-images.githubusercontent.com/859932/30527441-8af07210-9c63-11e7-9cf6-3aa4ce7190cf.png)

**Comment by hangum** [comment]
일단 좀 키워놔야겟네요

**Comment by hangum** [comment]
@jeongjaehong  어떤 브라우저로 테스트 했어요?

**Comment by hangum** [comment]
이거 원10, xp에서 테스트 해봐도 잘 되는데요.

**Comment by hangum** [comment]
@jeongjaehong  브라우저는 뭐였어요?

**Comment by jeongjaehong** [comment]
windows7에 설치된 크롬입니다.

![image](https://user-images.githubusercontent.com/859932/31702335-52afa90a-b411-11e7-850d-61a27957b27d.png)

**Comment by jeongjaehong** [comment]
어쩌면 외부에 존재하는 css같은 리소스를 참조할 경우 내부 폐쇄망 이라서 해당 css가 적용되지 않아서 그럴 수도 있습니다.

혹시 화면 디자인 요소에 사용되는 리소스들 중에서 외부 리소스 (http://***** )를 사용하는게 있지 않을까요?

아니면 os나 크롬의 폰트 크기 설정 때문인가? 싶기도 합니다.

**Comment by jeongjaehong** [comment]
크롬에서 최소 글꼴 크기를 크게 하면 그런현상이 발생하네요.

최소글꼴을 11로 하면 화면레이아웃이 깨지지 않고 12이상이면 화면레이아웃이 깨집니다. 

![image](https://user-images.githubusercontent.com/859932/31702767-33bce3d4-b414-11e7-83bc-961342fbfb7b.png)
