### ISSUE TITLE
각각 다른 스키마에 생성된 동일 이름의 테이블 데이타수정 모드 관련

### ISSUE THREAD

**Issue by fermatC** [hangum/TadpoleForDBTools#1032]
(조금전에 올챙이 페이스북 페이지에 올렸던 내용입니다.)

각각 다른 스키마에 생성된 동일 이름의 테이블(레이아웃이 다른) 의 데이타 수정 탭을 띄웠는데 먼저 띄운 테이블 정보로 수정 탭이 뜹니다.

============================ Version ==========================

![image](https://user-images.githubusercontent.com/8133210/30529084-a66ceb98-9c74-11e7-8a66-970f67d7e44f.png)

============================ table 1==========================

  CREATE TABLE "BXI"."DBTODB" 
   (	"UUID" VARCHAR2(32) NOT NULL ENABLE, 
	"TX_DT" VARCHAR2(8) NOT NULL ENABLE, 
	"INST_CD" VARCHAR2(16) NOT NULL ENABLE, 
	"PROCNG_DSCD" VARCHAR2(1) NOT NULL ENABLE, 
	"PROCNG_STAT" VARCHAR2(1) NOT NULL ENABLE, 
	"LAST_CHNG_DTM" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DBTODB" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 ;

COMMENT ON TABLE BXI.DBTODB IS 'DBTODB 테스트 테이블';
COMMENT ON COLUMN BXI.DBTODB.UUID IS 'UUID';
COMMENT ON COLUMN BXI.DBTODB.TX_DT IS '거래일자';
COMMENT ON COLUMN BXI.DBTODB.INST_CD IS '기관코드';
COMMENT ON COLUMN BXI.DBTODB.PROCNG_DSCD IS '처리구분코드';
COMMENT ON COLUMN BXI.DBTODB.PROCNG_STAT IS '거래처리상태코드';
COMMENT ON COLUMN BXI.DBTODB.LAST_CHNG_DTM IS '최종변경일시';

============================ table 2==========================

  CREATE TABLE "BXIDEV"."DBTODB" 
   (	"INST_CD" VARCHAR2(16) NOT NULL ENABLE, 
	"USE_YN" VARCHAR2(1) NOT NULL ENABLE, 
	"LAST_CHNG_DTM" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_CHNG_GUID" VARCHAR2(32) NOT NULL ENABLE, 
	"PROCNG_DSCD" VARCHAR2(1), 
	 CONSTRAINT "PK_DBTODB" PRIMARY KEY ("INST_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BXITS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BXITS" 
 ;

COMMENT ON TABLE BXIDEV.DBTODB IS 'DBTODB 테스트 테이블';
COMMENT ON COLUMN BXIDEV.DBTODB.INST_CD IS '기관코드';
COMMENT ON COLUMN BXIDEV.DBTODB.USE_YN IS '사용여부';
COMMENT ON COLUMN BXIDEV.DBTODB.LAST_CHNG_DTM IS '최종변경일시';
COMMENT ON COLUMN BXIDEV.DBTODB.LAST_CHNG_GUID IS '최종변경GUID';

**Comment by hangum** [comment]
@fermatC  버그 임을 확인했습니다.
화면 관리를 단순 오브젝트 이름으로 만 하여서 나타나는 문제이구요. db.schema.object 이름으로 변경하여 개선 할 수 있도록 하겠습니다.
