### ISSUE TITLE
begin으로 시작하는 pl/sql 스크립트를 리소스로 저장했을때...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1034]
리소스 목록을 더블클릭하면 sql에디터 창에서 리소스가 열립니다.

블럭을 설정하여 실행을 하면 정상 실행은 되나 스크립트 output이 표시되지 않습니다.

컴파일 에디터 창에서 표시되도록 하면 좋을듯 합니다.

sql 에디터에서 실행했을때...
![image](https://user-images.githubusercontent.com/859932/30534069-77f43550-9c97-11e7-9bce-3f2441e79fb7.png)

pl/sql 컴파일 에디터에서 실행했을때...
![image](https://user-images.githubusercontent.com/859932/30534093-8da4b488-9c97-11e7-8509-ca6b7a72a484.png)

**Comment by jeongjaehong** [comment]
dbms_output.enable(버퍼사이즈); 해줄때 기본 버퍼 사이즈가 몇인지 모르겠지만 dbms_ouput내용이 loop안에서 반복될 경우 버퍼 사이즈가 작아서 오류가 발생합니다. 

버퍼사이즈를 최대로 하거나, 
사용자가 버퍼 사이즈를 지정하게 하거나, 
dbms_output.get_line을 사용하여 라인단위로 시스템메시지 출력창에 flush하도록 하면 좋을듯 합니다.

**Comment by hangum** [comment]
에디터에 리소스 저장시에 오브젝트에디터에 저장했으면 오브젝트 창이 열리도록 개선했습니다.
(1.7.5 a4 버전부터 적용됩니다)
