### ISSUE TITLE
새로운 jdbc드라이버를 업로드 하고 기존 jdbc드라이버를 삭제할때...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1035]
클라이언트의 로컬 경로에서 해당 파일의 삭제를 시도하는 걸까요? 
첨부와 같은 에러가 발생하였습니다. 

또는 서버에서 삭제를 시도하는 거라면 해당 jar파일이 tomcat에 의해서 사용중이라서 그러는 거겠죠?

"삭제" 기능을 쓰려면 oracle 데이터 베이스 컨넥션을 모두 종료하고 시도해야 하면 될까요? 
아니면 강제로 삭제 후에 서버(톰캣)을 재시작 해야 할까요?

![image](https://user-images.githubusercontent.com/859932/30534446-383b31e6-9c99-11e7-9d75-6b01159c3171.png)

**Comment by jeongjaehong** [comment]
WAS구동시 이미 로딩되어 삭제할수 없는 jar파일을 선택하는 경우 "삭제" 버튼을 비 활성화 하여 삭제할 수 없도록 하거나 적절한 안내 메시지를 표시하여 was재구동 전에 업로드 했던 jar파일만 바로 삭제 할수 있도록 해야 할듯 합니다.

**Comment by hangum** [comment]
@jeongjaehong  네 실제로 삭제를 시도하는데 사용하고 있어서 나오는 메지로 보입니다.
기존 드라이버를 삭제하고 새로운 드라이버를 올리면 톰켓은 무조건 재시작해야 합니다.
(드라이버 폴더에 가서 파일을 복사하시고 새롭게 재시작하시지요)

**Comment by jeongjaehong** [comment]
서버의 리소스(jdbc 드라이버)경로에서 해당 jar 파일을 교체(구 버젼 파일 삭제) 하고 was(톰캣)재시작 하여 해결 하였습니다. 
새로운 드라이버를 등록하는것이 아니라 드라이버 교체 작업을 할때는 어쩔 수 없을것 같습니다.  ^^;
