### ISSUE TITLE
환경설정 문의

### ISSUE THREAD

**Issue by youngpda** [hangum/TadpoleForDBTools#1037]
안녕하세요? 

RAP 관련 레퍼런스를 찾던 중에 'Tadpole DB HUB ' 을 알게 되었는데요.

프로그램을 동작시켜보려고 하였으나 환경세팅에서 애를 먹고 있습니다. 

가이드에 언급된 내용데로 한 것 같기는 한데 뭔가 빠진게 있는 듯합니다.

분명 제가 실수한 부분이 있는 것 같은데 어디서 잘못 되었는지 찾지를 못하고 있습니다.

답변 부탁드리겠습니다. 감사합니다.

제가 수행해본 환경설정 과정입니다.

1. https://github.com/hangum/TadpoleForDBTools/ 에서 master branch 를  local git 저장소로 내려 받았습니다.
    - local git 저장소의 프로젝트를 worksapce 로 copy 하였습니다

2. 워크스페이스 인코딩을 UTF-8 로 하였습니다. 

![workspaceencoding](https://user-images.githubusercontent.com/11848440/30575527-583380e0-9d3c-11e7-9567-a2dd61947fdf.JPG)

3.Target Platform 설정을 다음과 같이 하였습니다.

 3-1. 이클립스 변수 등록
   : Tadpole 전체 프로젝트가 있는 workspace 를 변수로 등록하였습니다.
   
![variable](https://user-images.githubusercontent.com/11848440/30575546-8c61730e-9d3c-11e7-810f-66e042933e5b.JPG)

 3-2. 타겟 파일은 tadpolea-rap-2.0.0-emf-standalone.target 를 사용하였습니다.

![target](https://user-images.githubusercontent.com/11848440/30575560-a286ecc2-9d3c-11e7-95bd-9f49a7ae7a52.JPG)
   

 3-2. API Baselines 을 다음과 같이 설정하였습니다.
 : 가이드내용에 대한 이해가 부족하여 Location을 eclipse Home 혹은  workspace 로 각각 설정해봤습니다.  

![api-baseline-2](https://user-images.githubusercontent.com/11848440/30575591-d9bbb7e0-9d3c-11e7-9d91-e07db7bf70e6.JPG)

   <baselines를 eclipse 홈으로 하고 project clean 한 경우>
  
![clean-1](https://user-images.githubusercontent.com/11848440/30575603-f4db09b8-9d3c-11e7-95d8-8ece418cbcc4.JPG)

   <baselines를 workspace로 하고 project clean 한 경우>

   
![clean-2](https://user-images.githubusercontent.com/11848440/30575604-f77e47ac-9d3c-11e7-83e0-f0dac3a3eb3a.JPG)

  
   * 두 경우 모두 프로젝트에 오류가 남아있습니다. ㅠ.ㅠ 

p.s :
Target Definition 에 아래와 같은 경로 문제가 발생합니다. 
이부분을 해결해야 모든게 바로 잡히는 것인가요?

![target-2](https://user-images.githubusercontent.com/11848440/30575624-22653462-9d3d-11e7-84d7-785747d4ecae.JPG)

**Comment by hangum** [comment]
@youngpda  타겟플렛폼을 설정하실 때 target-tadpolea-1.7.1.target 로 해보시지요.
