### ISSUE TITLE
오브젝트 탐색기의 필터기능 강화.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1038]
필터링 할때 오브젝트 설명(comment)등에 입력된 내용으로도 필터링이 가능하면 좋을듯 합니다.

테이블명이 갑자기 생각이 안나거나 할때는 comment에 입력해 놓은 태그 정보나 코멘트를 사용하여 필터링 해서 찾을 수 있으면 편리할것 같습니다. 

근본적으로 테이블명이 저따위면 안되는데....ㅠㅠ 

![image](https://user-images.githubusercontent.com/859932/30629163-61922644-9e15-11e7-88ff-caf65a57ca22.png)

**Comment by hangum** [comment]
아네. 괜찮을듯합니다.
