### ISSUE TITLE
sql 템플릿 관리기능

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1044]
1. 템플릿 목록 아래쪽의 미리보기 내용은 수정후에 자동 저장되거나 하는 내용이 아니라면 편집이 안되는게 맞을것같습니다.
2. 수정기능에서 개인용, 또는 공유(공통) 템플릿으로 변경할 수 있으면 좋겠습니다.
3. 목록에서 더블클릭하면 에디터가 열려있지 않으면 아무런 동작이나 알림 메시지가 없습니다.
    3.1. 에디터 창을 열고 사용하라고 메시지를 주거나 자동으로 에디터 창을 하나 열고 해당 내용을 에디터에 뿌려주면 좋을것 같습니다.

4. 공유 템플릿 추가 버튼을 클릭한 후에 추가한 템플릿 내용이 목록화면에 추가(저장)되지 않습니다.
5. 하나이상의 sql템플릿이 추가되지 않습니다.
 

![image](https://user-images.githubusercontent.com/859932/30951912-5f651bb4-a460-11e7-82af-029a0b5b0e45.png)

**Comment by hangum** [comment]
4,5 여러개 추가되는데요.  혹시 로그 줘보세요.
![image](https://user-images.githubusercontent.com/1335915/31027676-f9ddf816-a585-11e7-9bb6-de0aba11a58f.png)
