### ISSUE TITLE
[1.7.4r13] Standalone을 macOS에서 실행 시 JRE를 찾습니다.

### ISSUE THREAD

**Issue by woowahan-jaehoon** [hangum/TadpoleForDBTools#1045]
안녕하세요.

https://sourceforge.net/projects/tadpoledbhub/files/1.7.x/1.7.4r13/
의 
macosx.cocoa.x86_64.zip
를 받아서 사용하고 있습니다.

macOS에서 실행하면 JDK 1.8.0_144 이 설치되어있습니다만
실행하면 
```No Java runtime present, requesting install.``` 
라는 메시지가 표시되면서 종료됩니다.
macOS에서 macOS용 JDK 1.6을 설치하라는 안내메세지가 표시되는 것 봐서는
JRE 1.6을 찾는 것 아닌가 하는 생각이 들었습니다.

당연히 JRE 1.6을 설치하면 동작은 잘 되긴 하는데,
이번에 High Sierra로 OS업그레이드 했더니 
재설치해주어야하는지 메세지가 다시 보여서
본 김에 Issue를 올리게 되었습니다.

**Comment by woowahan-jaehoon** [comment]
Launcher쪽 테스트를 좀 해보았습니다.

-vm 옵션으로는 어떤 값을 줘도 되지 않아서,
혹시나 해서 Eclipse Mars에 포함된 launcher 플러그인을 이식하니까 잘 동작 하네요... ^^;;
(Eclipse Mars를 선택한 이유는 적당히 옛날 Eclipse를 선택해보자고 생각해서 선택했습니다.)

아래 두 개만 이식했고, 
- org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
- org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.300.v20150602-1417

당연히 MacOS/tadpole-standalone.ini 를 이식한 파일과 경로에 맞게 수정했습니다.
(TadpoleHubOpenSource/tadpole-standalone.ini는 영향을 주지 않더군요)

```
-startup
#../TadpoleHubOpenSource/plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
../TadpoleHubOpenSource/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
#../TadpoleHubOpenSource/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.200.v20130521-0416
../TadpoleHubOpenSource/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.300.v20150602-1417
-nl
en
-standalone
-defaultDB
MySQL
-useDB
Altibase,Cubrid,MariaDB,MongoDB,MSSQL,MySQL,Oracle,RedShift,PostgreSQL,SQLite,Tibero
-vmargs
-Dfile.encoding=UTF-8
-Dorg.osgi.service.http.port=10081
-Declipse.ignoreApp=true
-Dosgi.noShutdown=true
-Declipse.registry.MultiLanguage=true
-Dorg.eclipse.jetty.server.Request.maxFormKeys=200000
-Dorg.eclipse.jetty.server.Request.maxFormContentSize=-1
-Xverify:none
-XX:+UseParallelGC
-XX:-UseConcMarkSweepGC
-XX:PermSize=32M
-XX:MaxPermSize=128M
-XX:MaxNewSize=128M
-XX:NewSize=64M
```

eclipse_1507.so의 로직이 오래된 것 같아 보이는데,
아무튼, Launcher 업그레이드를 한 번 하셔야할 것 같습니다. ^^;

**Comment by woowahan-jaehoon** [comment]
개발자 매뉴얼을 보니까 최소 버전이 Eclipse Kepler이어서 이 버전을 추가로 참조해서 테스트해보았습니다.
일단 Launcher 버전이 같군요.
하지만 cocoa용 라이브러리 버전이 차이가 있어서, 이식해서 테스트 해보았고
이식하니까 잘 됩니다.

최종성공한 버전은 이겁니다.
- org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.200.v20140116-2212

**Comment by hangum** [comment]
@woowahan-jaehoon  감사합니다.  eclipse rcp 타겟을 rap로 쓰다보니 몇가지 고쳐 쓰는게 있어서 풀리퀘스트 날려주신것을 받아 들이기 힘들지만, 애초에 말씀하셨던 아이디어를 코드에 담아서 문제를 해결했습니다.
감사해요.
