### ISSUE TITLE
프로시져 실행시 인수 타입이 날짜일 경우 

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1048]
프로시져 실행시 인수 타입이 날짜일 경우 yyyy-mm-dd, yyyymmdd, yyyy/mm/dd  형식으로 지정해도 모두 타입오류가 발생합니다.

인수를 프로시져로 넘길때 적절하게 타입을 변환하여 넘길수 있도록 수정되어야 할듯 합니다.

![image](https://user-images.githubusercontent.com/859932/31363765-9e3aed02-ad9b-11e7-8958-174f849153db.png)

**Comment by hangum** [comment]
@jeongjaehong  오라클에서 이지요?

실행해 볼 수 있도록 간단한 셈플을 만들어 주실수 있으세요?

**Comment by jeongjaehong** [comment]
오브젝트 실행 창에서 arg_date 에 아무런 값도 입력하지 않을경우  call sp_tran을 호출할때 call sp_tran(null)로 호출되는걸로 보입니다. 

프로시져 설계상 인수에 값이 없을경우에는 현재날짜가 기본값으로 사용되도록 했기 때문에 call sp_tran; 으로 호출되도록 해야 할듯 합니다. 

CREATE OR REPLACE PROCEDURE       sp_testsample (arg_date DATE := SYSDATE)
IS
BEGIN
    dbms_output.put_line('---------------begin------------------');
    dbms_output.put_line('result:' || to_char(arg_date, 'yyyy-mm-dd') );
    dbms_output.put_line('result:' || to_char(nvl(arg_date, sysdate), 'yyyy-mm-dd') );
    dbms_output.put_line('---------------end------------------');
END;

![image](https://user-images.githubusercontent.com/859932/31370173-83545c02-adc4-11e7-87e1-ba7d8639e61a.png)

**Comment by jeongjaehong** [comment]
기본값이 있을경우 ... 

![image](https://user-images.githubusercontent.com/859932/31370246-ee859cca-adc4-11e7-9866-f986598654e5.png)

**Comment by hangum** [comment]
뭔말인지 모르겟다..--;; 형이 수정해 줘요.

**Comment by jeongjaehong** [comment]
프로시져 실행 ui에서 인수를 입력 안 했을 때 null로 할것인지 해당 인수는 지정을 안하고 기본값을 사용할 것인지 여부를 지정할 수 있어야 할까요? 

default값이 지정된 인수를 지정하지 않으면 인수가 부족하다고 에러가 나겠군요. 

기본값이 있는 인수들은 뒷쪽으로 배치를 하긴 하지만 

인수가 4개일때 2개는 반드지 지정해야하고 2개는 기본값이 있다고 가정할때 뒤의 2개중 1개 또는 2개를 대입하거나 하나도 지정하지 않고 호출할 수도 있겠네요...  이런경우에 의도한 대로 실행시킬 수 있도록 ui를 변경해 줘야 할것 같습니다. 

가령 기본값이 있는 인수일 경우에는 기본값사용, 미지정 이라는 체크박스를 둬서 선택하게 한다거나 해서...

**Comment by hangum** [comment]
다른 툴들은 어떻게 처리 하고 있을까요?

**Comment by jeongjaehong** [comment]
프로시져의 인수목록을 조회할때 기본값이 있는지 보고 해당 정보를 인수 입력을 위한 대화상자에 그대로 넣어주거나 아무런 값도 입력하지 않았을 경우에 null로 처리하지말고 값을 입력하지 않아야 할듯. 

여행 다녀와서 체크해 볼께~

**Comment by hangum** [comment]
@jeongjaehong  응 즐겁게 다녀오세요~

**Comment by jeongjaehong** [comment]
프로시져의 인수 타입 종류별로 사용자가 입력한 값을 형변환을 해줘야 할거 같은데 ... 문자열 타입인 경우랑, 숫자, 날짜 이렇게 3자기 케이스만 체크해도 될까요? ^^;

일단은 date형일때 오류나는걸 기준으로 아래처럼 java.sql.Date타입으로 형변환 후에 실행하니 에러가 없이 정상 실행되는것 까지는 확인이 되었습니다.

![image](https://user-images.githubusercontent.com/859932/32422439-a2f5bbf8-c2e3-11e7-968d-df13a15e287f.png)

**Comment by jeongjaehong** [comment]
**사용자가 인수값을 입력했을때...**
![image](https://user-images.githubusercontent.com/859932/32426090-20cb0a9e-c2fb-11e7-86e3-541ac85fa9ee.png)


**사용자가 인수값을 입력하지 않았을때...**
![image](https://user-images.githubusercontent.com/859932/32426074-044b7232-c2fb-11e7-9f43-814012afd7e5.png)
