### ISSUE TITLE
바이너리 다운로드 관련

### ISSUE THREAD

**Issue by maxtortime** [hangum/TadpoleForDBTools#1050]
홈페이지 https://sites.google.com/site/tadpolefordb/sayongseolmyeong/seolchimichsijagjonglyo 를 보시면 http://code.google.com/p/tadpole-for-db-tools/downloads/list 에서 바이너리를 다운로드하라는 지시가 있는데 클릭시 GitHub로 연결됩니다.

좀 더 찾아보니 https://sourceforge.net/projects/tadpoledbhub/files/1.7.x/1.7.4r13/ 에서 바이너리를 확인할 수 있었는데 홈페이지 수정이 필요할 것 같습니다. 감사합니다.

**Comment by hangum** [comment]
이전 내용으로 링크가 잘못 걸려있네요.  수정할수 있도록 하겠습니다. 감사합니다.

**Comment by maxtortime** [comment]
위키 쪽도 링크가 잘못 걸려있었던 것 같습니다 ㅎㅎ

**Comment by hangum** [comment]
@maxtortime  네. 하나씩 확인해서 고쳐봐야겠네요.  감사합니다.
최신정보는 https://sites.google.com/site/tadpolefordb/ 에 있는걸 참조해주세요.
