### ISSUE TITLE
SQL 감사 화면에서 순번(?)이 일정치 않습니다.

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#1070]
SQL 감사화면에서 순번이 일정치 않아 일관되게 보이지 않습니다. 
1부터 시작하는 순번이면 좋겠습니다.

![image](https://user-images.githubusercontent.com/1335915/32919445-33515864-cb69-11e7-857d-2a0bc24038dc.png)

**Comment by jeongjaehong** [comment]
조회할 때 마다 번호가 달라지는 거에요? 아니면 데이터 베이스에 저장될때 결번이 생기는 건가요?

번호가 빠지더라도 항상 동일한 번호로 나오는게 중요한지 또는 조회될때 그냥 1부터 순차적으로 표시만 되면 되는건지 확인해 볼 필요가 있ㄱㅆ네요.

**Comment by hangum** [comment]
검색 조건에 따라 달라서 그래요.  실제 디비 순번을 바로 보여줘서 그래요

나의 iPhone에서 보냄

2017. 11. 20. 오전 10:36, jeongjaehong <notifications@github.com> 작성:
