### ISSUE TITLE
도움말->최신 버전 확인 미작동

### ISSUE THREAD

**Issue by maxtortime** [hangum/TadpoleForDBTools#1076]
![image](https://user-images.githubusercontent.com/10532570/33104045-6bd0a6b4-cf69-11e7-9330-9df89b5bb21f.png)

안녕하세요. 새 1.7.5 버전을 릴리즈하셔서 `도움말->최신 버전 확인`을 클릭해봤는데 최신화가 되어있지 않았습니다. 원래 동작이 안 되는건지 아니면 그냥 아직 저쪽만 갱신이 안 된건지 궁금합니다.

이건 제안이긴 한데 bitbucket 쪽 릴리즈 노트가 올라올때마다 bitbucket API를 이용해서 감지해서 갱신하는 방법도 있을 것 같긴 합니다.

감사합니다.

**Comment by hangum** [comment]
깃허브에 파일을 두고 하는데.. 그 파일 갱신을 못했네요. 
제보 감사합니다.

**Comment by hangum** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/1335915/33106862-c10e6324-cf77-11e7-83f8-a60e2f76491e.png">

최신 사항이 나오도록 업데이트 인포 파일을 수정했습니다. 감사합니다.
