### ISSUE TITLE
postgresql 에서 자리수 설정 오류 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#1078]
floating number 의 표시되는 자리수를 설정할 수 있는 기능이 있나요? 
예를 들어 postgresql 기준으로 select 0.3::float8   을 실행하면 0.29999999999999999 라고 나오는데,
사용자가 설정한 자리수에서 반올림해서 표시될 수 있는지 궁금합니다.

**Comment by hangum** [comment]
데이터를 string으로 형변환하는 중에 나오는 오류로 수정하였습니다. 

![image](https://user-images.githubusercontent.com/1335915/33194686-ff28b9f4-d114-11e7-9805-e281c494db0f.png)

**Comment by kth999** [comment]
수정 감사합니다.
자바가 익숙치 않아서, 코드를 받아서 윈도우용 standalone.exe 를 만드는데 어려움이 있습니다.
본 픽스가 반영된 릴리즈는 언제쯤 계획중이신가요?

**Comment by hangum** [comment]
2주전에 배포했던 버전에는 반영되었습니다.  최신버전을 사용해 보셔요. 


나의 iPhone에서 보냄

2017. 12. 5. 오전 8:40, kth999 <notifications@github.com> 작성:
