### ISSUE TITLE
API HUB User 권한 접속 후 테스트 결과.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1086]
1. API User로 접속했을때 표시되는 UI를 닫기[x]했을경우 다시 열 수 없으므로 메뉴에서 AIP User가 사용할 만한 메뉴만 표시하도록 메뉴 구성을 변경해야 할듯 합니다.

![image](https://user-images.githubusercontent.com/859932/33593005-cb11dfd2-d9d0-11e7-9dee-c4d360b26297.png)

2. Enterprise 버젼 사용자만 이용가능 한가요? 데이터 베이스 공유가 되지 않으면 사용 불가능 한듯 합니다.
 - 오픈소스 버젼이나 "그룹" 이 아닌 "개인사용자" 버젼으로 사용시에는 사용자를 추가할때 또는 api를 공유할때 추가된 사용자가 데이터베이스를 같이 공유되도록 해서 apif목록에 표시되도록 해야 하지 않을까요?

**Comment by jeongjaehong** [comment]
3. 실행 후 다운로드 받을때 결과 타입(json, csv, xml, html)에 따라 다운로드 받는 파일의 확장자를 변경해 주면 좋겠습니다. 
xml로 선택하고 실행 후 다운로드 하였지만 .txt로 다운로드 되었습니다.

![image](https://user-images.githubusercontent.com/859932/33593992-671871ee-d9d5-11e7-9311-aea6641e5622.png)

**Comment by jeongjaehong** [comment]
4. API User로 로그인 후에 목록을 더블클릭 하면 실행창이 열리면 좋겠습니다. 
현재는 상단의 실행 도구모음을 클릭 해야만 실행창이 열립니다. 

5. 목록에서 "설명", "URL", "API이름"등으로 조회할 수 있는 기능 또는 필터 기능이 있으면 좋겠습니다. 
api목록이 많아지면 현재 ui에서는 모든 api 목록이 전체 조회되어 표시되기 때문에 불편할듯 합니다.
최근에 등록된 api가 가장 위쪽으로 표시되도록 해서 최근 생성되었거나 최근에 조회(사용)한 api 50건 정도만 표시해주고 ...
사용자가 조회조건을 지정하여 추가로 조회하여 사용 할 수 있으면 좋겠습니다. 

6. API목록에 사용자가 직접 코멘트(주석)을 추가하여 다음에 해당 주석으로 api를 검색할 수 있으면 좋겠습니다. 
(사용자가 직접 태크를 추가하고 해당 태그로 검색)
![image](https://user-images.githubusercontent.com/859932/33594118-faee5406-d9d5-11e7-8360-3026e65ed0b3.png)

**Comment by jeongjaehong** [comment]
7. API 사용이력을 로깅하면 좋겠습니다.
![image](https://user-images.githubusercontent.com/859932/33594521-8da33090-d9d7-11e7-94a8-e48e7d542fcf.png)

**Comment by hangum** [comment]
1) 별도의 메뉴를 만들도록 하겠습니다.
2) 엔터프라이즈 버전만 사용해야 맞을듯합니다. 
3) 수정 할 수 있도록 하겠습니다.
4) 수정 할 수 있도록 하겠습니다.
5) URL/이름으로 검색할 수 있도록 하겠습니다.
6) 
7) 감사 로그로 로깅을 합니다.

**Comment by jeongjaehong** [comment]
api의 설명 내용을 api를 등록한 관리자나 개발자 외에 API User권한의 사용자가 해당 설명을 직접 수정할 수 있도록 해도 될듯 합니다. 

가령 설명에 국민연금관리공단 신고용, 또는 개인별 수당 지급내역, 초과근로수당 수령자 명단, 등등...
