### ISSUE TITLE
티베로(tibero) 디비 연결 문의

### ISSUE THREAD

**Issue by GoGillDong** [hangum/TadpoleForDBTools#1096]
안녕하세요

티베로 디비를 지원한다는 것을 알게되어 사용해보려고 합니다..

그러나 툴에서 데이터베이스를 추가하는 화면에소 tibero는 조회되지 않습니다..

매뉴얼이나 다른 문서들을 찾아봤는데 잘 몰라서 질문글 올립니다..

![image](https://user-images.githubusercontent.com/5512509/34857396-e648a13e-f78d-11e7-9272-38e88b415ca4.png)

감사합니다 ^^

**Comment by hangum** [comment]
@GoGillDong  혹시 해결 하셨는지요?

**Comment by GoGillDong** [comment]
@hangum 제가 예전버전을 다운받은 것 같습니다, 최신껄로 재차받으니 잘됩니다 감사합니다!
