### ISSUE TITLE
오브젝트 탐색기에서 오브젝트 탭간 이동시 선택정보 유지.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1098]
가령 테이블을 탭에서 특정 테이블을 선택하면 하단에 선택된 테이블의 컬럼 정보가 표시됩니다.
이때 프로시져 탭이나 뷰탭으로 이동했다가 다시 테이블 탭으로 돌아오면 하단 컬럼 정보는 그대로 유지되어 있지만 상단 테이블 목록에서 어떤 테이블이 선택되어 있는 상태인지 알 수 없습니다.

현재 선택된 테이블의 행이 selected상태로 표시되면 좋겠습니다. 

![image](https://user-images.githubusercontent.com/859932/35074874-5d77f2ec-fc33-11e7-92a5-85e91f7f3299.png)
(처음 테이블 선택시)
![image](https://user-images.githubusercontent.com/859932/35074956-d46789e4-fc33-11e7-8168-07152d96e34b.png)
(컬럼으로 포커스가 이동했을때)
![image](https://user-images.githubusercontent.com/859932/35074981-f7b0f110-fc33-11e7-821e-41bb5d9c4cb7.png)
(다른탭으로 이동했다가 다시 테이블 탭으로 돌아왔을 때)

**Comment by hangum** [comment]
좋네요.
