### ISSUE TITLE
MySQL 컬럼 수정 다이얼로그 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#1100]
MySQL의 컬럼 수정 다이얼로그에서 널 수정 항목이 잘 못 표시됩니다. 
원래 컬럼은 널 입력 가능인데, 불가능으로 표시되고, 불가능 컬럼은 가능으로 표시됩니다. 

테스트 버전 v1.7.5 r2
환경 도커기반(전체버전일 가능)

![image](https://user-images.githubusercontent.com/1335915/35343764-c210655a-016e-11e8-936c-f224f0929de8.png)

@이석곤님 재보.

**Comment by hadesyi** [comment]
감사합니다. 다음에는 제가 수정해서 풀 리퀘스트 하겠습니다. ^^

**Comment by hangum** [comment]
@hadesyi  꾸벅. 페북에도 같이 해주세요.~~~ ^^  티셔츠는 나눔할때 혹시나 잊어버리면 슬쩍 찔러주시구요.  (기억하고 있겠습니다.)
