### ISSUE TITLE
조회 후 쿼리 결과를 sql파일로 다운로드 받은 후 다른 디비의 에디터창에서 불러올때 한글이 깨집니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1106]
재현과정

1. mysql에서 쿼리한다.
다운로드를 선택하고 "sql" 탭에서 insert문으로 변환하여 다운로드한다.(utf-8)선택
2. oracle 에디터 창을 새로 열고 불러오기 한다.
3. 불러오기 결과의 한글 내용이 깨져 보임 (다운로드한 파일을 텍스트 에디터에서 확인할 경우 정상임)

다운로드 할때 문자셋을 euc-kr로 했더니 불러오기 후에 한글이 깨지지 않았음.
추측 및 개선 고려 사항 : 불러오기 할때 문자셋을 (euc-kr, utf-8)등을 지정할 수 있으면 좋겠습니다.
다운로드는 기본값이 utf-8, 불러오기 할때는 euc-kr로 적용되는건 아닐까요?

![image](https://user-images.githubusercontent.com/859932/36139527-2e34db22-10e1-11e8-987f-7245fc6042ff.png)

![image](https://user-images.githubusercontent.com/859932/36139650-b6bf34b0-10e1-11e8-89ec-665843ded3f1.png)

**Comment by hangum** [comment]
사용 환경이 맥이세요?

**Comment by jeongjaehong** [comment]
네~
맥에서 크롬 브라우져 였던것 같습니다.

**Comment by hangum** [comment]
네 현재 로직을 살펴보는데 bom 이 없으면 cp949(원도우)로 처리하는데, 디폴트로 UTF-8로 처리하도록 수정.
