### ISSUE TITLE
1.6 버전 이후로 프로젝트 로드시 에러가 납니다.

### ISSUE THREAD

**Issue by bokunn91** [hangum/TadpoleForDBTools#1107]
1.4.2 버전으로는 해당 git 소스를 내려받은 후
매뉴얼대로 했을때 소스 오류 없이 실행까지 되었습니다.

그런데 1.6 버전 이후로는 컴파일시 에러가 발생하고 있습니다.
실제로 사용하려는 버전은 1.7.4.r13 버전입니다만,
target 프로젝트에서 "해당 프로젝트를 타겟 프로젝트로 설정" 에서부터
"eclipse-babel-rap" 과 관련하여 해당 경로가 존재하지 않는다는 에러가 뜨고 있습니다.

혹시 관련에러에 대하여 어떻게 해결할 수 있을지 문의드립니다 :)

해당 서비스와 관련해서 이렇게 오픈소스로 제공해주셔서 감사합니다.
많은 도움이 되고 있습니다. :)

**Comment by hangum** [comment]
프로젝트가 현재 최신 프레임웍과 라이브러리를 사용하고 있어 아무래도 master 버전으로 작업을 해보심이 좋겠습니다. 
감사합니다.

**Comment by bokunn91** [comment]
답변 감사드립니다. 조언주신대로 실행후 안된다면 다시한번 문의드려보겠습니다. :)
감사합니다.

**Comment by hangum** [comment]
마스터 버전을 사용하시면 조금더 수월하실것으로 생각되요.

**Comment by bokunn91** [comment]
마스터 버전에는 target 파일들이 뒤에 모두 "_" 언더바 처리되어있던데
동일하게 2.0.0 타겟파일 사용하면 되나요? :)

**Comment by hangum** [comment]
네._는 조만간 지우게 될 친구들이라 그렇게 하였습니다. 
아직 예전 타겟으로 동작하는 일부가 있기는 해서요.

**Comment by seunghun-kim** [comment]
안녕하세요. 
개발환경 구축죽에 tadpolea-rap-2.0.0-emf-standalone.target_ 파일에서 _를 제거 후 target platform으로 지정했더니 다음 이미지처럼 ${project_loc:/targetProject}에서 몇몇 디렉토리가 없어서 에러가 발생하였습니다.
가이드는 [개발환경 설치에 관하여 - Target Platform 설정합니다.](https://tadpoledbhub.atlassian.net/wiki/spaces/TADPOLE/pages/2621473) 부분입니다.

<img width="1674" alt="tadpole_dev_setting" src="https://user-images.githubusercontent.com/16603187/36958491-9f0ae140-207f-11e8-9f45-247e84b9cbef.png">

혹시 2.0.0 target 말고 다른 target을 사용해야 하나요?

소스코드는 현재 마스터 브랜치의 코드로 사용하였습니다.

**Comment by hangum** [comment]
최신 마스터 브랜치와 1.7.6 타겟으로 해보시겠어요.  
몇몇 클랴스 오류는 주속으로 막으셔도 오픈소스 동작 하는데 이상 없을 거에요. 

나의 iPhone에서 보냄

2018. 3. 5. 오후 2:16, huna <notifications@github.com> 작성:
