### ISSUE TITLE
공유 템플릿 기능의 보완.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1111]
공유 템플릿 목록에서 더블클릭할 경우 에디터 창이 열려 있으면 해당 에디터에 리소스 내용이 복사 되는데...

에디터가 열려 있지 않으면 아무런 액션이 없습니다.

먼저 에디터를 오픈하십시오. 등의 적절한 메시지를 띄우거나 현재 선택된 데이터 베이스의 sql에디터 창을 열고 해당 에디터에 내용을 넣어주면 좋을것 같습니다.

![image](https://user-images.githubusercontent.com/859932/37064940-40b86306-21e2-11e8-828d-89c73ef57e46.png)

**Comment by hangum** [comment]
개선했습니다.
