### ISSUE TITLE
utf-8 한글 깨지는 문제

### ISSUE THREAD

**Issue by 4tyu4tyu** [hangum/TadpoleForDBTools#1112]
안녕하세요. 라인게임즈 인프라팀 김수철입니다.
쿼리 실행 중 한글이 깨지는 문제가 있어 리포팅합니다.
인코딩은 utf-8로 되어있고 notepad++ 에서는 잘 나오는 것 확인 된 쿼리 입니다.
![default](https://user-images.githubusercontent.com/38734381/39264893-e2152e60-4900-11e8-9f1d-f600571a5527.PNG)
아래 스샷 보시면 notepad++ utf-8로 설정되어 있는 것 확인 할 수 있습니다.
![notepad](https://user-images.githubusercontent.com/38734381/39264968-1517cffc-4901-11e8-9e20-a45d60f2ad00.PNG)
확인 부탁 드립니다.

**Comment by 4tyu4tyu** [comment]
추가 확인된 사항이 있습니다.
notepad++ 에서 copy & paste 하면 정상적으로 보이지만 sql파일 업로드로 파일을 올릴 경우 한글이 깨집니다.

**Comment by hangum** [comment]
@4tyu4tyu  안녕하세요.  테드폴허브에서 납품한 엔터프라이즈 버전을 사용하고 계시지요?

**Comment by 4tyu4tyu** [comment]
안녕하세요. 
라인게임즈 인프라팀 김수철입니다.
​
​
​
현재 사용중인 버전 입니다.
​
확인 부탁 드립니다!

-----Original Message-----

**Comment by 4tyu4tyu** [comment]
아래 현상 발생했던 쿼리파일 공유 드립니다.
​
첨부파일 확인 부탁 드립니다.

-----Original Message-----

**Comment by hangum** [comment]
@4tyu4tyu  hangum@tadpolehub.com 으로 메일 부탁드려요. 
이슈는 확인해서 연락드리겠습니다.

**Comment by hangum** [comment]
지금 사용하고 계시는 버전 1.7.5r2 버전으로 확인되는데요. 최시버전 1.8.2 버전에서는 수정된것으로 확인되었습니다. 
감사합니다.

**Comment by hangum** [comment]
구명근님에게 페치일정을 문의했구요. 
혹시 다른 불편한 사항은 없으신지요? 좋은하루 되십시오.
