### ISSUE TITLE
오라클의 테이블 및 컬럼 주석(설명) 입력기능 버그

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1121]
1. 테이블 주석 입력후 위, 아래 방향키로 이동불가.
2. 설명 컬럼을 클릭해서 하단의 컬럼목록이 갱신된 후에 컬럼의 설명(주석)을 입력하면 주석이 제대로 등록되지 않음.
   -> 테이블명을 클릭해서 이동 후 하단 컬럼정보가 새로고침 된 후에 컬럼 설명(주석)을 입력하면 이상없음.
   -> 코멘트 입력 대상이 되는 테이블명이 내부 코멘트 등록 작업시 사용하는 변수에 반영되지 않는듯.
3. 컬럼의 설명(주석)을 입력 후 앞쪽 방향키를 누르면 커서가 이동하지 않고 전체선택 작업이 됨.
4. 컬럼의 설명(주석)을 입력하고 다른컬럼으로 이동하거나 하지 않고 상단의 다른테이블을 입력하면 최종 등록하던 컬럼 코멘트는 반영되지않음.

**Comment by jeongjaehong** [comment]
테이블 선택할때 테이블명을 클릭하지 않고 설명(코멘트) 부분 클릭할 경우 
final TableDAO tableDAO = (TableDAO)is.getFirstElement(); 에서 null이므로 테이블명을 가져오지 못해서 코멘트 등록이 되지 않았음.

**Comment by hangum** [comment]
코드를 보다보니 
viewer.update(dao, null);  이 코드가 일반적으로는 변경된 로우의 포커스가 가야 하는데... 
변경된 로우의 포커스를 잃어 버리게 되네요. 

몇시간째 보고 있는데 도대체 모르겟다. --;;

**Comment by jeongjaehong** [comment]
테이블 목록을 표시하는 tableview를 클릭할때 설명(주석) 부분을 클릭하면 나중에 이벤트에서 getFirstSelect인가 하는걸로 읽어오면 null이더라구..

관련해서 어제 커밋했는데...

**Comment by hangum** [comment]
@jeongjaehong  엔터레파지토리에 커밋했어요?
