### ISSUE TITLE
도커 이미지 mysql 8.0 접속이 안됩니다.

### ISSUE THREAD

**Issue by hoksi** [hangum/TadpoleForDBTools#1132]
도커를 이용하여 mysql 8.0 접속시 
"데이터베이스 연결에 실패했습니다. (Unknown system variavle 'query_cache_size')"
메시지가 뜨면서 접속이 되지 않습니다.

어떻게 하면 좋을까요?

**Comment by hangum** [comment]
MySQL 8.x 부터는 query_cache_size 옵션이 사라져서 그렇습니다. 
테드폴허브에서는 5.x버전의 Connector/J 드라이버를 사용하고 있어서 나타나는 문제로 보여집니다
하여서 MySQL 최신 드라이버를 이용해서 작업하면 해당 문제가 사라질것으로 보여집니다.
다음배포시에 최신 드라이버로 배포할 수 있도록 하겠습니다.

감사합니다.

**Comment by hoksi** [comment]
버그 픽스된 도커 버전이 빨리 배포 되었으면 좋겠습니다.
답변 감사합니다.

**Comment by hangum** [comment]
@hoksi 보통 3-6개월 릴리즈라... . 좀 기다리셔야지 싶습니다. 
8.x 버전은 고객사에서 사용하는 곳이 없는데 업무적으로 사용하시는 건가요?

**Comment by hangum** [comment]
v2.2.0 a4에서 수정되었습니다.
감사합니다.
