### ISSUE TITLE
한번에 여러줄의 query를 실행하기 

### ISSUE THREAD

**Issue by darkancia** [hangum/TadpoleForDBTools#1133]
전체 쿼리를 불러오기 한 후 일부 쿼리를 실행하기 위해서 
실행하고자 하는 라인만큼 드래그 한 후 실행하면 상위 쿼리 1개만 실행됩니다. 

실행하고자 하는 쿼리만큼 드래그 후 실행이 불가능한가요?

**Comment by hangum** [comment]
안녕하세요
테드폴허브 조현종입니다. 

실행하려는 쿼리를 블럭하신후 실행하면 블럭된 부분이 실행 되는데요. 
다른 의미이신지요?

버전과 캡쳐 부탁드려요

나의 iPhone에서 보냄

2018. 7. 30. 오후 3:57, darkancia <notifications@github.com> 작성:

**Comment by darkancia** [comment]
해당 내용은 메일로 문의 드리겠습니다.
