### ISSUE TITLE
export war 방법

### ISSUE THREAD

**Issue by dvqkrdlswhd** [hangum/TadpoleForDBTools#1139]
안녕하세요. Tadpole 소스를 받아서 이것저것 확인해보고 있습니다.

[개발환경설치에 관하여](https://tadpoledbhub.atlassian.net/wiki/spaces/TADPOLE/pages/2621473)
그런데 위 링크의 배포 방법에 나오는 패키지들이 보이지않더군요. 어떤방식으로 export 해야하나요?

소스 버전은 v1.8.4 입니다.

**Comment by hangum** [comment]
안녕하세요. 

https://www.eclipse.org/rap/developers-guide/devguide.php?topic=deployment.html
부분을 참조하시면 좋겠습니다.

**Comment by dvqkrdlswhd** [comment]
@hangum 
감사합니다.
