### ISSUE TITLE
어드민 로그인

### ISSUE THREAD

**Issue by dvqkrdlswhd** [hangum/TadpoleForDBTools#1140]
안녕하세요. 프로젝트를 clone 후 이것 저것 만져보고 있는데 어드민으로 로그인이나 가입은 따로 존재 하지 않나요?

배포된 war파일을 받아서 처음 실행해보면 어드민을 등록하는데 소스를 통해 실행하게 되면 그런 메뉴가 뜨질 않습니다. war파일로 export 후에도 동일합니다. 

방법이 있다면 알려주시면 감사하겠습니다.

**Comment by hangum** [comment]
어드민 메뉴가 활성화 되는데요. 
어떤 메뉴를 찾으시는지요?

![image](https://user-images.githubusercontent.com/1335915/44387832-911fef00-a561-11e8-9427-27f27907545b.png)

**Comment by dvqkrdlswhd** [comment]
@hangum 
프로젝트를 처음에 실행하게 되면 바로 로그인화면이 보여서 어드민으로 가입하는 페이지가 보이지 않았습니다. 혹시 디폴트 어드민 계정이 존재하는 건가요?

**Comment by hangum** [comment]
테드폴디비허브를 처음 시작했을때 위자드화면에서 사용자를 입력하셨을텐데요.
그 사용자가 어드민이 되도록 되어 있어요.

**Comment by dvqkrdlswhd** [comment]
아 프로젝트를 여러번 지웠다 실행해서 첫 wizard 페이지가 보이지 않았나 보네요. 한번 제대로 지우고 다시 해보겠습니다. 감사합니다. 소스가 재미있네요 ㅎㅎ

**Comment by hangum** [comment]
기존에 Eclipse rcp 를 해보오셨나 보네요. 
대단하세요.

**Comment by dvqkrdlswhd** [comment]
덕분에 처음 접해봤습니다.ㅎㅎ 아 추가로 질문이 있었는데 깜빡하고 놓쳤네요.
그럼 소스 프로젝트를 실행하면서 처음 실행하면서 생기는 엔진디비는 어디에 위치하고 있나요?

**Comment by dvqkrdlswhd** [comment]
아 찾았네요! 감사합니다! ㅎㅎ

**Comment by hangum** [comment]
개발환경에서는 그럴수도 있겠네요.
패스워드는 아마도 tadpole 일 거에요.

**Comment by dvqkrdlswhd** [comment]
친절한 답변 정말 감사합니다.
