### ISSUE TITLE
아무리봐도 DB 타입 추가를 모르겠습니다.

### ISSUE THREAD

**Issue by disaqua** [hangum/TadpoleForDBTools#1149]
일단 시작하기에 앞서 이런 툴을 오픈해주셔서 감사합니다.

제가 티베로로 작업 할일이 있어서 사용하려고 합니다.

근데 아무리 봐도 DB타입 추가를 어찌 해야 할지 몰라서 이렇게 올립니다.

**Comment by hangum** [comment]
사용하시는 버전이 어떻게 되시는지요?

**Comment by disaqua** [comment]
안녕하세요.
 
1.8.4 버전이고 
 
jar 업로드 해봐도 반응이 없고.. 난감하네요. 
 
어떤방법을 써야 추가 되는지 알려주시길 바랍니다.
 
 
 
 
-----Original Message-----

**Comment by hangum** [comment]
@disaqua  확인해보겠습니다.

**Comment by hangum** [comment]
원인을 확인하였고 소스로는 수정되었습니다. 
주중에 마이너 패치를 하도록 하겠습니다. 감사합니다.
