### ISSUE TITLE
우측 상단에 로그인 정보 및 버젼정보가 표시되면 좋겠습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1150]
현재 로그인되어 있는 사용자 정보가 표시되면 좋겠습니다.

2가지 이상의 role을 부여받은 사용자가 여러계정을 사용할 경우 현재 로그인 되어 있는 사용자가 어떤 사용자 인지 쉽게 확인 할 수 있도록 하면 좋을듯 합니다.

![image](https://user-images.githubusercontent.com/859932/49778862-8c6a8b00-fd4a-11e8-9faa-675fcd4e5934.png)

**Comment by hangum** [comment]
![image](https://user-images.githubusercontent.com/1335915/57672799-8f004200-7654-11e9-9c3d-2ffc49ac164b.png)

표시되도록 개선되었습니다.
