### ISSUE TITLE
외부 확장브라우져 등록시 url이 중복되는 경우 뜨는 알림메시지 오류. 

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1151]
외부 확장브라우져 등록중 url이 중복될 경우 알리메시지에서 "이름"이라고 표시됩니다.

접속 URL이 중복되었습니다. 또는 동일한 접속URL의 브라우져가 이미 등록되어 있습니다. 등으로 표현되는게 좋겠습니다.

또한 데이터베이스 추가 중에는 확장브라우져 등록이 안되어야 하는게 맞지 않을까요?
아직 데이터베이스 정보가 저장되지 않은 상태에서 확장브라우져가 등록이 되면 어떤 디비의 확장 브라우져 정보인지 알수가 없는 상황이라 저장이 안되게 하거나 먼저 디비 등록정보를 저장하도록 안내해야 할것 같습니다.

![image](https://user-images.githubusercontent.com/859932/49986271-8bd42d80-ffb2-11e8-9642-441f2deda146.png)

**Comment by hangum** [comment]
확인해보겠습니다.

**Comment by hangum** [comment]
수정되었습니다.
