### ISSUE TITLE
데이터베이스 등록 후 쿼리 전체 이동 기능 추가

### ISSUE THREAD

**Issue by hkjang** [hangum/TadpoleForDBTools#1152]
안녕하세요. 먼저 좋은 툴 감사합니다. 
기능 개선 이슈 올립니다~ 
데이터베이스 등록 후 쿼리 전체 이동 기능 추가가 있었으면 합니다. 

ex) mysql 등록 후 쿼리 4개 작성, api hub기능의 api도 4개 추가  
--> maria db 등록 후 위에 mysql 에서 작성한 쿼리 4개를 똑같이 maria db로 전체 복사하거나 이동 기능 추가

**Comment by hangum** [comment]
안녕하세요. 
테드폴허브 조현종입니다.  
개발운영 쓸때 쿼리 이동하면 편하겠네요.  

기능 추가할수 있도록 하겠습니다. 
감사합니다. 

나의 iPhone에서 보냄

2019. 2. 12. 오전 9:46, hkjang <notifications@github.com> 작성:

**Comment by jeongjaehong** [comment]
리소스 관리자에서 선택해서 export하고 대상 DB로 import하거나 바로 대상 DB를 선택하고 transport 할 수 있으면 편리하겠네요~

근데 굳이 이동시키지 않고 공용 리소스로 관리할 수 있어도 좋겠다는 생각도 듭니다.

가령 오라클의 lock 세션 찾아보는 쿼리나 데이터 파일사이즈를 확인하다거나 환경설정값을 확인하는 쿼리등은 DB하고 상관없이 오라클 디비라면 어디든 쓸 수 있는 쿼리라서 유용할것 같습니다.

DBMS종류만 설정해서 공류 리소스로 관리할 수 있어도 좋을듯 합니다.

일단 올챙이가 개선되기 전까지는...
리소스 관리에서 해당 쿼리 리소스를 조회 후에 더블클릭하면 등록했던 데이터 베이스 쿼리 에디터로 로딩이 됩니다.  이때 위쪽의 데이터 베이스 연결을 다른 DB로 전환해서 쿼리를 실행할 수도 있는데 이렇게 사용하셔도 무방할것 같습니다.

1. 리소스 조회.
![image](https://user-images.githubusercontent.com/859932/52611841-c3842680-2eca-11e9-886c-165946c1844e.png)

2. 리소스 로딩 후 그룹내의 다른 데이터 베이스로 연결 변경.
![image](https://user-images.githubusercontent.com/859932/52611931-0e05a300-2ecb-11e9-9e27-1056d5f27607.png)

**Comment by hkjang** [comment]
코멘트 감사합니다. 
Tadpole meta db 상에는 select insert 일 것 같아서 아마도 테드폴측에서 금방? 구현해 주실수 있지 않을까 생각 됩니다. ^^

**Comment by hangum** [comment]
@hkjang  아~
@jeongjaehong  형 이거좀 맡아줘요.

**Comment by jeongjaehong** [comment]
아래와 첨부이미지와 같이 구현하면 될까?
리소스 넘길때 다른 고려사항이 필요할까요?
리소스 관리화면에서 리소스를 삭제하는 기능은 없던데 삭제 기능은 필요 없을까요?
리소스를 삭제할때 현재 변경이력도 관리하고 있긴한데... 이력이 있으면 삭제를 못하게 하는게 맞는건지? 아니면 변경이력도 같이 삭제를 하는게 좋은건지 확신이 없습니다. 어떤게 더 유용할 까요?

검토 부탁 드려요~ @hangum , @hkjang 
![image](https://user-images.githubusercontent.com/859932/53062369-f00bf400-3503-11e9-857e-308c390c40f8.png)

**Comment by hkjang** [comment]
@jeongjaehong 삭제도 있으면 좋을 듯 합니다. 근데 삭제를 실수로 할수 있을 듯 해서 삭제여부를 Y, N으로 관리하는게 좋을것도 같습니다. 언제든 살릴수 있게요~ 캡처 화면을 보니 API정보는 전송 안된다는 메시지가 보이는데요~ API도 함께 넘어가면 얼마나 좋을까 생각해 봅니다 ;; 감사합니다.

**Comment by jeongjaehong** [comment]
API의 경우 API 호출을 위한 URL이 있어서...또한 API허브가 함께 설정된 경우에만 유효한 상황이라~ 

어떻게 넘겨야 할지 좀더 고민해 봐야 할것 같습니다.

리소스를 복사하고 나서 복제된 API URL이 새로운 대상 데이터 베이스에서 제대로 작동할지도 알수 없는 상황이라 리소스(쿼리) 내용만 복제하고 API 설정은 복제된 리소스를 리소스 관리자를 통해서 다시 설정하는게 맞는거 아닌가 싶기도 하구요. 

좀 더 고민해 봐야 할것 같습니다.

**Comment by hkjang** [comment]
답변 감사합니다. 
@jeongjaehong 
복사, 이동이라는 기능이 있으면 좋을 것 같구요.. 
복사일때는 위에 말씀주신 부분이 맞을수 있을것 같구~ 
이동일때는 API까지 전부 이동되는게 좋지 않나 생각 해 봅니다~

**Comment by hangum** [comment]
@jeongjaehong  API_URL이랑 유일한 키는 그냥 통으로 넘기고 사용자에게 맡겨야 할것 같긴해요.
메뉴얼에 표시하구요. 안그러면 방법이 없겠다도 싶네요.

**Comment by jeongjaehong** [comment]
@hkjang , @hangum 

복사 & 이동 라는 옵션도 좋을것 같습니다.

API URL은 이동의 경우 그대로 넘기고 복사의 경우에는 기존 URL + yymmdd 형식의정보를 추가해서 중복을 방지해야 할것 같고 사용자가 추가하는 특정문자열을 뒤에 추가하는 방식도 있겠네요~ 

api url의 경우 중복이 되면 안되는 거라서 사용자가 추가한 문자열의 추가에도 불구하고 중복이 발생하면 추가로 yymmdd를 추가 적용하거나 하는 방법을 사용해야 할것 같습니다.

정리하면 아래 그림과 같은 형식이 될것 같습니다. 

좀더 정리해야 할 부분이 있을까요?

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/859932/53531073-7c866a00-3b35-11e9-8da9-3a3fdb95475d.png">
