### ISSUE TITLE
리소스 History  보기 창에서 "수정" 작업시 오류가 발생합니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#1153]
1. 리소스 관리자 열기
2. 리소스 선택 후 도구모음에서 History버튼 클릭.
3. 팝업창에 표시된 sql 수정 후 하단의 "수정" 버튼 클릭.
4. 첨부와 같은 오류 발생.

![image](https://user-images.githubusercontent.com/859932/53061448-08c6da80-3501-11e9-8686-4d40352446a1.png)

**Comment by hangum** [comment]
확인해보겟습니다.

**Comment by hangum** [comment]
수정되었습니다.
