### ISSUE TITLE
다운로드 관련 문의입니다.

### ISSUE THREAD

**Issue by LoveJuhee** [hangum/TadpoleForDBTools#1156]
v1.8.5 이후의 설치 파일은 sourceforge 에 없는데 엔터프라이즈 버전만 제공이 되는건가요?

**Comment by hangum** [comment]
@LoveJuhee  오픈소스는 마지막 버전이 v1.8.4r6 입니다.
마지막 릴리즈 후에 새로운 버전릴리즈를 아직 못하고 있는데, 차주에는 현재 코드를 기준으로 릴리즈 할 수 있도록 하겠습니다.     

엔터프라이즈 버전은 v2.1.1 까지 릴리즈 했습니다. 
자세한 내용은 릴리즈 노트를 참조해 주십시오.
https://tadpoledbhub.atlassian.net/wiki/spaces/TADPOLE/pages/586088472/v2.1.1
