### ISSUE TITLE
개발자 가이드 관련해서 질문을 드립니다.

### ISSUE THREAD

**Issue by CyanRYi** [hangum/TadpoleForDBTools#1158]
아래와 같은 환경에서 개발자 가이드를 따라서 개발 환경 구성을 시도하고 있습니다.
이 과정에서 몇몇 파일명을 찾기 어려워 이슈를 통해 질문을 드립니다.

개발환경 : Java 8, Eclipse 2019-06(4.12.0), 올챙이는 master branch를 보고 있습니다.

1. 가이드 문서의 Target Platform 설정과 관련해서
> 올챙이 타겟 파일은 ${workspace}/targetProject/tadpolea-rap-2.0.0-emf-standalone.target을 입니다. 

* 위 내용에서, 현재 버전 기준으로 ${workspace}/targetProject/AllInOne.target이 이를 대체하고 있는 것인지 확인하고 싶습니다.
---
1-1. 해당 파일을 열어보면 아래와 같은 화면이 뜹니다.
> ![.target](https://i.imgur.com/ROlc20H.png)
오류 메시지를 기준으로 레퍼런스를 아래와 같이 약간 수정하면 일단 오류는 사라집니다만..
이후 단계를 진행해보지 못해 제대로 해결된 것인지를 알 수 없습니다.
> ![.target-fix](https://i.imgur.com/zAZHxoy.png)
---
2. 가이드 문서의 실행과 관련된 부분에서
> com.hangum.tadpole.application.start 프로젝트의 TadpoleDBHub_executer_configuration.launch 를 클릭 하세요. 

* 위 파일이 com.hangum.tadpole.application.start.launcher.TadpoleDBHub_configuration_3.4.0.launch 로 대체된 것이 맞는지 확인하고 싶습니다.
---

호기롭게 덤벼들었다가 머리를 싸매고 있습니다.
아마도 메이저 판올림 관련한 괴리인것 같은데.. 혹여 다른 변경점도 있으면 함께 부탁드립니다 :)

**Comment by hangum** [comment]
네 말씀하신것이 맞습니다. 
코드 리팩토링하는 과정에서 그렇게 된듯합니다. 
수고하셨어요.
