### ISSUE TITLE
모든쿼리 실행시 insert문 구문오류(oracle)

### ISSUE THREAD

**Issue by vine-nam** [hangum/TadpoleForDBTools#1159]
안녕하세요.

`한줄 실행`에서는 문제가 없으나 `모든쿼리 실행`시  insert문에 세미콜론(;)이 포함되어 있으면 `ORA-01756: quoted string not properly terminated` 에러가 발생합니다.
해당 쿼리문: INSERT INTO table VALUES ('1','1',**'1;2;3;4'**);

데이터가 많아 하나씩 실행하기에는 무리가 있어 해당 구문은 다른 문자로 대처한 후 update문을 사용하여 해결하였습니다.

`모든쿼리 실행시` sql문에 세미콜론을 사용할 수 있게 되었으면 합니다.

감사합니다.

**Comment by hangum** [comment]
엔터프라이즈 버전은 v2.1.3 r6에서 수정되었는데, 오픈소스 버전도 수정할 수 있도록 하겠습니다.
엔터사용자이시면 메일이나 코멘트 주십시오.

**Comment by hangum** [comment]
아 쿼리를 보니 위의 케이스는 다음과 같이 하시면 되겠습니다. 

실행하려는 쿼리를 블럭으로 지정하세요.  그리고  쿼리를 실행하세요.(모든쿼리실행말고요) 
쿼리블럭을 실행하고 쿼리실행을 누르면 쿼리가 한개로 인식합니다.

![image](https://user-images.githubusercontent.com/1335915/75818781-dbcc2980-5ddc-11ea-9d62-1357750701a8.png)
