### ISSUE TITLE
티베로 이용 문의 드립니다.

### ISSUE THREAD

**Issue by ljy013** [hangum/TadpoleForDBTools#1160]
PostgreSQL, MySQL, MariaDB, Oracle, Tibero 를 모두 사용 중이라 하나의 SQL로 사용하기에 딱일걸로 생각되어 기능 확인 중에 문의드립니다.
2.0 / 1.8.5 버전에서는 티베로를 선택할 수 없던데 더이상 지원하지 않는건가요?
(1.7.4버전으로 확인했을 때는 티베로가 있긴한데, MySQL 8.0 버전이 안되더라구요.)
메뉴얼이나 릴리즈노트는 아무리 찾아봐도 해당 내용이 없어 이슈로 문의드립니다.

**Comment by hangum** [comment]
@ljy013  

안녕하세요. 
- 티베로는 기본 데이터베이스로 추가할 수 있도록 하겠습니다. 
- mysql 8.0 드라이버와 인자 문제로 그런데 개선할 수 있도록 하겠습니다. 

이번주 바쁜것좀 지나면 릴리즈 하겠습니다.

**Comment by hangum** [comment]
- 2.0 버전에서는 사용가능합니다. 
- 티베로는 수정했습니다.   테스트환경만들기가 너무 어렵네요.

**Comment by hangum** [comment]
https://sourceforge.net/projects/tadpoledbhub/files/2.0.x/2.0.0_r3  이걸 사용해 보세요
