### ISSUE TITLE
Elasticsearch 연결이 안됩니다. 

### ISSUE THREAD

**Issue by ezsimple** [hangum/TadpoleForDBTools#1161]
현재 v2.0.0 Build (A2)-2019.05.15 ROOT.war + tomcat8 을 사용하고 있습니다.

데이터베이스 등록 : Elasticsearch 에 URL : http://localhost:9200 을 입력하고 

연결테스트를 하면 java.lang.NullPointerException 로 나옵니다. 

어떻게 하면 연결할 수 있을까요?

언제나 감사합니다. 개발자님 ^^

덧) 2.1.X 버전의 war 가 언제쯤 릴리즈 되는지요?

**Comment by hangum** [comment]
@ezsimple  엘라스틱 커넥터는 엔터프라이즈 버전에서도 아직 알파탄계로 배포하고 있습니다.
2.1은 요즘 너무 바빠서요.    ㅠㅠ

**Comment by hangum** [comment]
오픈소스 버전에서는 엘라시틱 커넥터 공개일정은 아직 정해져 있지 않습니다.

**Comment by ezsimple** [comment]
오픈소스 버전에서는 아직 사용할 수 없군요. 아쉽습니다. 

답변 감사합니다. hangum님

**Comment by hangum** [comment]
@ezsimple  엔터프라이즈 버전은 훨씬 더 다양하고 멋진기능이 많이 있습니다. 
감사합니다.
