### ISSUE TITLE
관리자 권한인데 데이터베이스 삭제 메뉴가 안보이네요

### ISSUE THREAD

**Issue by webgori** [hangum/TadpoleForDBTools#1164]
docker container hyunjongcho/tadpoledbhub:latest 설치
버전: 2.0.0

데이터베이스: MSSQL
운영 타입: Development Server
그룹 이름: 기타

기타정보 설정
오토 커밋, 실행쿼리 저장, 테이블 보이기

관리자 권한인데 데이터베이스 삭제 메뉴가 안보이네요.

원인을 알 수 있을까요?

![image](https://user-images.githubusercontent.com/5680005/66185270-d77ad380-e6b9-11e9-9c53-3d47be361220.png)

**Comment by hangum** [comment]
@webgori  개선할 수 있도록 하겠습니다.

**Comment by webgori** [comment]
@hangum 
궁금해서 여쭤보는건데요, 해당 기능이 MYSQL은 있는데 MSSQL 에만 빠져있는 기능인가요?

**Comment by hangum** [comment]
@webgori  기본 디비에 빠져있는데 그것도 추가해 놓을게요. 

엔터 버전과 소스가 분리되면서 관리가 안되고 있네요. 좀더 신경쓰도록 하겠습니다.

**Comment by hangum** [comment]
![image](https://user-images.githubusercontent.com/1335915/75816110-ef28c600-5dd7-11ea-82dd-2a377c186d50.png)

2.0.0 a4 버전에서 수정되었습니다.
