### ISSUE TITLE
MAC 바이너리 실행 시 멈춤현상

### ISSUE THREAD

**Issue by actict** [hangum/TadpoleForDBTools#1165]
안녕하세요.

MAC 바이너리 실행 시 팝업화면 뜬 채로 다음 화면으로 못 넘어가고 멈춰있습니다.

조치 방법이 있을가요?

확인 부탁 드립니다.

감사합니다.

**Comment by hangum** [comment]
일단은 저의 환경은 실행이 잘 되고있습니다.
![image](https://user-images.githubusercontent.com/1335915/75711147-35632400-5d09-11ea-9d9e-383215672f55.png)

혹시 안되시면 설치 디렉토리까지 가셔서  (/macosx.cocoa.x86_64/macosx.cocoa.x86_64/MacOS/) 으로 이동하셔서  ./tadpole-standalone 으로 실행하십시오. 

참고로 최신버전에서는 각 os 로 실행하는 바이너리를 만들고 있지 않습니다.
