### ISSUE TITLE
5000 rows limit

### ISSUE THREAD

**Issue by mkante-mereo** [hangum/TadpoleForDBTools#1168]
Hi, 

I just installed Tadpole v2.0.1 and i see that the maximum of rows returned is 5000.
I was using v1.6.3 and it was possible to remove the limit. 

It is possible to remove the limit in v2.0.1 ?

Thanks.

**Comment by hangum** [comment]
There is no common way yet.

Bringing data from a table with a lot of data at once causes the system to die.
So, it was developed to bring 500~5000 rows each.

If the setting is 500, you can import only 500 cases at first, and when the result screen comes to the end, you can get as much data as 500*4.

May I ask what kind of situation you need?
@mereo-mka

**Comment by mkante-mereo** [comment]
We want to export result with a lot of lines, more than 50 000.

**Comment by hangum** [comment]
@mereo-mka What database do you use?

**Comment by mkante-mereo** [comment]
Oracle and PostgreSQL

**Comment by hangum** [comment]
@mereo-mka Queries will all download down.
Test it out.

**Comment by hangum** [comment]
@mereo-mka  I have a question. 
How many people use it?
Is it used by the company?

There's a commercial version. Do you know that?

**Comment by mkante-mereo** [comment]
Yes it is for a company but just 10 maximum.
How much is the commercial version ?

**Comment by hangum** [comment]
Business email is as below.
Please let me know the country and local company.

hangum@tadpolehub.com

**Comment by hangum** [comment]
@mereo-mka  are you sending email?
