### ISSUE TITLE
Oracle 사용 시 오류(literal does not match format string) 문의

### ISSUE THREAD

**Issue by sslee-begin** [hangum/TadpoleForDBTools#1175]
안녕하세요,

TadpoleForDBTools을 '/db' 라는 path에 설치를 하고 다른 path에는 다른 application이 동작하고 있습니다.
하나의 톰켓에 두개의 application이 있는 구조입니다.
두 application 모두 동작은 잘 하고 있는 것으로 보입니다.
DB는 Oracle을 사용하고 있는데 TadpoleForDBTools에서 데이터 조회 시 to_date 함수를 데이터 포맷 없이 사용할 경우
'literal does not match format string' 오류가 발생합니다.
다른 application에서 해당 SQL문을 사용하는 페이지를 호출할 때에도 오류가 발생합니다.
그런데 '/db' path 를 삭제한 후 다른 application만 동작할 경우 동일한 페이지를 호출하면 그런 오류가 발생하지 않습니다.
어떤 이유로 이런 현상이 발생하는 걸까요?
드라이버 문제일까요? 아니면 관련 설정이 있는 건가요?

**Comment by hangum** [comment]
안녕하세요. 

아마도 아래의 문제 처럼 보입니다. 
https://m.blog.naver.com/jeemin5/220141590502

감사합니다. 

ps) 오픈소스 테드폴디비허브는 여력이  없어서 많이 방치되고 있는 상태라 죄송합니다.

**Comment by sslee-begin** [comment]
빠른 답변 감사드립니다 ^^

TadpoleForDBTools로 접속해서 Session 정보를 변경한 후 관련 SQL문을 실행하면 오류없이 실행은 됩니다.
그런데 다른 경로에 있는 해당 SQL문을 사용하는 페이지(다른 application입니다)를 호출하면 여전히 오류가 발생합니다.
이상한 점은 TadpoleForDBTools이 설치된 폴더를 삭제하고 서버를 재 시작한 후 해당 페이지를 호출하면 오류가 없다는 거죠..
동일한 페이지를 호출하는데 TadpoleForDBTools이 설치된 상태와 설치되지 않은 상태가 다른 결과가 나와서요.
TadpoleForDBTools이 WAS를 다른 application과 같이 사용할 수는 없는 건가요?
