### ISSUE TITLE
[기능추가]

### ISSUE THREAD

**Issue by nobelbill** [hangum/TadpoleForDBTools#240]
아까 이야기하던거 그냥 좀 검색해서 적습니다..

지금 세미나 시간인데 듣기싫어서 ^^

http://www.slideshare.net/Couchbase/migrating-from-the-rdbms-to-no-sql-webinar-26-july-2012

전체적인 아젠다는 위의 글과 유사한듯

일반적인 마이그레이션 툴중에 오픈소스는 예전에 말한번했던

talend 라는 툴이 있는데

http://www.talend.com/

엔터프라이즈 기능에는 패러럴 옵션이 들어있어서

마이그레이션 속도를 상당히 올릴수있는 기능이 있습니다~

가격이 한  host 에 2000불 정도 했던거같아

예전에 한번 확인했을때..

뭐 내 생각에는 탈렌드라는 툴 한번 조사한번 해보는것도 좋을듯

이 툴은 

input 데이터를 모든 데이터베이스, 파싱가능한 화일 심지어 네트워크 소켓까지도 

받을수있으며

output 도 가능한 모든 방법으로 만들수가 있음

사용법도 드래그 앤 드랍 방식으로 ..

일단 한번 써보면 감이 올듯

참고하세요!

**Comment by hangum** [comment]
접근제어/마스킹 용도로 기능을 확장해야겠습니다. 
마이그레이션은 아무래도.. --;; 
잘되고 있는 툴에 기능을 맡겨야겠습니다.
