### ISSUE TITLE
등록된 RDBMS들 간에 자료 복제(전송) 기능

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#263]
오라클, 큐브리드, 포스트리드 등..상호가 전송 기능.

**Comment by hangum** [comment]
mongo to rdb
rdb to rdb 기능도 추가해야겠어요.

**Comment by WaveGrasper** [comment]
이런 경우도 포함될까요?
현재 __운영__ 데이터베이스에 대해 __개발__과 __테스트__ 데이터베이스를 사용하고 있습니다.
스키마 변경이나 데이터 차이로 인해 주기적으로 운영의 백업 데이터로 개발과 테스트를 복원하고 있습니다. 버튼 하나로 운영 측의 데이터로 동기화 시킬 수 있다면 무~척 편리하겠습니다.
너무 게으른 걸까요?

**Comment by hangum** [comment]
지금 만들어 가고 있는 기능이에요. 
소스 오픈과 기능 오픈을 어느 정도까지 할지는 정해져 있지 않구요. 
아마도 일부 기능제약을 두지 싶습니다. 

엔진디비 1.6.0 버전 때와 1.6.6 현재 버전의 스키마 변경 부분을 찍어 놓은 것입니다. 
![2015-11-17 10 26 02](https://cloud.githubusercontent.com/assets/1335915/11203228/3656633e-8d35-11e5-8118-48caa1929e45.png)

**Comment by hangum** [comment]
이 기능도 올챙이 장기 기능은 아닌듯합니다. 
디비의 복제는 단순 데이터 복제뿐만 아니라, 프로시저 평션등 복잡한 문제가 산제되어 있어 수작업이 되지 않으면 안되는 기능 같습니다.  

방향성은 웹베이스 기반의 접근제어/마스킹/기본 툴깃이 되어야겠습니다.
