### ISSUE TITLE
조회된 결과를 DML문으로 저장하는 기능.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#264]
조회된 결과 데이터를 INSERT문이나 UPDATE문장, 오라클의 MERGE문장으로 변환하여 저장하는 기능.

**Comment by hangum** [comment]
@billygoo  이거 해보시겠어요.

**Comment by hangum** [comment]
부자형님이 얼마전에 다운로드에 탭으로 추가했습니다.
