### ISSUE TITLE
PayPal 이외 기부 방법

### ISSUE THREAD

**Issue by babokim** [hangum/TadpoleForDBTools#317]
PayPal 이외의 기부 방법은 없나요?
제가 온라인에 카드 번호 저장하는 서비스를 별로 좋아하지 않아서요. ㅋ

**Comment by Mabin-J** [comment]
opencollective.com
이용하는 오픈소스들도 있는 것 같은데요.
이것도 고려해보시면 어떨까요? ^^;;

https://github.com/gureum/gureum/issues/535
이것 보다가 생각나서 적어봅니다. ^^;

**Comment by hangum** [comment]
@Mabin-J 관심보여주셔서 감사해요.   잘 계시지요?
사실 오픈소스 올챙이에 기부해 주시는 것은 법인을 만든 이후에는 모두(?) 다른곳 혹은 다른분께 기부하고 있어요. 
정규적으로 회사매출의 얼마 정도를 다른곳에 기부 하고 있는 상태입니다. 

혹은  제가 2013년때처럼의 상황과 결과물이있는 상태의 다른 오픈소스 프로젝트가 있다면 많지는 않겠지만 기부하려고도 해요.  그런 프로젝트가 있다면 저에게 알려주세요.  만나보고 싶어요. 

현재는, 오픈소스 올챙이는 소스와 아이디어 방향성 기부를 받고 싶습니다. 
예전처럼 사용기나, 버그 코드 커밋해주세요.
