### ISSUE TITLE
질문. 혹시 ldap 지원 예정인가요?

### ISSUE THREAD

**Issue by stariki** [hangum/TadpoleForDBTools#326]
혹시 ldap 지원 예정인가요? 
아니면, 넣어주실 수 있는지요?

만약 넣어주신다면, 제가 찜해도 될까요?

내년 상반기 목표로 천천히....(간단한 조회만)
올챙이 소스 한번도 본 적이 없고
git모르고 
회사일도 많고.... ^^;

**Comment by hangum** [comment]
테스트 코드는 완료 되었습니다.

**Comment by stariki** [comment]
짝짝짝. 
하시는 일 잘 되세요...^^

**Comment by hangum** [comment]
@stariki  감사합니다.  엔터프라이즈 버전에 적용될 예정입니다.

**Comment by hangum** [comment]
오픈소스버전에서도 지원하도록 기능을 추가했습니다.
