### ISSUE TITLE
 dbms 별  키워드(예약어) 지원 강화.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#399]
dbms 별로 예약어를 등록하고 관리 하도록 해서 에디터 창에서 입력시 해당 키워드는 색상을 강조해서 표시하고 자동으로 대문자로 표시하는등의 강조 처리가 가능하면 사용자 입력 오류를 최소화 할 수 있을듯 합니다.

**Comment by hangum** [comment]
1.7.0에는 전면 수정했습니다 ..
