### ISSUE TITLE
REST API 정의

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#476]
REST API 추가
- 등록된 그룹이 API를 통해 엔진에 사용자, 디비를 추가 삭제 등을 요청 할 수 있도록 합니다. 
-- 나중에는 쿼리 요청, 히스토리 요청까지 할 수 있도록 시스템을 확장하는 것이 목표입니다.

-- REST API 는
--- 특정 IP만 접속 할 수 있도록 합니다.

- 권한 제어
-- 계정 생성
-- 계정 블럭
-- 계정 삭제
-- 계정 정보 요청

- 디비 
-- 디비 생성
-- 디비 삭제
-- 디비 정보 요청

**Comment by hangum** [comment]
현재는 쿼리를 지정하고 사용자가 요청하도록으로 수정되었습니다. 
더 좋은 아이디어가 나올때까지...

**Comment by jeongjaehong** [comment]
사용자 등록을 api를 통해서 자동화 할 수 있으면 관련 시스템(사내 erp, 그룹웨어)등과 연동할때 편리할 듯 합니다.
그리고 등록된 API USER 레벨의 사용자를 그룹화(조직 내지는 사용자 권한그룹 형태의...)화며 표시할 수 있으면 좋을듯 합니다.
