### ISSUE TITLE
MSSQL 의 view DDL 로 생성되는 쿼리

### ISSUE THREAD

**Issue by snwflower** [hangum/TadpoleForDBTools#482]
MSSQL 의 view DDL 로 생성되는 쿼리의
int,datetime,text 타입은 length를 입력받지않네여.

**Comment by hangum** [comment]
@jeongjaehong  이거 어떻게 진행 되가요?

**Comment by jeongjaehong** [comment]
int, datetime, text 타입의 컬럼 정보에 (xx), (xx, x) 형태로 DDL이 생성되네요..ㅡㅡ;

scale, prec정보를 지정할 수 없는 데이터 타입을 확인해서 빼줘야 할듯 합니다. ^^;

**Comment by jeongjaehong** [comment]
http://www.w3schools.com/sql/sql_datatypes.asp 의 정보를 참조하여 아래 데이터 타입에 대해서는 데이터 타입명만 사용하여 DDL문을 사용하도록 변경하였습니다.

/*decimal*/106,/*numeric*/108,/*float*/62,/*varbinary*/165,/*binary*/173,/*nvarchar*/231,/*varchar*/167,/*char*/175
