### ISSUE TITLE
기본 셈플 데이터베이스 생성.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#491]
TadpoleDB.com에 사용자 계정을 생성할때 

SQLite DB에 올챙이 엔진디비 모델을 기본으로 생성해주고 

리소드에 ERD도 함께 생성해 주면 어떨까요?

**Comment by hangum** [comment]
@jeongjaehong  요즘 바쁘시지 않으면 이것이나 sql 초기 템플릿 작업을 해보시겠어요?

**Comment by hangum** [comment]
이건 제가 했어요. ㅜㅜ
