### ISSUE TITLE
모델링은 데이터베이스 커넥션 없이 불가능한 것인가요?

### ISSUE THREAD

**Issue by Guhnguk** [hangum/TadpoleForDBTools#528]
제목 그대로 입니다. 커넥션 없이 DB 모델링을 하고자 합니다. 제가 문서를 못 찾을 수도 있겠지만, 커넥션 없이 DB 모델링이 가능했으면 좋겠습니다.

**Comment by hangum** [comment]
모델링 툴이 아니라 현재는 디비가 반듯이 필요하겠다 싶습니다. 
이것과 별개로 erd에서 테이블을 별로 생성하거나 수정 하는 기능을 개발중에 있습니다. 

모니터링 특화된 툴이 나올수 있었으면 좋겠네요. 
당분간 개선될 여지가 없을 것으로 생각되어서 이슈를 종료 하겠습니다.
