### ISSUE TITLE
tajo 0.8 버전에서 query 실행 후 실행 결과 값이 보지이 않습니다.

### ISSUE THREAD

**Issue by sungyoul** [hangum/TadpoleForDBTools#570]
Mac OS, Tajo 0.8, hadoop 2.3 , tadpole stand alone 에서, DB접속,  create table은 정상적으로 잘되나, select * 을 제외한 쿼리 결과값이 보이지 않습니다.
 
select * from table limit xx 만 실행결과값이 보이고, 다른 쿼리들은 query error message는 없고, 결과값이 리턴되지 않습니다. tajo cli 에서 직접 테스트 했을때는 모두 정상 처리 되었습니다.
추가적으로 확인해야 될 것들이 있는지요?

OK :  SELECT * from tour limit 5;
NOK: SELECT count(*) FROM tour ; SELECT lt from limit 5

**Comment by hangum** [comment]
우선은 실행하시는 쿼리가 오랫동안 실행해야 결과가 나오는 지요? 
오랫동안 실행하는 쿼리이면, 올챙이가 쿼리를 중지했을 수 있습니다.
Preference -> RDB -> Query timeout(sec) 의 초를 살펴 보셔서 그것보다 오래 걸리면 쿼리를 자동으로 중지합니다. 

![_2015-01-11_ _6_57_22](https://cloud.githubusercontent.com/assets/1335915/5694909/cb55b04a-99c3-11e4-86b8-a31f80ed5214.png)

감사합니다.

**Comment by sungyoul** [comment]
네 빠른 답변 감사 드립니다. 쿼리는 10초 미만의 단순 쿼리 입니다. 시간문제는 아닌듯 보입니다.

**Comment by hangum** [comment]
@sungyoul  아 그래요. 그럼 확인해 보겠습니다.  노트북을 포멧해서 개발환경을 구축해야하는데, 하는데로 확인해 보겠습니다.

**Comment by hangum** [comment]
@sungyoul  최신버전업을 하니 말하신 오류가 수정되었습니다.
감사합니다.
