### ISSUE TITLE
tajo 0.9.x 버전 사용시, query error

### ISSUE THREAD

**Issue by sungyoul** [hangum/TadpoleForDBTools#571]
현재 tajo 0.9.x 버전으로 테스트 시, DB접속은 정상적으로 되나, 쿼리 실행시 다음과 같은 error message 가 발생합니다. 

java.sql.SQLFeatureNotSupportedException: org.apache.tajo.rpc.TajoServiceException: Message missing required fields: isJson

**Comment by hangum** [comment]
확인해 보겠습니다.

**Comment by hangum** [comment]
@sungyoul  올챙이에서 사용하는 tajo driver를 최신으로 수정하니 정상 동작 합니다.
감사합니다.  hive까지 테스트해서 마이너 버전업을 하도록 하겠습니다. 

https://drive.google.com/folderview?id=0B3YIS2ZszMgpVW0yY1l2QzBfckk&usp=sharing

**Comment by sungyoul** [comment]
감사합니다. 공유해 주신 폴더에서 mac standalone 버전 다운 받아 테스트 해보니, 
쿼리를 보낼때 error message없이 success 처리 되나, 쿼리 결과값이 보이지 않습니다.
 select * from limit xx 문만 처리 되고, 다른 쿼리들은 결과값이 보여지지 않는 현상은 존재하는 것 같습니다.  
정상 동작 하신다고 하니, 혹시 제가 설정을 잘못 한게 있는지 모르겠습니다. 
테스트 환경은 아래와 같습니다. 
서버 환경: hadoop 2.5.2, tajo apache 0.9, java 1.7.0_45, CentOS
client 환경: Mac, java.1.7.0_71, 올챙이 1.43  release 1.11

**Comment by hangum** [comment]
아네.
저는 hadoop 2.5.1이고 서버와 클라이언트 환경이 거의 같으네요. (2.5.2 도 잘 되네요)
끙~

tajo는 어제자 최신을 git에서 받아서 컴파일해서 사용했습니다.
어떻게 해야 할지 저도감을 못 잡겠네요.

**Comment by sungyoul** [comment]
안녕하세요. tajo를 저도 최신 버전  0.10 git 에서 받아 빌드해서 해보니 잘됩니다.
감사합니다. 
0.9.1 버전이상에서 변경된 부분이 많아 그런것 같습니다..

**Comment by hangum** [comment]
@sungyoul 네. 해결되어서 다행이네요.  좋은 하루 되십시오.

**Comment by hangum** [comment]
이제 1.4.3 버전을 릴리즈 했습니다. 
좋은하루 되십시오. 

https://tadpoledbhub.atlassian.net/wiki/display/TADPOLE/v1.4.3+Release+note
