### ISSUE TITLE
프로시져 실행 시 권한 오류

### ISSUE THREAD

**Issue by ncrash** [hangum/TadpoleForDBTools#576]
1.4.3 버전으로 MySQL 디비 접속 후 프로시져 실행 시 아래와 같은 오류가 발생하네요.

에러 메시지상에는 해당 유저의 권한설정 문제라고 하는데 toad와 같은 클라이언트 툴에서는 프로시저 실행에 전혀 문제 없는 유저인데 에러가 발생하네요

메시지에서 권고하는대로 noAccessToProcedureBodies=true 옵션을 jdbc url에 지정하고 싶은데 1시간정도 살펴봤으나 답을 못찾겠어서 이슈로 등록해 봅니다.

![image](https://cloud.githubusercontent.com/assets/153414/6796483/40d0c85e-d237-11e4-9c48-c35ce4edad92.png)

java.sql.SQLException: User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.

**Comment by hangum** [comment]
@ncrash  안녕하세요.
현재는 엔진에 jdbc 옵션을 줄수가 없는데요. 

다음 버전(2.0)에 반영 될수 있도록 이슈를 만들고 관리 하겠습니다. 
https://github.com/hangum/TadpoleForDBTools/issues/577

감사합니다.

**Comment by ncrash** [comment]
확인 감사합니다!

**Comment by hangum** [comment]
수정되었습니다.
https://github.com/hangum/TadpoleForDBTools/commit/0229432ce3b9fa8353070322291b0fa262ff65e1
