### ISSUE TITLE
Tadpole DB support SSL

### ISSUE THREAD

**Issue by syafiqmazli-mcpayment** [hangum/TadpoleForDBTools#591]
Hi,

I just want to check either Tadpole could configure with SSL?

Regards,
Syafiq

**Comment by hangum** [comment]
we planned next version.

**Comment by hangum** [comment]
@syafiqmazli-mcpayment  What kind of DB the use?

**Comment by syafiqmazli-mcpayment** [comment]
Microsoft SQL & MySQL

**Comment by hangum** [comment]
v1.7.0 now support ssl.

https://translate.google.co.kr/translate?sl=ko&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Ftadpoledbhub.atlassian.net%2Fwiki%2Fpages%2Fviewpage.action%3FpageId%3D32702468&edit-text=&act=url
