### ISSUE TITLE
Choose an other schema

### ISSUE THREAD

**Issue by ENison** [hangum/TadpoleForDBTools#592]
Hi,
I couldn't find if there is a way to show an other schema than the default one in the Object Explorer. Is it currently possible?
Thanks.

Regards,
Emilie

**Comment by hangum** [comment]
I wonder what kind of object?
What is DB type you use?

**Comment by ENison** [comment]
I use PostgreSQL databases and I can only see the tables, views... of the public schema.

**Comment by hangum** [comment]
Are you connected database?  
Do not connect db, can not see db object. 
if you connect to db, you attach log file.

![2015-06-05 16 52 37](https://cloud.githubusercontent.com/assets/1335915/8001731/64bbed52-0ba3-11e5-8f68-0d59006ab00b.png)

**Comment by ENison** [comment]
Yes, my database are connected. I can see the db objects of the default schema but only the one.

**Comment by hangum** [comment]
yes, only one. you add instance.

**Comment by ENison** [comment]
Okay, thanks you very much for your rapid help and for tadpole.
It's a very great tool.

**Comment by hangum** [comment]
@ENison  thanks a lot

**Comment by ENison** [comment]
I check the code and in reality it's currently impossible to change the schema without changing the code because in the code the schema is set on public (WHERE a.table_schema = 'public').
So I have my response, thanks.

**Comment by hangum** [comment]
@ENison  see 
https://github.com/hangum/TadpoleForDBTools/blob/master/com.hangum.tadpole.commons.sql/src/com/hangum/tadpole/engine/query/PostgreSQL.xml

**Comment by ENison** [comment]
I agree it's the code to change to choose the schema.
Does the possibility of choosing the schema without changing the code will be add in a next version? 
I'm sorry, I understand it's annoying that I insist but my company is interested in about using tadpole for a significant use so I need to be sure that tadpole will answer or not to our needs.

**Comment by hangum** [comment]
We need a supporter.
If you pay the full cost possible. 

Contact us -> adi.tadpole@gmail.com
