### ISSUE TITLE
엔진디비 및 초기 연결 방법에 대해

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#595]
암호화된 연결문자열 생성 유틸을 제공하거나 설치가이드에 관련 안내자료가 있어야 할것 같습니다.

그리고 최초 설치시에 엔진디비를 직접 생성해 주어야 하는데 관련 SQL파일 사용에 대한 안내 및 설치 가이드를 최신으로 갱신해야 할것 같습니다.

실행시 tadpole_user테이블이 존재하지 않는다는 오류 메시지 보다는 어느 위치의 어떤파일을 다운받아 엔진디비를 초기화 하고 tadpole을 다시 시작하라는 안내문구가 나오면 더 좋을것 같습니다.

또는 시작옵션을 이용하여 초기화에 이용할 파일을 지정할 수 있도록 하고 정상적으로 연결이 되고 나면 해당 파일을 읽어 들여 지정된 테이블 생성후 기본 코드 데이터를 생성해 주는건 어떨까요?

**Comment by hangum** [comment]
전체 적인 메뉴얼 작업은 빠른 시일 내에 해야겠습니다. 
코드 관련 작업은 1.6.2 릴리즈에 맞게 할수 있도록 하겠습니다.
