### ISSUE TITLE
올챙이 최초 실행시 계정등록 중에 암호가 비어있다는 메시지에 대해서...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#596]
아래와 같이 war를 이용하여 초기 접속시에 계정을 생성하는 화면에서 패스워드 길이가 규칙에 맞지 않을 경우 메시지가 자릿수가 짧다거나 규칙에 위배된다는 메시지 대신 입력되지 않았다는 안내메시지가 표시됩니다.

규칙에 맞지 않습니다. 영문 대소문자와 특수문자, 숫자를 포함한 8자리 이상으로 입력하십시오. 

처럼 안내되면 좋겠습니다. 

![capture](https://cloud.githubusercontent.com/assets/859932/8226052/29c4612e-15d6-11e5-8755-f76d90d96a61.png)

**Comment by hangum** [comment]
@jeongjaehong  해줘요

**Comment by hangum** [comment]
@billygoo  이거 해보시죠.

**Comment by billygoo** [comment]
![image](https://cloud.githubusercontent.com/assets/2518075/8548666/1b8dae46-2501-11e5-80d1-4e68b719a74f.png)

![image](https://cloud.githubusercontent.com/assets/2518075/8548673/2114ae0a-2501-11e5-8a3f-8e6fdd8d5c06.png)

문구 수정했습니다. 그리고 룰이 적용 되어 있지 않아서 신규로 룰을 추가했습니다. 
특수 기호는 정해지지 않아서 이를 제외한 영문 대소문자, 그리고 숫자를 각각 1자 이상 그리고 8자 이상으로 변경하였습니다. 

오랜만에 push를 해서 직접 브랜치로 넣는 실수를 했어요. ㅡ.ㅡ;;;
한번 이상이 있나 확인해 주세요. ^^;;; 

변경된 내역은 다음과 같습니다. 

1. 레이아웃 수정 : 레이블 왼쪽으로 정렬, 하단 테스트 버튼 위치 및 사이즈 수정
2. 레이블명 중에 오타 수정
3. Password 입력 룰 적용 
4. Password 검증 실패시 메시지 변경

**Comment by hangum** [comment]
수고하셨습니다. 
레이블의 텍스트를 지금까지는 왼쪽 정렬 되도록 수정했는데, 오른쪽 정렬이 보기가 더 좋아 보이네요. 
앞으로는 오른쪽 정렬 되도록 코드를 수정해야겠어요. 

@billygoo  @jeongjaehong 

지금 다른 코드를 수정중이라 테스트를 못하고 있는데 수정이 완료되면 테스트 해볼게요.
