### ISSUE TITLE
UI를 통해서 조회된 자료는 파일로 저장할 수 있도록 하면 좋겠습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#598]
UI를 통해서 조회된 자료는 파일로 저장할 수 있도록 하면 좋겠습니다.

UI를 통해서 조회할 경우에는 Result Set에는 일부자료만( Top 100 Row 형태로...) 표시하거나 "전체보기" 또는 "미리보기100건" 형태로 만 조회하고 전체 자료는 파일로 다운로드 받도록 하는것도 좋을것 같습니다.

![capture 2](https://cloud.githubusercontent.com/assets/859932/8229445/c6c0b2aa-15f1-11e5-9a8d-f5457d9ebae6.png)

**Comment by hangum** [comment]
enhancement ui
![2015-06-19 14 46 02](https://cloud.githubusercontent.com/assets/1335915/8247835/ec044130-1691-11e5-9f30-5b3a676f60d7.png)
