### ISSUE TITLE
리소스 쿼리에 한글이 포함될 경우 한글이 깨져서 저장됩니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#599]
server.xml에는 아래와 같이 정의해 주었습니다.
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" 
               URIEncoding="UTF-8"
               />

리소스에 한글이 포함된 쿼리를 저장할 경우 첨부와 같이 ?????? 형태로 깨져서 저장이 됩니다.

이런 이유때문인지 API로 해당 리소스를 호출하면 에러가 발생합니다.

추가로 리소스 메니져에서 리소스를 삭제할 수 없습니다. (삭제기능이 없는것인지 권한문제 인지 알수 없음)
데이터 베이스 목록에서 표시되는 리소스 목록에서는 삭제 가능함.
리소스 삭제 후 동일한 이름으로 다시 리소스를 등록하려고 하면 이미 존재하는 리소스라고 저장이 안됨.
(리소스 명을 pk로 사용하고 있는데 실제 삭제가 이루어지는게 아니라 삭제 마킹만 하고 화면에서 숨기는것으로 판단되며 이럴경우는 내부적으로 일련번호를 생성하여 pk로 사용해야 할것같음)

그래야 삭제후에 사용자가 동일한 이름으로 리소스를 등록하고자 할때 에러가 발생하지 않을것 같음...

![capture 3](https://cloud.githubusercontent.com/assets/859932/8229613/6f2287d8-15f3-11e5-9b69-0c9a728b84b5.png)

**Comment by jeongjaehong** [comment]
한글이 깨지는 문제는 제가 테스트 하던 mysql(엔진디비)의 설정이 잘못되어 발생하는 문제인듯 합니다. ㅠㅠ

**Comment by jeongjaehong** [comment]
맥에 mySQL설치시에 latin1이 기본값으로 설치가 되어서 리소스에 한글이 깨져서 저장되었던 거네요..ㅡㅡ;
일단 테이블 몽창 지우고..문자설정 기본값을 UTF-8로 변경하고 엔진디비(tadpole20)을 다시 생성하고...

조회는 되는데..결과값이 깨지는건 어떻게 해야할까요??? ^^;;
 
![capture 4](https://cloud.githubusercontent.com/assets/859932/8230691/947fee30-15fd-11e5-9d08-9c278694c861.png)

**Comment by hangum** [comment]
헤더에 content_type을 넣어서 수정하였습니다.
