### ISSUE TITLE
API호출을 위한 URL정보가 실제 호출가능한 주소와 유사하지 않습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#600]
실제 호출가능한 주소는 http://127.0.0.1:8080/tadpoleapi/rest/base?serviceID=3d15cc44-0a5f-4d43-80de-a97bb984df46&1= 이지만 리소스 메니져에서 조회했을때 표시되는 주소는 http://yoururl.com?serviceID=3d15cc44-0a5f-4d43-80de-a97bb984df46&1=FirstParameter&2=SecondParameter 처럼 표시가 되고 있습니다.

http://127.0.0.1:8080/tadpoleapi/rest/base?serviceID=3d15cc44-0a5f-4d43-80de-a97bb984df46&1=FirstParameter[&2=...] 형태로  표시해주는게 더 사용하기 편리할듯 합니다. 

추가적으로 tadpole rest api서비스를 사용할 경우 host url을 환경설정에 등록하면 그 내용을 사용해서 url을 만들어 주면 더 좋을것 같습니다. 

![capture 12](https://cloud.githubusercontent.com/assets/859932/8324758/9779a41a-1a8e-11e5-83f4-227888751fe3.png)

**Comment by hangum** [comment]
@jeongjaehong  
아네. 좀 불편하지요. 
API 다이얼로그에서 보여지는 URL 과 api server에서 보여지는 url이 다른데 사용자에게 어떻게 보여주면 좋을까요?

**Comment by jeongjaehong** [comment]
@ Dialog 이용   O 브라우저 이용     [ 미리보기 ] [URL복사]

이렇게 라디오버튼으로 선택하고 미리보기를 이용해서 해당 URL을 직접 오픈해 주거나 또는 클립보드에 URL만 복사해 주는 기능이 있으면
편리할것 같습니다.

**Comment by hangum** [comment]
API 서버는 따로 설치해야 사용할 수 있어서요.
둘다 표시해 주는것도 문제가 있을듯한데요. 

앞에 ?serviceID=3d15cc44-0a5f-4d43-80de-a97bb984df46&1=FirstParameter[&2=...]  만 표시해 줄까요?

**Comment by jeongjaehong** [comment]
Tadpole UI : ......
REST API Server : ...    이렇게 해서 표시해 줘도 좋을듯 합니다.

인수 갯수는 ?를 기준으로  몇개인지  파악해서 만들어 줘도 좋을것 같구요. ^^;
사용자가 바꿔 넣어야 하는 부분은 {server}    {인수값1}   형태로 표시하면 어떨까요?
미리보기나 URL복사기능은 들이는 수고에 비해서 효율적이지 못할까요? ㅋㅋ​

**Comment by hangum** [comment]
@jeongjaehong  네 그게 좋을듯하네요. 그렇게 수정하겠습니다.

**Comment by hangum** [comment]
파라미터 갯수 가져오는 코드는 개선해야하고 다른 코드는 수정했네요. 

![2015-06-25 07 40 23](https://cloud.githubusercontent.com/assets/1335915/8343160/705d4d80-1b0d-11e5-9699-78b7dcaee571.png)
