### ISSUE TITLE
rest api 서버의 오류.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#601]
한글 인수값을 줬을때, 영단어를 인수로 줬을때, 영단어에 공백이 포함되었을때  아래와 같은 오류가 발생했습니다.

테이블은 다음과 같이 생성하였습니다.
CREATE TABLE `apitest` (
  `seq` int(11) NOT NULL AUTO_INCREMENT COMMENT '순번',
  `contents` varchar(20) DEFAULT NULL COMMENT '테스트 데이터 내용',
  `working_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '작업일시',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='API테스트 테이블';

![capture 13](https://cloud.githubusercontent.com/assets/859932/8326153/00a1c0fc-1a9a-11e5-90b6-e2f8adccfd85.png)
![capture 14](https://cloud.githubusercontent.com/assets/859932/8326160/052960bc-1a9a-11e5-9a77-a29afcca8cb7.png)
![capture 15](https://cloud.githubusercontent.com/assets/859932/8326166/096f74c2-1a9a-11e5-8f79-dc7a33c22e8d.png)
![capture 16](https://cloud.githubusercontent.com/assets/859932/8326169/0dab92dc-1a9a-11e5-9db5-a36d77438a0b.png)

**Comment by jeongjaehong** [comment]
에러메시지를 검색해 보니 이런게 나오네요..ㅡㅡ;

https://bugs.mysql.com/bug.php?id=59456

**Comment by hangum** [comment]
그래서 에러를 못잡을까요? 해결 방법은 뭐가 있을가요?

**Comment by jeongjaehong** [comment]
영어가 짧아서...ㅜㅜ 
일단은 테이블을 생성할때 기분문자셋을 latin1으로 해주니 에러는 안나는데... 실제 입력되는 값을 보니 이상하게 깨져서 들어가네... 아마도 파라미터를 UTF-8로 인코딩 해주기 때문인듯...  인코딩 옵션을 파라미터에 선택적으로 입력받게 하고 지정안되면 기본값을 사용하도록 처리해야 할거 같음.

JDBC가 다른게 있는지 버젼이 맞는지 등도 확인해볼 필요가 있어 보이고...ㅡㅡ;

MySQL 설치나 기본문자셋 설정 또는 데이터베이스 생성할때 문자셋 옵션도 제대로 지정한건지 서로 상충하는 부분은 없는지 확인이 필요해 보임...ㅠㅠ

그리고 첫번째 인수가 다른곳에 들어간다는 버그는 뭔가 테스트 중에 발생한 착각이 아닐까 싶음... latin1으로 해서 해보니 지정된 컬럼에 잘 입력이 되고 있음.

![capture 17](https://cloud.githubusercontent.com/assets/859932/8333141/9fddc224-1acc-11e5-82ae-12ccf1dc81be.png)
