### ISSUE TITLE
REST API 서비스 호출할때 파라미터 인코딩을 사용자가 선택할 수 있어야...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#602]
데이터베이스에 저장되는 문자셋이 다양할 것이기 때문에 UTF-8고 고정해 두는건 무리가 있을것 같습니다.

지정하지 않을경우 UTF-8을 사용하더라도 명시적으로 다른 인코딩을 사용할 수도 있도록 해야할것 같습니다.

&ResultType=CSV&encoding=UTF-8

**Comment by hangum** [comment]
디비의 캐릭터 셋이 아니고 http 상에서 받은 컨텐츠의 캐릭터 셋이긴한데, 톰켓 설정도 그렇고 전체를 다시 살펴보긴해야겠네요.
