### ISSUE TITLE
REST API DML 실행 후 결과 까지 한꺼번에 받을 수도 있을까요?

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#604]
1. 프로시져 생성
![1](https://cloud.githubusercontent.com/assets/859932/8612401/d39cd376-270a-11e5-9e66-833df7419510.png)

2. API리소스 등록
![2](https://cloud.githubusercontent.com/assets/859932/8612406/e680022e-270a-11e5-8de3-a4f6a6ff984d.png)

3. API 호출
![3api](https://cloud.githubusercontent.com/assets/859932/8612408/ee31f036-270a-11e5-9376-cb9de95cdc1f.png)

4. MySQL 워크벤치에서 실행한 결과.
![4](https://cloud.githubusercontent.com/assets/859932/8612413/fde429ae-270a-11e5-9359-9e85ecb60a3d.png)

5. 실행 후 대상테이블 조회결과
![5](https://cloud.githubusercontent.com/assets/859932/8612415/0c8eed22-270b-11e5-8a2d-13de2346f7ae.png)

**Comment by hangum** [comment]
프로시저를 실행할수 있도록 기능을 확장해야겠습니다.

**Comment by hangum** [comment]
api 서버 관련 이슈는 https://github.com/hangum/TadpoleDBHub_APIServer 프로젝트를 분리할게요.

**Comment by hangum** [comment]
MySQL로만 먼저 만들어보고 다른 디비까지 확대해가요.

**Comment by hangum** [comment]
mysql의 경우 에디터에서 프로시저 처리는 끝냈습니다. 
아래 처럼 작업하면 되겠습니다.

-- film_in_stock
set @p_film_count = 0;
call sakila.film_in_stock(1, 1, @p_film_count);
select @p_film_count;

-- simpleproc
call simpleproc(333, '1');
call simpleproc(15, '1');

-- function 
select inventory_in_stock(1);
