### ISSUE TITLE
Problem with installation under Eclipse Mars

### ISSUE THREAD

**Issue by extreme-dh** [hangum/TadpoleForDBTools#608]
I've got an error during installation

![bez tytulu](https://cloud.githubusercontent.com/assets/5195296/8926699/091b4bbc-3512-11e5-9198-9957236ac8ef.png)

**Comment by hangum** [comment]
Tadpole is does not work Eclipse.
Only single execute product or Tomcat. 

https://tadpoledbhub.atlassian.net/wiki/display/TADPOLE/Getting+Started
