### ISSUE TITLE
mongodb import 할때 필드가 배열일때 필드값이 없음

### ISSUE THREAD

**Issue by artflower** [hangum/TadpoleForDBTools#612]
tadpole 1.6.1 버전의 기능중에 mongodb import를 사용했습니다.

필드가 배열이면 별도의 파일로 create table 하도록 저장을 하는데요.
배열안에 있는 순서 없이 value 만 저장이 됩니다.

순서값이 같이 저장되면 좋겠습니다.

**Comment by artflower** [comment]
배열에 값이 하나도 없을때는 skip 해서 저장하지 않는것도 좋겠고요.

**Comment by artflower** [comment]
순서대로 insert 됐다면 아래 쿼리로 순서를 줄 수 있기는 합니다.

select _id, order_no, array_value from (
 select array_value, _id, case when @_id=_id then @num:=@num+1 else @num:=0 end as order_no, @_id := _id 
 from table_array
 where _id in ( '_id_value_1', '_id_value_1')
) as t
;

**Comment by hangum** [comment]
@artflower  몽고 소스와 mysql 소스를 보여주시겠어요.
