### ISSUE TITLE
oracle package, procedure 관련 ...

### ISSUE THREAD

**Issue by woosuk288** [hangum/TadpoleForDBTools#613]
1. package에서 procedure 생성 후, 방금 생성한 procedure를 refresh 해도 방금 생성한 procedure 목록이 생성되지 않음. (다른 db를 클릭 후 현재 db 클릭해야 package에 방금 생성한 procedure 목록이 뜨게됨.)

2. 패키지에서 프로시저를 생성하기 위해, 
선언부와 본문(body) 부분을 한번에 실행하면 에러가 뜸.

(---예시---)
CREATE OR REPLACE PACKAGE emp_info AS
  ~~~ 생략 ~~~
END emp_info;
CREATE OR REPLACE PACKAGE BODY emp_info AS
 ~~~ 생략 ~~~
END emp_info;

하지만 선언부부터 실행 후 본문(body) 실행 시 제대로 작동됨...

3.  package에 procedure 생성 후, 해당 프로시져 테스트를 위해 execute package로 값을 넣어 실행(execute) 해봤을 때 실행은 되나 아무런 결과물이 안나옴.
쿼리문으로 실행해도 안나옴.

**Comment by hangum** [comment]
@woosuk288  제보해 주셔서 감사합니다  패치를 빠르게 만들어야겠네요.

**Comment by hangum** [comment]
@woosuk288  
안녕하세요. 
몇가지 질문이 있습니다. 
사용하시는 올챙이 버전과 오라클 버전은 어떻게 되시는 지요?

2번  질문에서 선언부와 본문 부분을
 한번에 실행하면 에러가 뜸은 무슨 의미 인가요?  
아래 그림처럼 아이콘이 프로시저 아이콘이 나오는데도 그러는것인가요?
<img width="836" alt="2015-08-10 1 04 07" src="https://cloud.githubusercontent.com/assets/1335915/9159275/53a0dc58-3f60-11e5-807f-b4ec77e86576.png">

3. 쿼리문을 보여주시겠어요?

**Comment by woosuk288** [comment]
사용하는 올챙이 버전과 오라클 버전 
 
---&gt; oracle 11g, 올챙이버전은 7월13일 최신버전인 1.6.x/1.6.2 인것 같습니다. (어디서 보는지 잘모르겠네요. tadpole-standalone.ini 파일 첨부했습니다.)
 
아래 그림처럼 아이콘이 프로시저 아이콘이 나오는데도 그러는것인가요? 
---&gt;예... 
 
캡쳐 보냅니다. 
 
 
패키지 선언부분과 바디부분을 쓴 후 실행.
 
 
 
 
생성 후 패키지 창. 오류 및 경고가 떠있음.
 
 
 
 
해당 패키지 VIEW DDL로 확인. 입력했던 코드와 VIEW DDL의 결과가 다르게 나옴.
 
 
 
 
 
 
 
그리고 제가 크롬브라우저를 주로 사용하는데, 
올챙이 사용하다보면 어느 순간 오른쪽 마우스 버튼 클릭시 올챙이 메뉴들이 안나오고 브라우저의 오른쪽마우스버튼 메뉴들이 나옵니다.
또한 이러한 현상이 나타나면 복사기능(ctrl+c) 이 되질 않는 현상이 발생하네요... 그래서 잘라내기로 사용한다는...  
 
 
 
-----Original Message-----

**Comment by hangum** [comment]
안녕하세요. 

프로시저 실행에 몇가지 오류가 있어서 수정했습니다.  수정된 사항은 다음과 같습니다. 
- 프로시저 텍스트에 / 문자가있을경우 컴파일 오류가 나는것을 수정했습니다. 
- 프로시저 실행 다이얼로그가 여러번 실행했을 경우 오류가 나는 것을 수정했습니다. 
새롭게 만든 패치는 다음과 같습니다. 
-- https://drive.google.com/folderview?id=0B3YIS2ZszMgpfjVxTVByclNHT2RXSUczaTVRZnFyZ2J6S193TGNJcWZpZHFmc01IcGhpQVU&usp=sharing

- 사용법 동영상을 만들었습니다. (https://youtu.be/07x6n0gOyzs)  보시면 도움이 되실 듯합니다. 
동영상 만들때 사용한 셈플 주소는 
http://www.mkyong.com/oracle/oracle-stored-procedures-hello-world-examples/
http://www.mkyong.com/oracle/oracle-stored-procedure-select-into-example/
입니다. 

- 사용자가 프로시저를 만들때와 view ddl 했을때 프로시저가 틀린것은 리버스 엔지니어링 해서 틀리게 나오는 것입니다. --;; 
어떻게 할 수 있는지는 좀더 고민해 보겠습니다. (아마 안될듯하긴 합니다만, 방법을 아시면 부탁드리겠습니다)

*** 혹시 그래도 동작 하지 않는다면 번거로우시겠지만, 프로시저의 셈플 코드와 관련 스크립트를 부탁드리겠습니다.  ***

**Comment by hangum** [comment]
@woosuk288  어떤문제 인지 좀더 알려주시면 찾아보겠습니다.  현재로는 이슈를 닫겠습니다.
