### ISSUE TITLE
Windows64Bit Standalone버전에서 mongoDB가 추가가 안됩니다.

### ISSUE THREAD

**Issue by namioto** [hangum/TadpoleForDBTools#614]
핑테스트는 해봤는데 핑테스트는 잘 되구요
커넥션 테스트나 add db버튼, add db, close버튼등을 눌러봐도 감감무소식이네요.

그냥 동작이 안하는가 싶어서 mysql 샘플 서버를 추가했더니 잘 추가되구요.
제 서버에 문제가 있나 싶어서 mongodb 샘플 서버를 추가하려고 시도해보았더니 
샘플 서버 또한 마찬가지라서 제 서버 문제는 아닌 것 같습니다.

**Comment by hangum** [comment]
@namioto  문의해 주셔서 감사합니다. 

몽고디비 2.x에서 3.x로 넘어 오면서 많은 수정이 있는 상태인데요.
그래서 궁금한 점이 있습니다. 

몽고디비 버전은 어떻게 되시나요?
연결하실때 디비의 id,password, ssl 통신등을 하시는 지요?
logs/ 디렉토리를 압축해서 보내주시면 도움이 많이 되겠습니다. 

감사합니다.

**Comment by namioto** [comment]
안녕하세요 ^^

몽고디비의 버전은 2.4.10 입니다.

id, pw 다 입력했어요. ^^
제가 접속과정에 문제가 있다고 하더라도 오류메세지 등이 나와야하는데 아무런 반응이 없습니다.

로그파일 첨부하여 보냅니다.
logs/ 디렉토리안에 저 파일 하나 밖에 없더라구요.

2015년 8월 24일 오후 4:25, Cho HyunJong <notifications@github.com>님이 작성:

**Comment by hangum** [comment]
@namioto  확인해 보겠습니다. 감사합니다.

**Comment by hangum** [comment]
감사합니다. 말씀 하신 부분의 코드가 잘못 되어 있어서 그렇네요.  

바이너리 다운로드 받으셔서 테스트 부탁드려요. 원도우 64비트 테스트 시스템이 없어서요. 
https://drive.google.com/file/d/0B3YIS2ZszMgpUUM2NEFqa3VZWEk/view?usp=sharing

**Comment by namioto** [comment]
실행은 잘 됩니다만.. DB 쿼리 조회가 안되네요..
간단하게 조회하려고 조건 넣고 검색했는데 무한 대기가 걸려서 취소도 안되네요.

데이터량이 많아서 그런가 서버에서 테스트 해보았으나 빠르게 잘 나오는 문제 없는 쿼리 였습니다.

그에 대한 로그도 같이 첨부합니다.

2015년 8월 24일 오후 6:53, Cho HyunJong <notifications@github.com>님이 작성:

**Comment by hangum** [comment]
로그 파일이 첨부 되어 있지 않는데요. 확인 부탁드려요.

**Comment by hangum** [comment]
괸찮으시면 tempview 등의 원격 프로그램으로 상황을 보는것도 좋겠습니다. 
괸찮으시면 google talk 하시면 hangum@gmail.com 으로 메시지 주셔도 좋구요. 
페이스 북으로 메시지 주셔도 좋겠습니다. 조현종(hangum@gmail.com) 입니다.

**Comment by namioto** [comment]
저에겐 로그 첨부한 것으로 나오는데 이상하네요.
다시 첨부합니다.

teamview 사용은 회사라 불가능하네요 죄송합니다.

급한건 아니라서요 ^^

2015년 8월 25일 오후 5:37, Cho HyunJong <notifications@github.com>님이 작성:

**Comment by hangum** [comment]
첨부 하신 화면이 보이지 않는데요. 메일로 부탁드려요. 
hangum@gmail.com 감사합니다.
