### ISSUE TITLE
홈페이지 생성

### ISSUE THREAD

**Issue by jungheelee** [hangum/TadpoleForDBTools#615]
깃헙 페이지를 이용하여 올챙이 소개 및 다운로드 링크를 첨부한 사이트를 만들 예정입니다.

**Comment by hangum** [comment]
@jungheelee  기대하겠어요. 
만들고 있는 페이지 url을 알려주세요.

**Comment by jungheelee** [comment]
http://jungheelee.github.io/TadpoleForDBTools/

**Comment by hangum** [comment]
@jungheelee  감사.
현재 홈페이지로 쓰이고 있는 페이지(https://sites.google.com/site/tadpolefordb/)를 대체할 목적이구요. 
아래 페이지 처럼 예상해 봅니다. 
http://monkey-project.com/
http://w3goods.com/wp-content/uploads/knight-demo/index.html

**Comment by jungheelee** [comment]
https://github.com/jungheelee/TadpoleForDBTools/tree/gh-pages
더미 포스트와 샘플 페이지를 구성하여 푸시했는데 경로설정 문제때문에 에러가 빵빵 터지네여
오늘 밤 픽스해서 한번 더 푸시푸시

**Comment by hangum** [comment]
집에 도착하면 확인해볼게. 
머지하기 전에 확인해볼 패이지 있어?

**Comment by jungheelee** [comment]
아직 제 리포에서 작업하고 있어요. 머지는 일요일에 풀리퀘시 해주시면 될 거 같아요. 컨플루언스에 작성된 내용 중 릴리즈 관련된 내용들을 마크다운으로 작성하여 홈페이지에 포스팅하는 작업을 좀 도와주셨음 해요. 글 목록을 추려주실 수 있나요?

**Comment by jungheelee** [comment]
http://jungheelee.github.io/TadpoleForDBTools/

0. 저는 로컬환경에서 작업해도 상관 없지만 @hangum 님의 의견이 지속적으로 반영되는 것이 좋다고 생각되기 때문에 실제 페이지에 푸시를 하면서 작업하고 있습니다.

1. 요구사항을 수렴하여 메인 커버 사진을 없해봤는데 매우 허전합니다.

2. 로고가 없을 때 span 영역에 표시되는 사이트의 타이틀을 모든 경우 나타나게 수정했는데 버티컬 얼라인이 예쁘지 않아 재수정이 필요합니다. bourbon을 차용하고 있는 상태라 로고 영역만 css 클래스를 재정의하는 방법을 생각하고 있습니다. 여러번 이야기했지만 저는 CSS 까막눈이라 이건 좀 후순위로 미루고 싶은데 로고라 미룰 수도 없고 좀 난감합니다.

3. 대메뉴(네비게이션)를 아래와 같이 생각하고 있습니다. 추가될 내용이나 빼야할 부분, 혹은 보완해야할 부분이 있다면 알려주세요.
-About : 소개
-Service: 가격 정보 (이거 좀 알려주세요)
-Support: 컨텍 정보, 개발자 문서 포함
-Post: 각종 세미나, 릴리즈 정보등을 포스팅할 예정

4. 추후 홈페이지 운영에 도움을 줄 기여자가 생길지도 모르니 지킬을 통해 사이트의 컨텐츠를 추가할 수 있도록 개발환경 셋팅에 관한 RD를 만들고 싶습니다.

5. 올챙이 로고와 테마의 베이스 컬러가 조금 겉도는 느낌이 드네요.

**Comment by hangum** [comment]
어떻게 의견을 줄까요? 어니면 내용을 추가 할까요?

**Comment by hangum** [comment]
상단 메뉴에는 두개의 메뉴가 더 있었으면 좋겠어요. 

1. 네
2. 좀 허전하기 하네요. 
Welcome to Jekyll! 대신에 Welcome to Tadpole 을 넣고 
설명과 함께 올챙이 컨셉 이미지 를 넣으면 괸찮을까요?(https://sites.google.com/site/tadpolefordb/_/rsrc/1431536878594/home/TadpoleDBHub_overview.png?height=309&width=400)

3. 감사합니다.

4. 대 메뉴에는 현재 하나 정도 더 있으면 좋겠어요.
service 는 : tadpoledb.com 을 어떻게 구겨 넣으면 좋겠어요. 
Support 메뉴 :  기술지원 서비스 내용(https://tadpoledbhub.atlassian.net/wiki/pages/viewpage.action?pageId=20578306)

5. RD는 뭐에요? 

6. 그러게요. 흠.. 폰트와 색을 바꿔가면서 어떤게 어울릴지 계속 확인해야겠네요.

**Comment by jungheelee** [comment]
일단 원래의 이미지로 돌려놓고, 해당 이미지는 css로 구조에 맞춰 사이즈가 정해져있으니.. 비슷한 사이즈의 올챙이 이미지를 얻는 방법을 선택하는게 좋을 거 같아요.

RD=리드밐ㅋㅋㅋㅋㅋㅋㅋ

추가 이슈
7. 다국어 처리. 국내 사용자보다 국외 사용자들이 많은 관계로, 앞의 이슈들을 먼저 해결하고 한글 컨텐츠를 최대한 밀어넣은 뒤 영문 컨텐츠도 추가하는 방법을 고려 중 입니다.
