### ISSUE TITLE
REST API의 Result Type에 Shape 추가

### ISSUE THREAD

**Issue by jangbi882** [hangum/TadpoleForDBTools#617]
공간정보가 있는 Query의 결과를 Shape 파일로 만들어 shp, shx, dbf를 압축 후 메일로 전달한다.

**Comment by hangum** [comment]
억, 연락드릴게요.

**Comment by hangum** [comment]
Shape 파일로 떨구는 건 SDM에서 확장 개념을 만들어야 할듯해요 ㅠㅠ 
SDM 이슈로 만들어 놓고 여기에서는 닫을게요.
