### ISSUE TITLE
mssql xpath query 사용시 결과가 xml일 경우 여러줄에 표시됨.

### ISSUE THREAD

**Issue by dohwan-lee** [hangum/TadpoleForDBTools#626]
ssms 같은 경우 query 결과가 xml일 경우 한줄에 표시되는데에 비해
올챙이는 여러줄에 출력하여 결과를 변환(상세창에서)해서 볼때 한줄씩만 보임.
또는 xml로 되돌릴 경우 copy도 한줄씩만 가능함.

**Comment by hangum** [comment]
결과를 보여줄때 에디터에 너무 많은 텍스트를 뿌릴경우에 과도하게 느려지는 문제가 있어서 결과가 몇자 이상일 경우 잘라서 일부만 보여 지도록 해 놓았습니다. 

설정으로 바꾸실수 있는데요.  
프리퍼런스 -> rdb 쪽에 거시면 결과셋 몊자만 보여줄것인가 옵션을 수정하시면 됩니다. 

다른 버전에는 결과 글자를 잘라지게되면 잘라진것을 인식할수 있도록 뷰 화면을 수정하겠습니다. 

감사합니다.

**Comment by hangum** [comment]
![rdbset](https://cloud.githubusercontent.com/assets/1335915/10039738/086ee612-6210-11e5-8acc-c30713eff257.png)

이 값을 수정하면 되겠습니다.

**Comment by hangum** [comment]
값이 널이거나, 설정보다 길어서 짤린경우 아래처럼 처리했습니다. 감사합니다.


<img width="898" alt="2015-09-23 8 47 45" src="https://cloud.githubusercontent.com/assets/1335915/10044357/3e3aa176-6235-11e5-975b-6335525a6c62.png">

**Comment by hangum** [comment]
몇일간 버그와 개선 사항을 모아서 릴리즈 버전을 올렸습니다. 
감사합니다.
https://sourceforge.net/projects/tadpoledbhub/files/1.6.x/1.6.4/
