### ISSUE TITLE
war 파일 Tomcat 실행시 HTTP Status 404 - ProxyServlet: /

### ISSUE THREAD

**Issue by uyu423** [hangum/TadpoleForDBTools#627]
war 파일 webapp에 넣고 톰캣 재시작 후 host:8080/tadpole 로 접속하면
<pre>
HTTP Status 404 - ProxyServlet: /
</pre>
라는 에러메시지가 출력 되네요 ㅜㅜ

**Comment by uyu423** [comment]
음.. 이슈를 여기에 올려다 되는지는 잘 모르겠으나 게시글을 남길곳이 마땅치 않아 이곳에 남깁니다.

**Comment by hangum** [comment]
tadpole/tadpole 이어야해요. 
오늘 말끔하신 문제 두개 해결 한걸 올려 놓을게요.  오분만요

**Comment by hangum** [comment]
네. 편하게 올리셔요.

**Comment by hangum** [comment]
https://drive.google.com/file/d/0B3YIS2ZszMgpZmZNQllZakJFejg/view?usp=sharing
으로 쓰시고요. 

http://xxx:8080/tadpole/tadpole 이어야 해요. 

위의 파일로 다시 시작하실때는 
webapps/tadpole로 시작하는 폴더를 삭제하시구요.
work/Catalina 폴더도 삭제하셔야 합니다.

**Comment by uyu423** [comment]
정말 친절하신분. 감사합니다.

**Comment by hangum** [comment]
@uyu423  ^^
