### ISSUE TITLE
시스템별 배포판 있으면 좋겠습니다. 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#632]
각 os 별 배포판이 있었으면 좋겠습니다. 
원도우면 exe, ubuntu이면 dbe, mac이면 dmg로요. 
센트os 지원배포판도 필요하고요.

배포판은 JRE까지 포함된 상태이고 기본 설정도 되어 있어, 설치하면 바로 사용할 수 있어야 합니다.

배포판이 있으면 사용자들이 좀더 쉽게 올챙이를 접근할 수있는 방법이라 생각합니다.

참고)
http://www.scala-sbt.org/sbt-native-packager/

**Comment by hangum** [comment]
1.6.5 R2부터는 모든 배포판에 JRE를 넣어서 배포하도록 수정 되었습니다.

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <Re: [TadpoleForDBTools] 시스템별 배포판 있으면 좋겠습니다.  (#632)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hangum** [comment]
맥은 완성되었습니다.

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <Re: [TadpoleForDBTools] 시스템별 배포판 있으면 좋겠습니다.  (#632)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
