### ISSUE TITLE
원도우에서 로그인 히스토리 정보 저장 오류

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#633]
로그인 히스토리 화면에서 로그인 시간이 1970-01-01으로 저장되는 오류가 있습니다. 
ps) https://mail.google.com/mail/u/0/#inbox/15036b74cd27e013

<img width="501" alt="2015-10-05 4 54 54" src="https://cloud.githubusercontent.com/assets/1335915/10275376/e171f59c-6b81-11e5-8908-e97e2c385a40.png">

**Comment by hangum** [comment]
원도우 뿐만아니라 모든 os에서 나는 오류이구요. 
엔진디비를 sqlite를 사용했을때 나오는 오류입니다.

**Comment by billygoo** [comment]
다른 브랜치를 가지고 고쳤네요. 
1.6.6 버전들어가면서 로그인 히스토리가 검색이 안되네요..;;;

아래는 간단한 샘플이고, 지금 시간보다 큰 조건만 넣었을때 조회가 되고 특정일보다 작은 값을 넣으면 쿼리 결과가 조회가 안되네요.. 저만 그런걸까요?? 

위에 처럼 UserDAO 에서 Timestamp 타입을  String으로 처리하는걸 UserLoginHistoryDAO도 맞추려고 했는데 아래 오류가 나네요. 

로그인 기록 제대로 나오는지 확인 좀 해주시겠어요?? 

```sql
SELECT
    b.seq
    ,b.user_seq
    ,b.login_ip
    ,b.connet_time
    ,b.disconnect_time
  FROM
    tadpole_user a
    ,login_history b
  WHERE
    a.email = 'sangmo.gu@gmail.com'
    -- AND b.connet_time <= '1544316400056'
    AND a.seq = b.user_seq
    AND b.connet_time >= '1444316400056'
  ORDER BY
    b.connet_time DESC
```

**Comment by hangum** [comment]
네 ^^
툴로는 제대로 나오는데요.
프로그램을 수정해볼게요

2015-10-16 0:26 GMT+09:00 Billy Goo <notifications@github.com>:

> 다른 브랜치를 가지고 고쳤네요.
> 1.6.6 버전들어가면서 로그인 히스토리가 검색이 안되네요..;;;
>
> 아래는 간단한 샘플이고, 지금 시간보다 큰 조건만 넣었을때 조회가 되고 특정일보다 작은 값을 넣으면 쿼리 결과가 조회가 안되네요..
> 저만 그런걸까요??
>
> 위에 처럼 UserDAO 에서 Timestamp 타입을 String으로 처리하는걸 UserLoginHistoryDAO도 맞추려고
> 했는데 아래 오류가 나네요.
>
> 로그인 기록 제대로 나오는지 확인 좀 해주시겠어요??
>
> SELECT
>     b.seq
>     ,b.user_seq
>     ,b.login_ip
>     ,b.connet_time
>     ,b.disconnect_time
>   FROM
>     tadpole_user a
>     ,login_history b
>   WHERE
>     a.email = 'sangmo.gu@gmail.com'
>     -- AND b.connet_time <= '1544316400056'
>     AND a.seq = b.user_seq
>     AND b.connet_time >= '1444316400056'
>   ORDER BY
>     b.connet_time DESC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangum/TadpoleForDBTools/issues/633#issuecomment-148422009>
> .
>



-- 
__________________________
Google Talk: hangum@gmail.com
blog  : http://hangumkj.blogspot.com/
FaceBook : https://www.facebook.com/hangum
Tadpole DB Hub : https://github.com/hangum/TadpoleForDBTools

HyunJong Cho

**Comment by billygoo** [comment]
툴로도 나오나요?? 저거 본 이유가 실행했을때 결과가 안나오길래 봤거든요

**Comment by hangum** [comment]
이렇게는 잘 나오네요.  sqlite에 timestamp값이 없어서 그런듯해요.
말씀하신것처럼 String으로 처리하도록 수정해봐야겠어요
[image: Inline image 1]

On Fri, Oct 16, 2015 at 9:03 AM, Billy Goo <notifications@github.com> wrote:

> 툴로도 나오나요?? 저거 본 이유가 실행했을때 결과가 안나오길래 봤거든요
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangum/TadpoleForDBTools/issues/633#issuecomment-148557458>
> .
>



-- 
__________________________
Google Talk: hangum@gmail.com
blog  : http://hangumkj.blogspot.com/
FaceBook : https://www.facebook.com/hangum
Tadpole DB Hub : https://github.com/hangum/TadpoleForDBTools

HyunJong Cho

**Comment by hangum** [comment]
엔진디비를 sqlite로 하는 모든 날짜처리에 오류가 있네요. 
ibatis와 역는 부분을 수정해야겠어요.
