### ISSUE TITLE
쿼리 결과 내보내기 기능의 확장

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#643]
향후 확장성을 위해서 UI 를 조금 바꾸는건 어떨까요?

내보내기 기능에 다양한 옵션이 필요하기도 하구요..

![capture 1](https://cloud.githubusercontent.com/assets/859932/10502426/fa6dec66-7326-11e5-9d7e-7f05e3afaf63.png)

merge문이나 update문장도 있음 좋을듯~ ^^; 
insert into (....) values (....), (....), (....) <= mysql의 경우...등등 dbms별로...그리고 대상테이블명을 바꿔서 export할수 있으면 좋음...

업데이트 문장으로 export할때는 where절에 사용할 column을 pk기준으로 하고 없을경우 직접 선택할 수 있으면 좋음..^^;

**Comment by hangum** [comment]
다음과 같이 수정했어요. 
앞으로는 개선 사항은 형이 시간이 걸리더라도 개선해 주시겠어요?

![2015-10-16 1 31 53](https://cloud.githubusercontent.com/assets/1335915/10533889/6612167a-740a-11e5-8c0d-a3302cce5468.png)

**Comment by hangum** [comment]
JSON, CSV 콤마와 텝 형식으 다운로드를 받을수 있도록 확장 했어요

**Comment by hangum** [comment]
- Update 문 다이얼로그도 되었습니다. 
<img width="454" alt="update" src="https://cloud.githubusercontent.com/assets/1335915/14411117/4ad3ea18-ff7a-11e5-9049-e964f1247acd.png">

@jeongjaehong  merge sql 은 어떤거에요? 확장해주시겠어요.

**Comment by hangum** [comment]
#744  와 통합하고 닫을게요.
