### ISSUE TITLE
Eclipse marketplace Link fails

### ISSUE THREAD

**Issue by MortalCatalyst** [hangum/TadpoleForDBTools#644]
It appears the current link resolves to the wiki not install .

Unable to read repository at https://github.com/hangum/TadpoleForDBTools/wiki.
https://github.com/hangum/TadpoleForDBTools/wiki is not a valid repository location.

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <[TadpoleForDBTools] Eclipse marketplace Link fails (#644)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hangum** [comment]
@MortalCatalyst  ooops. I check it this problems. Thanks

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <Re: [TadpoleForDBTools] Eclipse marketplace Link fails (#644)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hangum** [comment]
I will fixed this problems.
Thanks for your report.
