### ISSUE TITLE
MYSQL 5.7 의 JSON지원에 대한 이슈 추가

### ISSUE THREAD

**Issue by goody80** [hangum/TadpoleForDBTools#645]
MYSQL 5.7 의 JSON지원에 대해, 출력 결과가 JSON 형태 일 경우, JSON view 기능 추가

**Comment by hangum** [comment]
컬럼 데이터의 자세한 자료를 보여 줄수 있는 창을 만들게요.
그 중 MySQL, PGSQL 데이터 타입이 json  일 경우 json을 인식하여 몽고 디비의 json뷰처럼 디테일 창을 보여줄수 있도록 확장 합니다.

**Comment by hangum** [comment]
결과화면 하단에 '컬럼보기' 버튼을 추가했구요.
타입이 json 일 경우 json 에디터 창이 뜨도록 작업했습니다. 
감사합니다.

<img width="605" alt="2015-10-21 5 19 17" src="https://cloud.githubusercontent.com/assets/1335915/10631285/f35b24fc-7817-11e5-8c74-7821ec1c949b.png">
