### ISSUE TITLE
war 파일 Tomcat 실행시 HTTP Status 404 - ProxyServlet: 오류

### ISSUE THREAD

**Issue by bumjin** [hangum/TadpoleForDBTools#646]
최신버전 war 로 tomcat에서 실행시  HTTP Status 404 - ProxyServlet: 오류가 표시됩니다.
JAVA : jdk1.7,
WAS : tomcat6, tomcat7, 
OS : window, linux 상관없이 모두 동일한 현상입니다.

tadpole.log에는 다음과 같이 찍힙니다.
Bundle initial@reference:file:plugins/org.eclipse.rap.rwt.testfixture_3.1.0.20150806-1542.jar was not resolved.

**Comment by hangum** [comment]
@bumjin  안녕하세요.

톰켓 7로 하셔야 하구요. 
요청 url 을 http://127.0.0.1:8080/tadpole/tadpole 로 하셨는지 확인해주세요.

**Comment by bumjin** [comment]
tadpole/tadpole로 하니 화면이 나오네요. 감사합니다.  
(매뉴얼이나 FAQ같은데 설명이 포함되었으면 좋을거 같습니다. 인터넷에서 tadpole war설치 등으로 검색시 tadpole/tadpole 형태로 호출한다는것은 못본거 같아서요.)
꼭 127.0.0.1로 해야하나요? localhost로 했더니 어드민이 허락한 IP대역을 벗어났습니다. 라고 
경고창이 뜨네요.

**Comment by hangum** [comment]
네. 메뉴얼은 https://tadpoledbhub.atlassian.net/wiki/pages/viewpage.action?pageId=21528601에 보시면 있어요. 일반적으로 tadpole 만 있으면 되는데 좀 그렇긴하네요. 개선해 볼게요. 

localhost 문제는시스템 어드민이 사용자의 ip 대역으로 올챙이 로그인을 못하게 하는 기능이 있는데요. 거기서 오류네요. 
개선해 보겠습니다.

**Comment by ys2cdh** [comment]
똑같은 내용으로 에러가 나서 실행이 안되고 있습니다.
로그 내용으로 봐서는 기동 할 때 나오고 있습니다.

tadpoled 버전(2017년 5월 25일 다운로드)
https://sourceforge.net/projects/tadpoledbhub/?source=typ_redirect

java 버전
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

Tomcat 버전 
7.0.73

요청 url http://xxxx.xxx.xxx.xxx:8081/tadpole/tadpole 하였습니다.

os 는 우분투 입니다.

**Comment by ys2cdh** [comment]
찾았습니다.
 http://xxxx.xxx.xxx.xxx:8081/tadpole/

끝에 /가 들어가면 접속이 됩니다.

**Comment by hangum** [comment]
@ys2cdh  수고하셨습니다. 
메뉴얼을 좀더 자세히 쓸수 있도록 하겠습니다.
