### ISSUE TITLE
독립 모듈일 경우 온라인 업데이트 가능했으면 좋겠습니다

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#664]
독립 모듈일 경우 온라인 업데이트 가능했으면 좋겠습니다
-- 설문에서

**Comment by WaveGrasper** [comment]
새로운 이슈를 만들려다 이미 등록된 이슈를 찾아보니 이 이슈와 요구사항이 가장 비슷해서 질문 남깁니다.
"독립 모듈일 경우"라는 게 어떤 경우일까요?
우선 기존 사용자가 발전하는 올챙이의 모습을 경험하기 위해서 새로 설치해야 합니다(매뉴얼 사이트에서 업그레이드 방법을 찾을 수 없습니다). 
새로운 버전을 자동으로 체크해서 패키지를 다운받고 사용자에게 알림을 주고 개선된 기능을 확인하고 업그레이드 여부를 결정할 수 있도록 하면 좋겠습니다.

**Comment by hangum** [comment]
독립모듈은 스텐드어론 어플리케이션을 의미합니다. 
자동업그레이드를 만들려고 하는데, 우선 순위에 밀려  못하고 있네요.

조만간(?) 되지 싶습니다.

**Comment by hangum** [comment]
독립 모듈 업데이트관련해서.
현재는 신 버전 업데이트가 나오면 업데이트를 알려주는 정도로 관련 기능을 정리하려고합니다. 

![2016-03-07 6 56 12](https://cloud.githubusercontent.com/assets/1335915/13566327/5a63b618-e498-11e5-981c-fa3b7519f38a.png)
