### ISSUE TITLE
sql parse exception

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#667]
It happens sometimes when I switches active editors over different database connections.
### sql contents
```sql
desc service_schedule;
select * from service_schedule;
show processlist;
```

### log for one by one execution
> 11:14:47, 602 ERROR - RequestQuery:praseSQL sql parse exception. [ desc service_schedule ] 
> 11:14:52, 750 ERROR - BasicTDBSQLParser:parseDML sql parse exception. [ show processlist ] 
There is no log for second sentence, 'select * from service_schedule;'

### log for all execution
> 11:20:03, 863 ERROR - BasicTDBSQLParser:parseDML sql parse exception. [ desc service_schedule;
> select * from service_schedule;
> show processlist ] 
> 11:20:03, 866 ERROR - RequestQuery:praseSQL sql parse exception. [ desc service_schedule;
> select * from service_schedule;
> show processlist ]

**Comment by hangum** [comment]
I'll check out this problems.

**Comment by WaveGrasper** [comment]
MySQL 인스턴스 세 개를 등록해서 사용중이고, 최근 아주 많은 시간을 사용하고 있습니다.
그런데 한 인스턴스에서만 쿼리가 안됩니다. 어떤 쿼리도 실패하는데, 같은 스키마인 다른 인스턴스에서는 잘 됩니다. 처음에는 아무런 문제가 없었는데 갑자기 이 현상이 나타났고, 에디터를 새로 띄워도, 새로고침 해도, 서버를 재시작 해도 해결이 안되네요. 다시 토드나 phpMyAdmin으로 돌아가야 하나 싶어 우울합니다.

**Comment by hangum** [comment]
두개의 인스턴스 상태와 문제 인스턴스 상태가 틀린가요? 혹은 환경이라도요.
일단 주신 로그 로는 말하신 이유로는 안돌아가는 원인을 짐작할 수 없네요. 
주신 로그로도 짐작할 수 없구요. 

-- 올챙이에 문제가 되는 인스턴스를 이름을 바꾸어 새롭게 등록해 보세요. 
그리고 시도해 보세요.
-- phpmyadmin이나 다른 클라이언트 툴로는 정상인지도 확인해 주시구요.

두개는 잘 되는데, 한개는 잘 안되고 그게 올챙이 때문일리가요?
(저는 20개도 올려 놓고 써요)

올챙이 로그 파일과 톰켓 로그 파일 전체를 주세요. 
안되면 phpmyadmin 으로 당연히 돌아가셔야죠.  붙잡지 않습니다.

**Comment by WaveGrasper** [comment]
phpmyadmin로 돌아가라니ㅜㅜ 튕기는 겁니까?
한 툴이 모는 면을 충족시키지 못하니 자연스레 왔다갔다 합니다.
phpmyadmin도 쓸만하지만, SQL 편집/저장 기능에 있어서 올챙이에 비교는 안되지요.
운영서버, 테스트 서버, 개발서버 뭐 이렇게 세 개이고 phpmyadmin으로는 잘 됩니다.
올챙이도 처음엔 다 잘 되었는데, 하다보니 안되기 시작했고 docker에 어떤 변경을 한 적은 없으니 순수하게 올챙이 내부 동작에 관계되었다고 봅니다.
올챙이 로그와 톰캣 로그가 다른가요? /usr/local/tomcat/logs/tadpole.log 

연결 설정을 삭제하고 다시 등록해 보고 결과를 알려드리겠습니다.

[tadpole.log.1.txt](https://github.com/hangum/TadpoleForDBTools/files/33561/tadpole.log.1.txt)
[tadpole.log.txt](https://github.com/hangum/TadpoleForDBTools/files/33562/tadpole.log.txt)
[eclispe_metadata.txt](https://github.com/hangum/TadpoleForDBTools/files/33563/eclispe_metadata.txt)

**Comment by hangum** [comment]
172.xx.xx.1  번 호스트에서 is not allowed to connect to this MySQL server") 와 같은 오류가 나고 있어요. 
해서 아래 이슈를 살펴보시면 좋겠습니다. 
http://stackoverflow.com/questions/1559955/host-xxx-xx-xxx-xxx-is-not-allowed-to-connect-to-this-mysql-server

ps) 아이피가 노출되어 로그 파일을 삭제할게요.

**Comment by WaveGrasper** [comment]
172 번은 docker가 올라가는 mac 네트워크가 안될 때 virtualbox 네트워크가 문제가 생기면서 임시로 있던 에러라 무시해도 되고, 외부 접근이 안되는 주소라 문제되지는 않습니다.
그보다 주목해야 할 점은, 둘 이상의 쿼리를 하나씩 실행하면 다 안되는데, 전체 실행하면 일부는 된다는 점입니다. 아래 쿼리를 Execute All 하면 처음 것은 실패하, 두번째는 성공합니다.
> select * from table1 limit 1;
> select * from table1 limit 1;

데이버베이스 삭제하고 다시 등록하니 잘 됩니다.
그런데  메뉴가 "데이터베이스 **삭제**"여서 한참 고민했습니다.:sweat:

**Comment by hangum** [comment]
다른 분이 구글 그룹으로 트랜잭션으로 쿼리를 실행하면 안된다고해서 실제로 수행해보니 안되네요. 그 에러와 말씀 하신 에러와의 연관성이 있을지도 모르니 찾아보겠습니다. 
왜 안될까요? 흠... 

메뉴의 내용은 '디비 등록삭제'로 수정해 놓겠습니다. 
헛갈릴수 있겠네요.  --;;

**Comment by hangum** [comment]
수정되었습니다. 
민감한 버그라 일요일밤 월요일 아침까지 1.6.6 r1을 내놔야겠네요. 

감사합니다.
