### ISSUE TITLE
MySQL Column Grid Editing

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#671]
매뉴얼을 보면 Oracle과 MSSQL만 지원한다고 명시되어 있는데요, 전체는 아니더라도 표준적인 변경문에 한해서는 MySQL도 지원했으면 합니다.

**Comment by hangum** [comment]
1.6.6 r1에서는  Oracle, MSSQL 뿐만 아니라 mysql(maria), pgsql 도 지원합니다. 

메뉴얼은 수정해 놓겠습니다. 
감사합니다.
