### ISSUE TITLE
올챙이DB 첫번째 실행시 에러가 나고, 두번째 다시 실행시 정상적으로 나타나요

### ISSUE THREAD

**Issue by hunylee** [hangum/TadpoleForDBTools#672]
1. 첫번째 실행시 HTTP 404를 찾을수 없습니다.
![tadpole_error1](https://cloud.githubusercontent.com/assets/1106559/11199832/97c869bc-8d14-11e5-9309-d24e06635dc8.PNG)

2. 두번째 실행시 정상적으로 나와요. 
![tadpole_status](https://cloud.githubusercontent.com/assets/1106559/11199883/e4fd5738-8d14-11e5-859f-ff57208c1882.PNG)

Version은  Tadpole DB Hub Version 1.6.6 SR 이에요. 

서버 설정 문제가 아닐것 같은데요. 

그래서 이미지 파일을 첨부합니당.

**Comment by hangum** [comment]
올챙이를 처음 실행하면, 엔진을 시작하고 웹서버를 시작하게되는데요. 
이 시간이 오래(?) 걸리면 위와 같은 화면이 나오게됩니다. 

그럴때는 잠시(몇초간) 기다렸다가 화면을 리프레쉬 해주세요. 
감사합니다.

**Comment by hangum** [comment]
수정해야겠네요.

**Comment by hangum** [comment]
일단은 좀더 기다리도록 수정하였습니다. 감사합니다.
