### ISSUE TITLE
Table Data Editor - Failed to parse markup text

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#673]
MySQL 테이블에 대해 Table Data Editor 실행 시 아래와 같은 에러의 대화창이 나타나지만 에디터는 열리고 데이터도 표시됩니다.
> ERROR - LogListener:logging Problems occurred when invoking code from plug-in: "org.eclipse.rap.jface".java.lang.IllegalArgumentException: Failed to parse markup text

**Comment by hangum** [comment]
사용하시는 버전이 어떻게 되세요?

**Comment by WaveGrasper** [comment]
1.6.6 R0 였는데, R1으로 업그레이드 하니 해결되었습니다.

**Comment by hangum** [comment]
감사합니다.
