### ISSUE TITLE
Feature Request - Column Grid의 열 순서 변경 기능

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#674]
작업에 따라 컬럼의 특정 정보를 집중해서 보는 경우가 있습니다.
열 제목을 드래그 해서 순서를 바꿀 수 있다면 좋겠습니다.

**Comment by hangum** [comment]
아래 화면에서의 컬럼 순서를 바꾸어 보고 싶으신 것이지요?
컬럼의 순서는 디비에 정해져 있는것을 보여주는데요. 
바꿔 보여주면 혼동의 여지도 있을듯합니다. 



<img width="497" alt="2015-11-17 1 46 07" src="https://cloud.githubusercontent.com/assets/1335915/11202962/98083e80-8d31-11e5-9f0d-2330f6f0cd5d.png">

**Comment by WaveGrasper** [comment]
디비에 정해져 있다는 게 무슨 뜻인가요? DDL 문의 컬럼 스펙 순서 말인가요?
제 뜻은 테이블 컬럼 정보를 보여주는 __뷰의 컬럼 순서를__ 변경한다..입니다.

**Comment by hangum** [comment]
위의 그림 같은 경우 seq는 첫번째, user_seq는 두번째로 있어야 하는 순서가 있다는 이야기에요. 
사용자에게 보여줄때만 바꾸어서 보여 주었으면 하는 것이지요?

**Comment by WaveGrasper** [comment]
행의 순서가 아니라 열의 순서 즉, 필드/타입/키/설명/널여부/기본값/확장정보 순서를 변경할 수 있으면 좋겠다는 뜻입니다.

**Comment by WaveGrasper** [comment]
RAP 테이블뷰어 위젯에서 기본으로 제공되지 않나요?

**Comment by hangum** [comment]
아 이제야 이해했어요?
저도 가끔 아쉽긴 합니다.(디비에 넣어 놓자니 부담이고, 쿠키에 넣어 놀까요? )
![2015-11-17 2 48 56](https://cloud.githubusercontent.com/assets/1335915/11203747/5ee64d5a-8d3a-11e5-95c2-2b12569066a8.png)

어떤 순서로 보세요?

**Comment by hangum** [comment]
바뀌도록 수정했습니다. 현재는 화면을 리프레쉬하거나 디비가 바뀌면 초기화 되구요. 
향후에는 디비에 저장할 수 있도록 하겠습니다. 

테이블-컬럼은 쿠키에 저장하여 쿠키까지는 살아 있도록 하겠습니다.

**Comment by WaveGrasper** [comment]
이런 사소한 요청까지 즉각 처리해주시다니, 감사할 따름입니다.

**Comment by hangum** [comment]
배꼽인사 드립니다. 감사합니다.
