### ISSUE TITLE
ERD 컬럼 설명 행 불일치

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#676]
제목을 쓰기가 어렵군요.
아래 그림과 같습니다.
테이블 컬럼 설명을 한글로 적었더니, 한글과 영문 출력 높이 차이로 인해 위치가 점점 더 틀어지고 있습니다.
![erd_comments](https://cloud.githubusercontent.com/assets/5283280/11207020/11ac4686-8d56-11e5-88cf-2e416f7ebe48.png)

**Comment by hangum** [comment]
gef 코드 안본지 좀 됐더니 좀 시간이 걸리겠네요.  
우선 순위를 좀 미뤄 놓을게요.

**Comment by hangum** [comment]
프레임웍 버그이고요. 리포팅할게요.
gef port 프로젝트가 거의 멈춰있어서 어떻게 될지 모르겠네요.

**Comment by hangum** [comment]
사용하시는 브라우저가 어떻게 되세요?
크롬이시면 다시 해보시겠어요.

**Comment by hangum** [comment]
오래 기다리셨습니다. 

- 원인은
-- 한글 폭 문제였고.기 위해 레이아웃을 잘못(?) 잡았고..
-- 한글 폭 문제였고.
-- 코멘트에 줄 바꿈이 있었을때 틀어졌네요.
