### ISSUE TITLE
Text-based Query Result View

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#677]
'Query result' view is a table-based output window.
I need text-based output to write queries reviewing previous query results.

**Comment by hangum** [comment]
What kind of text?
JSON, CSV style?

**Comment by hangum** [comment]
쿼리결과를 기존 테이블, JSON, CSV 하구요. 결과를 하나씩 추가할 수 있도록 하겠습니다.

**Comment by WaveGrasper** [comment]
뭐가 그리 급합니까. 전 mysql 터미널 출력 같은 형식을 말한 겁니다.

**Comment by hangum** [comment]
@WaveGrasper  thanks for request topic. 

![2015-11-25 4 50 03](https://cloud.githubusercontent.com/assets/1335915/11391426/ba3e75ea-9395-11e5-837c-7eca68e762f4.png)
![2015-11-25 4 50 12](https://cloud.githubusercontent.com/assets/1335915/11391427/ba6645de-9395-11e5-8677-095ff9e08ea3.png)
![2015-11-25 4 50 58](https://cloud.githubusercontent.com/assets/1335915/11391428/ba77c2fa-9395-11e5-8722-7f4a3be366d9.png)

**Comment by hangum** [comment]
이거 컬럼 복사 붙여넣기 불편하신 것 때문에 요청하신거에요?
