### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#678]
It looks like that user preferred language is based on client browser language.
Does It make you work harder on translation?

**Comment by hangum** [comment]
번역 품질이 많이 떨어지죠?

**Comment by WaveGrasper** [comment]
그게 아니라 올챙이의 세계화를 위해 이슈를 영문으로 작성하려 노력하는데, 화면이 한글이라...

**Comment by hangum** [comment]
브라우저 정보에서  초기 로케일을 설정하도록 수정해야겠네요. 

<img width="483" alt="2015-11-20 10 13 07" src="https://cloud.githubusercontent.com/assets/1335915/11289379/913edf6a-8f6f-11e5-9fb5-525581d681eb.png">
