### ISSUE TITLE
PostgreSQL에서 오브젝트 탐색기 개선

### ISSUE THREAD

**Issue by lunar999** [hangum/TadpoleForDBTools#679]
postgreSQL에서 Database -> Schemas ->tables, sequence...  와 같은 형태로 구분을 해서 보여주는 방향으로 개선이 필요합니다.
현재는 그냥 스키마와 관련없이 테이블. 뷰등만 뿌려주는데 Schemas가 다르나 테이블명이 같은경우에는 어떤 Schemas의 테이블인지 알수 없고 SQL 자동완성시에도 Schemas를 붙여주거나 혹은 선택하는 화면이 필요함(참조는 pgAdmin3를 보면 좋을듯함)

**Comment by hangum** [comment]
사용 하시는 버전이 어떻게 되세요?

**Comment by lunar999** [comment]
최신이요 얼마전에 릴리즈한거요 1,6,6요

**Comment by hangum** [comment]
테이블 뷰를 보여줄때 스키마를 보여주도록 수정하겠습니다.   뷰에서 스키마 명을 붙여 주면될까요?
에디터에는 스키마명을 주고 쿼리 문이 생성 되도록 하고 있어요.


<img width="368" alt="2015-11-20 7 01 34" src="https://cloud.githubusercontent.com/assets/1335915/11297055/45cd3212-8fb9-11e5-8f84-d64d12fee95b.png">
<img width="654" alt="2015-11-20 7 01 44" src="https://cloud.githubusercontent.com/assets/1335915/11297056/45cf31d4-8fb9-11e5-96b9-53fb5760c7ca.png">

**Comment by lunar999** [comment]
스키마가 테이블 스키마가 아니라요 db인스턴스안에 스키마가 있고 그 안에 테이블 시퀀스등이 있는구조에요 pgadmin한번 사용해보시면 이해가 쉬울꺼 같아요

**Comment by hangum** [comment]
알고 있는데요. 
테이블명 앞에 스키마를 다 붙여 놓을까요?
아니면, 디비 등록할때부터 스키마를 선택하도록 할까요?

![2015-11-21 12 10 08](https://cloud.githubusercontent.com/assets/1335915/11316394/d6392376-9048-11e5-8973-300536af86a2.png)

**Comment by lunar999** [comment]
스키마선택하는게 편해보입니다

**Comment by hangum** [comment]
현재는 Object Explorer에서 테이블명 앞에 스키마 명을 붙이도록 작업해 놓았습니다. 
향후에는 테이블 이름앞에 스키마 이름을 붙이던지(?), 아니면 처음 입력 받을때부터 스키마 명을 입력 받도록 고민해 보겠습니다.  

사용하실때 불편하시면 아래 첨부한 이미지처럼 필터에 스키마 명을 쳐 놓으시면 불편하시지만 그나마 괸찮으실듯합니다. 
<img width="383" alt="2015-11-22 2 35 12" src="https://cloud.githubusercontent.com/assets/1335915/11319653/b466536c-90c1-11e5-811f-158ec92f9a2f.png">

**Comment by hangum** [comment]
다른 이슈도 계속 찔러줘요
