### ISSUE TITLE
데이터베이스 목록에서 데이터베이스 선택 후, 오른쪽 마우스 컨텍스트 메뉴 중 '확장 브라우'라고 표시되고 있습니다.

### ISSUE THREAD

**Issue by nasky987** [hangum/TadpoleForDBTools#681]
로그인 이후 화면에서
데이터베이스 목록에서 데이터 베이스 선택 후, 오른쪽 마우스를 클릭 하면
나오는 컨텍스트 메뉴에서 `확장 브라우`까지만 표시되고 있습니다.
아마 `확장 브라우저` 또는 `확장 브라우저에서 열기` 또는 `확장 브라우저에서 실행` 정도에 의미를 담고 만드신듯 한데 완전한 글자가 표시되어 있지 않습니다.
![](http://i.imgur.com/oYODMGC.png)

**Comment by hangum** [comment]
수정하도록 하겠습니다. 
감사합니다

**Comment by hangum** [comment]
이번주 주말에 1.6.7 버전에 반영될 예정입니다. 
감사합니다. 

<img width="370" alt="2015-11-22 8 02 15" src="https://cloud.githubusercontent.com/assets/1335915/11323398/e7580a0c-9154-11e5-9c1d-7b91df1a1f2d.png">
