### ISSUE TITLE
데이터베이스 환경설정 창 리사이징 문제

### ISSUE THREAD

**Issue by nasky987** [hangum/TadpoleForDBTools#682]
[관리] -> [데이터베이스 관리] 메뉴에서
데이터 베이스 선택 후 데이터베이스 환경설정 버튼을 클릭하면 나오는 창의 사이즈가
조금 작은듯 합니다.
하단의 `SELECT문 이외에 확인 후 실행` 체크 박스가 다 표현이 되지 않고 있습니다.
임의로 늘려줬을때는 잘 표현 되지만 약 10~20px 정도가 모자라지 않나 싶습니다.
![](http://i.imgur.com/4DbU7QS.png)

**Comment by hangum** [comment]
문장을 좀더 이해 할만하게 수정할게요.

**Comment by nasky987** [comment]
이 화면이 데이터베이스 신규 등록할때도 일부 사용되고 있는데 그 화면에서는 잘 나와서요 바꾸게 되시면 그 화면도 같이 수정되어야 할 듯 합니다.

**Comment by hangum** [comment]
@nasky987  네 같은 화면이에요.  
디비마다 좀 틀리고해서 조절하는 코드가 있는데, 수정해야겠어요.

**Comment by hangum** [comment]
확인해 보니 1.6.6 버전 부터는 수정이 되었네요. 감사합니다. 
![2015-11-22 8 29 29](https://cloud.githubusercontent.com/assets/1335915/11323540/ce4e4410-9157-11e5-84f2-3a79aaf063b7.png)
