### ISSUE TITLE
[질문] 메뉴 클릭시 한글화 및 일관성 문제

### ISSUE THREAD

**Issue by nasky987** [hangum/TadpoleForDBTools#683]
이 부분은 사실 큰 문제는 아니지만 한글화 사용시 영문에서 사용하는 메뉴가 사용되어 일관성있게 되어 있지 않는듯 한 부분에 대한 건의? 문의 입니다.
메뉴와의 일관성이 되면 더 좋지 않을까 하는 마음에 남깁니다.

1. [관리] -> [REST API 관리자] 메뉴 클릭시 오른쪽 뷰에는 [RESTFul API Manager]로 표시
2. [어드민] -> [사용자 관리] 메뉴 클릭시 오른쪽 뷰에는 [User List]로 표시
3. [어드민] -> [메시지 보내기] 메뉴 클릭시 나오는 팝업창 제목은 [이메일 보내기]로 표시됨

![](http://i.imgur.com/eyA1i8v.png)

**Comment by hangum** [comment]
@nasky987  감사합니다.  
시간내서 용어사전등의 일반화 시키는 작업을 한번 해야겠네요.

**Comment by hangum** [comment]
1.7.1 버전에는 좀더 직관적인 메시지를 보여줄수 있도록 작업하였습니다
여러번 걸처서 수정해야겠지만, 메시지등 전체를 리팩토링 하였습니다.

**Comment by hangum** [comment]
지역화에 대한 이슈는 이슈로 정리하고 있습니다. 
https://github.com/hangum/TadpoleForDBTools/issues/724
