### ISSUE TITLE
[어드민] -> [사용자 관리] 메뉴 클릭 후 오른쪽 뷰에서 [추가] 버튼 클릭시 나오는 팝업창 리사이징 문제

### ISSUE THREAD

**Issue by nasky987** [hangum/TadpoleForDBTools#684]
[어드민] -> [사용자 관리] 메뉴 클릭 후 오른쪽 뷰에서 [추가] 버튼 클릭시 나오는 팝업창 리사이징 문제
Goole OTP 체크 안되어 있을 때 숨겨진 메뉴 중 일부 표시되고 있습니다.

큰 문제는 아니지만 이런 이왕이면 다 안보이는게 더 깔끔해 보이지 않을까 싶어 남겨 드립니다.

![](http://i.imgur.com/urzKYV7.png)

**Comment by hangum** [comment]
1.6.6 버전부터는 수정이 되었네요. 
감사합니다. 
<img width="381" alt="2015-11-22 8 32 15" src="https://cloud.githubusercontent.com/assets/1335915/11323559/2f05b4e6-9158-11e5-80c9-67027f0bd187.png">
