### ISSUE TITLE
서버에 있는 여러 데이타베이스가 있을 경우 

### ISSUE THREAD

**Issue by ys2cdh** [hangum/TadpoleForDBTools#689]
마리아DB에서 여러 데이타 베이스를 쓰고 있습니다.
데이타베이스가 많기 떄문에 해당 건들을 다 만들어서 보기에는 너무 불편 합니다.

다른 데이타베이스 접속 가능하게 use 데이타베이스 가 가능 하도록 만들 수 없을 까요?

**Comment by hangum** [comment]
말씀하신 use 데이터베이스 기능은 현재 기능을 막아 놓은 상태입니다. 
올챙이에 디비 접근 제어 기능이 있는데 그 기능과 충돌 때문이구요. 
기능을 어떻게 할지는 좀더 검토해보겠습니다.
감사합니다.

**Comment by hangum** [comment]
다음버전에는 use 명령이 먹도록 수정하겠습니다. 
감사합니다.

**Comment by hangum** [comment]
사용자의 권한이 있을 경우 접근 되도록 코드에 반영되었습니다. 감사합니다.
