### ISSUE TITLE
rest full api

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#690]
비슷해 보이는 두 기능이 하나는 정상작동하고 하나는 작동하지 않습니다.
![capture 1](https://cloud.githubusercontent.com/assets/859932/11579221/f1b5665e-99e0-11e5-94d5-46c76aba1005.png)

![capture 2](https://cloud.githubusercontent.com/assets/859932/11579224/f857feb8-99e0-11e5-9429-f4a9d30c16f0.png)

등록한 API를 외부에서 호출하면 페이이 호출이 안됩니다...(이건 크롬앱에 등록된 서버에 등록된 api라서 당연한거 같기도 하네요..^^;)
![capture 6](https://cloud.githubusercontent.com/assets/859932/11579263/deebc420-9a6f-11e5-868e-f3468eef7b07.png)

**Comment by hangum** [comment]
초기에 api hub테스트 페이지 였네요.   

크롬 익스텐션에서 테스트 하셔야하구요. 
chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/RestClient.html

환경설정 레스트풀 api의 키를 설정하셔야합니다. 

![2015-12-04 11 16 36](https://cloud.githubusercontent.com/assets/1335915/11580245/8d70d9a6-9a78-11e5-82b4-4fb392d949e1.png)
<img width="629" alt="2015-12-04 11 16 44" src="https://cloud.githubusercontent.com/assets/1335915/11580244/8d70be3a-9a78-11e5-8fec-b19b21015729.png">

**Comment by hangum** [comment]
수정되었구요. 쿼리 파싱하다가 문제가 발생했네요.
