### ISSUE TITLE
Query Editor Auto-Save

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#695]
I have been losing many query at session timeout, refreshing browser or server restart.
Please add auto-save function by new successful query.

**Comment by hangum** [comment]
다음을 채크해 주세요. 
- 브라우저 세션타임 아웃이 되셨다면 환경설정-> 일반설정->세션 타임아웃 으로 설정하실 수 있습니다.
![user](https://cloud.githubusercontent.com/assets/1335915/11680940/12ac97b6-9e9f-11e5-992a-12017e10ce3d.png)
- 쿼리의 타임 아웃이라면 환경설정 -> RDB 설정 -> 쿼리 타임아웃(초) 로 설정하실 수 있습니다.
![query](https://cloud.githubusercontent.com/assets/1335915/11680967/476618a6-9e9f-11e5-8322-487da77c7d7d.png)
- 올챙이에는 과거에 실행 했던 쿼리 히스토리가 남습니다. 에디터 하단 -> 요청한 쿼리 히스토리 페이지에서 검색하실수 있습니다 
![editor](https://cloud.githubusercontent.com/assets/1335915/11681000/6e264574-9e9f-11e5-831c-9d6a9838289f.png)

감사합니다.

**Comment by WaveGrasper** [comment]
친절한 설명 감사합니다. 그래도 이렇게 닫으면 안될 것 같습니다.
최신 버전 1.6.7 R0 로 업그레이드 후 예외가 가끔 발생하여 새로고침하게 되는데, 그 때도 편집중인 내용을 잃게 됩니다.
그리고 쿼리이력은 참고가 되겠지만, 에디터 창에 쿼리 뿐만 아니라 이슈해결을 위한 설명을 쭉 기록해 두는데, 그것들은 다시 작성해야 합니다.
새 버전에서 발생하는 에러는 다시 발생하면 이슈로 올릴께요.

**Comment by hangum** [comment]
1.6.7 버전에서 예외가 발생할때 화면 캡쳐와 상황 설명을 해주시면 참조가 많이 될듯해요. 
에디터상의 쿼리의 마지막 정보를 기록해 뒀으면 하시는거에요?

**Comment by WaveGrasper** [comment]
에디터를 쿼리가 범벅이 된 보고서로 활용한다고 보면 되겠습니다.
예외는 오늘 여러번 겪었으니까 내일도 볼 수 있을 겁니다.

**Comment by hangum** [comment]
쿼리 자동 저장은 다음과 같습니다. 

# 에디터를 새롭게 오픈하면
##  30초 단위로 에디터의 쿼리를 자동 저장( 자동 저장 된 쿼리는 히스토리 관리 안함)
## 에디터가 새롭게 열리면 자동 저장된 쿼리가 자동으로 오픈됨.
문제는) 이름이 없는 에디터를 두개 열어 작업하면 어떻게 해야 할까요? 

이정도로 정리 하려고 합니다. 
의견 주세요.

**Comment by hangum** [comment]
개선 되었습니다. 
<img width="634" alt="autosave" src="https://cloud.githubusercontent.com/assets/1335915/12537779/46b3839a-c30b-11e5-8e6b-ca1a3c033f86.png">
