### ISSUE TITLE
업데이트 쿼리 실행 확인 대화창 취소해도 실행됨

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#696]
쿼리를 블락으로 선택하고 실행하면 확인창이 뜨는데, ESC로 취소해도 실행됩니다.
항상 그래요.

**Comment by hangum** [comment]
스크린 캡쳐 올려주시겠어요

**Comment by hangum** [comment]
운영디비로 설정하시고 업데이트 쿼리 실행했을때 말씀이시죠?

**Comment by hangum** [comment]
![2015-12-09 8 35 38](https://cloud.githubusercontent.com/assets/1335915/11684370/7cd6914a-9eb4-11e5-8ad3-a98441ba1bb9.png)

에디터에서 이 창 말씀이세요?

**Comment by WaveGrasper** [comment]
맞습니다. 운영인지는 확실히 기억이 안납니다.

**Comment by hangum** [comment]
@WaveGrasper 에디터에서의 작동은 원하는데로 작동했어요.   어떤화면인지 좀더 찍어주시면 좋겠습니다.

**Comment by WaveGrasper** [comment]
그러고 보니 운영서버가 아니면 확인창이 뜨지를 않는군요.
첫번째 그림에서 확인창을 나타났을 때 esc로 닫으면 두번째 그림처럼 실행했다는 결과가 나오고 실제로 삭제되었습니다.
![screen shot 2015-12-16 at 3 26 48 pm](https://cloud.githubusercontent.com/assets/5283280/11833784/894e488c-a409-11e5-8303-fc2547216d65.png)
![screen shot 2015-12-16 at 3 26 58 pm](https://cloud.githubusercontent.com/assets/5283280/11833785/895709cc-a409-11e5-8b59-730a3d273f0c.png)

**Comment by hangum** [comment]
@WaveGrasper  아네 감사합니다. 
수정했습니다. 코딩이 개발 세발로 되어 있었네요. --; ;
