### ISSUE TITLE
싱글 모드로 실행시 올챙이 서버 종료 방법 필요

### ISSUE THREAD

**Issue by jangbi882** [hangum/TadpoleForDBTools#697]
로그인이 필요 없는 싱글 모드로 들어갈 경우, 올챙이 서버를 내릴 수 있는 버튼이 안 나옵니다.
때문에 올챙이를 죽이려면 컴퓨터를 끄거나 프로세스를 찾아 죽여야 합니다.

싱글 모드에서도 종료 버튼이 나오게 해 주세요~

**Comment by hangum** [comment]
수정되었습니다.
