### ISSUE TITLE
테이블과 컬럼 선택시 SQL 버튼과 ERD 버튼 비활성화되는 문제

### ISSUE THREAD

**Issue by jangbi882** [hangum/TadpoleForDBTools#698]
데이터베이스에 접속 후
테이블의 리스트나 컬럼의 리스트를 선택하면
상단 툴바에서 SQL과 ERD 버튼이 비활성화 됩니다.

때문에 직관적으로 새 SQL 창을 띠울 수 없게 됩니다.
테이블이나 컬럼 리스트가 활성화 되더라도 데이터베이스가 어느것 인지는 명확하므로
이 버튼들이 활성화되어 있었으면 합니다.

**Comment by hangum** [comment]
수정되었습니다. 
이제 메니저 뷰에 디비가 선택되어 있으면 버튼이 활성화 됩니다.
