### ISSUE TITLE
2016년 목표(작성 중)

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#701]
- 홈페이지 생성
- 아마존, 애저 마켓플레이스에 올챙이 올리기
- LDAP 기본지원
- 어드민 API 공개(https://github.com/hangum/TadpoleForDBTools/issues/700) 
  어드민이 사용자와 추가, 삭제, 데이터베이스의 추가 삭제를 API로 할수 있도록 합니다.
- CI, Test 관련 코드 정비
- 신규 디비 지원
-- 전체 기능을 지원하지는 않더라도, JDBC 드라이버가 있다면 쿼리 할수 있는 기능(?) 지원

-  Tadpole Data Compare, Tadpole Report 기능 개발

**Comment by iamsunhan** [comment]
2016년 일본어 버전 추가 예정입니다. 히히..

**Comment by hangum** [comment]
@iamsunhan  감사합니다.
