### ISSUE TITLE
데이터베이스 간 SQL 쿼리 리소스 공유

### ISSUE THREAD

**Issue by WaveGrasper** [hangum/TadpoleForDBTools#703]
테스트 서버에서 쿼리문을 검증하고 운영 서버에 적용할 때 일일이 쿼리 리소스 파일을 새로 만들어서 복사/붙여넣기를 해야 하는 불편함이 있습니다.
테스트와 운영 서버를 짝짖고 이에 대해서 리소스를 공유할 수 있다면 편리하겠습니다.
에디터 상단 메뉴바에서 리소스가 공유되는 서버 버튼이나 드랍다운 리스트가 있고 작업 대상 서버로 선택할 수 있으면 되겠습니다.

**Comment by hangum** [comment]
좋은 아이디어 감사합니다.

다음버전에는 반영해 놓도록 하겠습니다.

**Comment by hangum** [comment]
@WaveGrasper 기능정의를 하려고 고민을 해보는데 어떻게 정의해야할지 모르겠네요. 
- 1.7.x 부터는 에디터에 자동 저장 기능을 넣어놨어요. 

동기화(?) 공유는 작업중인 쿼리가 있을수도 있고 등을 어떻게 정리해야할까요?

**Comment by jeongjaehong** [comment]
리소스를 에디터에 불러온 다음에 해당 에디터창이 연결된 데이터 베이스를 선택(변경, 운영<->개발 또는 이기종 dbms간에...) 할수 있다면 아래쪽에 쿼리결과 고정(pin) 후 비교기능을 이용해 조회결과도 비교해 볼 수 있어서 좋을듯 합니다. ^^;

**Comment by hangum** [comment]
상단에 같은 그룹의 디비리스트를 보여주어서 현재 에디터를 선택할 수 있도록 합니다. 
- 저장된 리소스라면 쿼리 불러올때와 실행, 저장, 다른 이름으로 저장이 헛갈리는데 어떻게 정리할까요?
![703_nw](https://cloud.githubusercontent.com/assets/1335915/14416391/a99c497c-ffe4-11e5-8567-1495de3439b7.png)

**Comment by WaveGrasper** [comment]
이슈만 만들어 놓고 답이 늦었군요.
여러 가지 방법이 있겠지만 조금 생각해보면,
리소스를 저장할 때 공유할 데이터베이스를 선택하거나 아니면 데이터베이스 그룹 단위로 공유할 지 말 지를 선택할 수 있으면 되겠습니다.
공유된 리소스는 데이터베이스 마다 보여지면 되겠고, 어떤 데이터베이스에서 오픈했는지를 타이틀에 표시하면 되지 않을까 합니다.
다른 데이터베이스에서 열린 또는 다른 사용자가 열어 편집하는 경우는 저장할 때 병합하면 될 텐데, 이 과정이 일이 많겠죠. Git의 병합 같은 방법도 생각할 수 있겠지만 효용에 비해 작업이 너무 클 것 같습니다. 단순히 덮어쓸 것인지 버릴 것인지만 선택할 수 있어도 충분하지 않을까 싶습니다.

**Comment by hangum** [comment]
다음과 같습니다. 
디비 이름 옆의 화살표를 선택하면 그룹의 디비 목록을 보여줍니다.  디비를 선택하면 해당 디비로 작업이 가능하구요. 
- 조건은 다음과 같습니다.
-- 트랜잭션 커넥션일 경우 해당 트랜잭션을 끝내야 가능합니다. 
-- 이미 저장된 리소스를 가져왔을경우 기존 리소스에 계속 저장이 됩니다.  as 누르면 새롭게 저장되겠지요.
-- 자동 저장도 이미 자동 저장되고 있다면 원래 자동 저장된 아이에게 계속 저장 됩니다. 

![703](https://cloud.githubusercontent.com/assets/1335915/14523592/6ffde54e-026f-11e6-8747-9c508495c935.png)
