### ISSUE TITLE
JDBC drivers in Tadpole

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#705]
현재 올챙이는 내부에 지원하는 DBMS들의 드라이버를 모두 가지고 있고... 프로그램 기동시 모두 읽어들이는 것으로 알고 있습니다(혹시 틀리면 말씀해 주세용.. 아직 분석을 마치지 않아서..) 

여기에는 다음과 같은 문제점이 있습니다. 

1. 상용 디비, 즉 오픈소스가 아닌 돈을 받고 판매하는 디비의 경우 라이센스 문제가 있을 수 있습니다. 드라이버도 결국 돈을 받고 파는 것일 수 있다는 얘기지요... 

2. 디비들의 상/하위 호환성 지원 정책에 따라 사용자는 문제가 발생할 수 있습니다. 각 벤더들 마다 상위 호환성(높은 버전의 클라이언트 --> 낮은 버전 서버 접속)과 하위호환성(낮은 버전의 클라이언트 --> 높은 버전 서버에 접속)의 보장 범위가 다르기 때문에 만약 올챙이가 내부적으로 가지고 있는 드라이버가 .. 같은  DBMS라 할지라도 .. 호환이 안되는 경우가 있을 수 있습니다. (올챙이가 가지고 있는 MySQL 드라이버가.. 너무 최신이여서.. 이전 버전 MySQL을 사용하는 사용자는 서버에 접속할 수 없는 등...)

3. 사용자는 불필요한 라이브러리를 모두 가지고 있어야 합니다. .. 사용자는  MySQL 한 종류만 사용하는데.. 올챙이에서 지원하는 모든 디비의 드라이버를 모두 가지고 있어야 하고... 또한 메모리에 올라가 있다면 디스크든,, 메모리든 리소스 낭비가 될 수 있습니다.

그래서... 다음과 같은 방법으로 고치면 어떨까 합니다. 
일단 .. 올챙이 개발시 보증하는.. 각 디비별 기본 지원 범위를 정하고(예: 오라클 9i 이상).. 사용자가 올챙이를 설치할 때 ... 사용할 디비의 드라이버를 특정 디렉토리에 넣어줍니다(디비서버랑 같은 버전이나..본인이 사용했던 것 넣겠지요..).. 필요한 경우 프로퍼티 설정 정도 할 수 있겠지요... 
그러면... 올챙이는 기동시.. 그 디렉토리에서 정보를 읽어... 디비들의 종류를 파악한 다음 그것을 기준으로 ..현재의 서비스를 제공하는게 어떨까 합니다.. (즉 ..해당 디렉토리에  MySQL JDBC  드라이버만 있다면.. 디비 등록에..MySQL만 나오고... MySQL JDBC, SQLite 가 있다면..두개가 나오고..이런 식..)
즉, 기존에 데이터베이스 드라이버를 올챙이가 ..모두 가지고 관리 했다면. 이것을 사용자에게 전가하여.. 올챙이는 경량화 하고... 위에 3가지 문제점들을 극복하는 것이죠.... 

다른 좋은 의견들 ... 기다립니다.

**Comment by ys2cdh** [comment]
squirrel sql 에서 동일한 방법으로 관리하고 있습니다.

사용하는데 불편은 없었습니다.

**Comment by iamsunhan** [comment]
사실 이 이슈를 꺼낸 것은 1번과 2번.. 특히 2번의 영향이 큽니다. 
물론 사용자들은 올챙이를 사용하기 위해 드라이버를 내부적으로 사용해서 .. 실제로 드라이버를 사용해 클라이언트 프로그램을 작성하는 사람 만큼.. 드라이버 버전이나 새부 기능등에 민감하지는 않겠지만.. 그렇다고 하더라도.... 
만약 ... 어떤 드라이버에 버그 수정이나 성능 향상 작업.. 기능 추가 등이 있었다고 하면.... 사용자는 해당 드라이버를 사용하기 위해 올챙이가 새로 패치되는 것을 기다려야 하는 수 밖에 없습니다. 
올챙이 입장에서도 현재보다 지원하는 데이터베이스의 수가 늘어날 경우 .. 그런 것들을 모두 세심하게 체크해주거나..아니면 지원 대상 버전을 한정적으로 가지고 갈 수 밖에 없습니다. 
벤더마다 드라이버를 이슈를 파악해서 관래해줘야 하는 올챙이도,,, 올챙이의 패치를 기다려야 하는 사용자 입자에서도 부담일 수 있을 것 같아서 .. 이번참에 ... 드라이버 버전 등의 선택을 사용자 입맛이 맞게 설정 할 수 있도록 선택권을 주고... 올챙이도 경량화 해서 가볍게 가는게 어떨까 해서 .. 생각해 본 것 입니다. ㅎㅎ

**Comment by hangum** [comment]
@ys2cdh  @iamsunhan  좀더 고민해 봐야 하는것이 a 팀에서는 버전 1.0을 사용하고 b 팀에서는 2.0을 사용하고자 했을 경우에 선택권을 주어야 할까요?
웹이다 보니, 일반 c/s 처럼의 접근이 좀 힘들듯해요.

**Comment by iamsunhan** [comment]
일반 C/S도 ... 데이터소스 클래스 이름이 동일하면 하나밖에 ... 사용 못하지 않나요?? (ㅎㅎ 제가 웹도 자바도 잘 몰라서리.... ) 
세부적으로 버전까지 주면야..좋겠지만...  데이터소스 클래스 이름이 동일한 선에서..... 하나만 로딩해서 쓰는 걸로 ... 정해도 괜찮지 싶어요... 
지금 구조를 .. 바꾸기 힘들면... 제 생각엔... 현재 올챙이 구조를 그대로 .. 유지 하돼...... 사용자가 원하는 드라이버가 있으면... 특정 디렉토리에 카피해서 다시 띄우면 ...되는 정도로만 해도 좋을 것 같습니다.

**Comment by iamsunhan** [comment]
어렵네용... ㅎㅎ 역시.. 쉬운게 하나도 없어요... 
제가 자바나 웹쪽을 이제 막 공부하는 중이라... 진짜 초보예요.. ㄱ

**Comment by iamsunhan** [comment]
아.. 이런.. 뭔가 잘못 눌러서...  멘트도.. 이 이슈도 이상하게 되어버렸네요.. 혼란을 드려 죄송합니다...

**Comment by hangum** [comment]
지금은 구조가 여러개의 드라이버를 동적 로딩하는 것이 아니라, 조금 힘든 부분이 있네요. 
osgi 가 알아서 해주긴한데, 스터디가 좀 필요해요.

**Comment by hangum** [comment]
좀더 다양한 의견이 있어야 해서 좋은듯한데요.

**Comment by hangum** [comment]
원하는 드라이버 버전을 잘 올려줄수있는것도 큰 장점이겠는데요. 흠흠흠... 좀더 스터디를 해볼게요.

**Comment by hangum** [comment]
반영했습니다. 
이번주 주말을 기대해 보아요.
