### ISSUE TITLE
작은 버그 1개와 의견 입니다.

### ISSUE THREAD

**Issue by lahuman** [hangum/TadpoleForDBTools#706]
안녕하세요. 올챙이를 사용하면서 발견한 작은 버그 한개 올립니다.

버그. 멀티라인 주석 (/* */) 에 ; 이 있을 경우 하위 행에 대한 SQL 질의가 이루어 지지 않습니다.
예) select * from ABC /* from ccc; */ where a=1  경우 where 조건 제외 처리
* 단일 라인 주석(--)의 경우 문제 없이 동작 합니다.

의견. 함께 사용하는 분들이 불편한 점이 쿼리 결과를 바로 복사(Ctrl + C) 할 수 없는 부분입니다.

감사합니다. 오늘도 즐거운 하루 되세요. :)

**Comment by hangum** [comment]
아, 저번에 말해 주셨는데.. 놓쳤네요. 
이번 베타 나올때는 수정하도록 하겠습니다.  죄송합니다. 

쿼리 결과 복사는 계속 다양한 방법으로 시도 중이에요.
저번 1.6.7 버전에서는 쿼리 결과를 텍스트로 보여주는 부분을 시도했었는데 1.6.8 버전은 빼기도했구요. 
좀더 방법을 찾아보겠습니다. 
(https://tadpoledbhub.atlassian.net/wiki/download/attachments/26804235/queryResult.png?version=2&modificationDate=1449411309775&api=v2)

**Comment by lahuman** [comment]
추가로, 버그는 아니고, 내부 네트워크 사용시 확인된 부분 입니다.

1.6.8 기준으로 최초 화면 호출시 "http://www.google-analytics.com/analytics.js" 를 호출 해서 행이 걸리는 경우가 있습니다.
조금 특이한게 특정 자리에서만 현상이 있네요. 

늘 발전하는 올챙이를 응원합니다.

**Comment by hangum** [comment]
@lahuman  앗, 그런문제가 있는가 보네요.  어떤 특성이 있을지 좀더 찾아봐야겠네요. 

에디터는 전체를 바꿔야 할지 아니면 기존을 수정할지 고민중에 있습니다. 
근본적으로 수정하는게 가능할지도 고민이구요. 
무언가 결정되면 메시지 공지 하겠습니다.

**Comment by hangum** [comment]
오래기다려 주셔서 감사해요. 
다음의 쿼리로 테스트해 했습니다
![query](https://cloud.githubusercontent.com/assets/1335915/12637668/662a7734-c5da-11e5-929c-a07c19459347.png)

쿼리 결과 카피는 현재는 브라우저에서 클립보드 카피가 브라우저 보안문제로 쉽지 않는상태이고요. 
프레임웍 개발팀의 q&a를 하였지만 같은 응답을 받은 상태이에요. 

해서 다음과 같은 방법으로 사용하시면 어떨까 싶습니다.   결과를 더블클릭하시면 데이터 직접 수정되도록 결과가 블럭되는데 거기서 ctrl+c를 하시면 어떨까 싶습니다. 
![reqult](https://cloud.githubusercontent.com/assets/1335915/12637674/6c5b72d4-c5da-11e5-8d34-fb189b790b44.png)

좋은하루 되십시오.

**Comment by magnet0706** [comment]
친구추가를 어떻게 하는건지.. 익숙하지 않은 깃허브 활동입니다 킄킄

**Comment by hangum** [comment]
어떤 친구 추가를 생각하세요?

**Comment by magnet0706** [comment]
오 안녕하세요 저는 다니엘 임 님께 조언을 구하는 초보 개발자인데요
혹시 올챙이 개발자님이신가요^^*
 
요즘 깃허브를 사용하기 시작했는데 사용법이 서툴러서 제가 개발자 님께 잘못 글을 올렸나보아요.
 
오픈소스 개발을 자비로 하시는 열정적인 모습 본받고 싶습니다. 
 
제가 잘못 글을 개제하는 바람에 이런 일이 있었네요^^
 
친절히 답장을 보내주셔서 감사합니다 .
 
 
-----Original Message-----

**Comment by hangum** [comment]
@lahuman  ^^
@magnet0706 꾸벅~ 좀더 구체적인 결과가 있어야 할 것인데, 허접한 개발 능력 밖에 없는듯 하네요. 친하게 지내요.

**Comment by hangum** [comment]
에디터 기능이 많이 수정되어서, 수정 사항이 나오면 말해주세요. ~~
