### ISSUE TITLE
오타 및 버그

### ISSUE THREAD

**Issue by uyu423** [hangum/TadpoleForDBTools#708]
모든 곳에서 그런지는 모르겠지만 사용자 관리 - 사용자 데이터베이스 관리에서 '역할'이 '역활'로 오기되었네요.

그리고 로그아웃시 return 페이지 url이 이상합니다.
예를들어 링크각 'http://abc.com:8080/tadpole/tadpole' 로 돌아가야하는데 'data:text/html,chromewebdata' 와 같이 완전 이상한 링크로 가게됩니다.

**Comment by hangum** [comment]
@uyu423  리포팅해주셔서 감사해요. 
사용하시는 버전과 운영체제를 알려주시면 감사하겠습니다.

**Comment by hangum** [comment]
@uyu423  
한글 표기 오류는 수정했습니다.감사합니다.

사용하시는 버전과 운영체제, 브라우저를 알려주시면 감사하겠습니다.
저는 맥 환경이고 1.6.8 버전에서 크롬과 파이어폭스, 사파리는 이상없이 동작합니다.

**Comment by hangum** [comment]
https://github.com/hangum/TadpoleForDBTools/commit/f92ae2292c6dfe137ad54907f32ebdb393575a41

**Comment by uyu423** [comment]
빠른 적용에 감사드립니다.
Tadpole DB Hub Version 1.6.8 SR Build(R0)을 사용 중이며
AWS EC2 Ubuntu 14.04에 올려놓은 상태입니다.
사용한 브라우저는 Chrome이며 Explorer에서도 같은 현상이 나타나네요.
이번에 로그아웃시 다른 링크가 또 뜨네요. 민감한 url 이니 페이스북 메시지 드리겠습니다.

**Comment by hangum** [comment]
네 감사합니다. 
호출된  uri로 넘어가도록 수정했습니다.
