### ISSUE TITLE
사소한 오브젝트 탐색기 버그

### ISSUE THREAD

**Issue by uyu423** [hangum/TadpoleForDBTools#709]
![image](https://cloud.githubusercontent.com/assets/8033320/12637334/af5388b8-c5d7-11e5-827f-8fc33ca3e4e8.png)

사소한 버그일 수도 있지만 은근히 사용하는데 불편함이 있어 등록합니다.

오브젝트 탐색기에서 뷰 목록 이름에 대해 오름차순/내림차순이 제대로 동작하지 않습니다.

**Comment by hangum** [comment]
테이블 이외의 오브젝트에서 정렬기능을 지원하지 않고 있는데요. 
전체 오브젝트에서 추가 하도록 하겠습니다.

**Comment by hangum** [comment]
정렬 되도록 수정하였습니다. 
view는 오브젝트를 수정하였는데, 필터 코드가 리팩토링되지 않았네요.
