### ISSUE TITLE
Function 9 (F9) Key를 눌렀을때 아이콘들이 사라집니다.

### ISSUE THREAD

**Issue by SeWoongPark** [hangum/TadpoleForDBTools#720]
![image](https://cloud.githubusercontent.com/assets/7866865/13911671/fbcb0ff4-ef76-11e5-88f2-cb474412f4a1.png)

쿼리 실행시 버릇처럼 누르던 F9 Key를 눌렀을때 위와 같은 문제가 발생 합니다. 

버그가 맞는지 아님 원래 그런것인지??

**Comment by hangum** [comment]
안녕하세요. 
저는 
실행환경 : 독립실행환경
운영체제 : 맥
브라우저 : 크롬으로 테스트했을 경우에는 재현되지 않아서 뭐라 말씀 드리기 어려운데요. 

사용하고 계신 환경을 위처럼 알려 주세요.
에디터에 위치 시키고 F9를 누르셨는지요?
사용하고 계신 툴에서는 F9가 쿼리 실행이신가요?

**Comment by hangum** [comment]
올챙이는 원도우, 리눅스의 경우 Ctrl + Shift + L 을 누르시면 단축 목록이 나옵니다. 
대표적인 단축키는 
- 쿼리실행 Ctrl + 엔터
- 쿼리플랜 Ctrl + E
- 커서가 테이블 명에 있을때 Ctrl + I  테이블 명 쿼리
- 커서가 테이블 명에 있을때 F4 테이블 정보 

등이 있습니다. F9 단축키도 쿼리 실행으로 추가해 놓을게요.

**Comment by SeWoongPark** [comment]
환경은 Windows 10 환경에 Browser는 Chrome 입니다. 

무심결에 F9를 눌렀더니 아이콘이 없어 지더군요. 단축키 추가로 막으면 해당 문제는 사라질듯 합니다. 

감사합니다.

**Comment by hangum** [comment]
@SeWoongPark  windows 10 에서 크롬으로  테스트 해봤는데요. 
저는 문제가 재현되지 않았어요. 
올챙이 기능에서 이미지 빠지거나 색 반전되는 기능들은 있을 수 없구요. 

그래서, 사용하고 계신 크롬의 확장(익스텐션) 플러그인 중에 css관련 을 쓰시는지요?

**Comment by SeWoongPark** [comment]
@hangum 제가 사용하고 있는 익스텐션은 구글 문서 도구들... 그리고 네이버 플레이어,Pig Toolbox (Super Gestures) 이정도 입니다. 이게 css에 영향이 있을지는 모르겠네요..

**Comment by SeWoongPark** [comment]
@hangum 방금 Pig Toolbox (Super Gestures) <== 이것 삭제 하고 해봤더니 반전 되지 않네요 css에 영향이 있었던거 같습니다.

**Comment by hangum** [comment]
@SeWoongPark  감사합니다. 
다른 툴의 단축키도 올챙이에 반영해 놔야겠네요. 

사용하고 계신 툴은 어느 것이세요?

**Comment by SeWoongPark** [comment]
@hangum ORANGE FOR ORACLE 입니다. 제가 알기론 My sql Front도 F9 KEY를 이용하는걸로 알고 있습니다. 

감사합니다.

**Comment by hangum** [comment]
네, 단축키를 맵핑할 수있게 하거나 중복으로 사용할 수 있도록 기능을 개선해 보겠습니다. 
감사합니다.

**Comment by hangum** [comment]
F5, F9도 쿼리 실행되도록 단축키에 추가했습니다. 
사용자 정의 단축키 기능은 다음 버전에 반영해야겠네요. 

감사합니다. 

<img width="280" alt="2016-03-21 6 32 30" src="https://cloud.githubusercontent.com/assets/1335915/13914682/523b970c-ef93-11e5-8178-f229fcff194e.png">
