### ISSUE TITLE
개인사용자 환경설정-언어 변경 

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#721]
개인사용자의 경우 ... 별도의 로그인 화면이 없기 때문에.. 로그인 화면에서 설정할 수 있는 언어 설정을 따로 할 수가 없네요.. 맨 처음에.. 한글로 사용했으면.. 계속 한글로 사용해야 합니다. 
사용자 설정이나 환경 설정에 .. 있으면 좋을 것 같아요.

**Comment by hangum** [comment]
엇, 그러네요. 
프리퍼런스의 일반설정 -> 언어 를 추가하도록 하겠습니다.

**Comment by hangum** [comment]
로케일 수정후 다음 로그인 혹은 화면 전체 리프레쉬(F5) 후 부터 로케일이 반영됩니다. 

<img width="648" alt="2016-03-22 11 33 51" src="https://cloud.githubusercontent.com/assets/1335915/13940660/dab17c5c-f022-11e5-8623-df0998659e95.png">
