### ISSUE TITLE
problem with my user

### ISSUE THREAD

**Issue by avallfox** [hangum/TadpoleForDBTools#722]
Could you restore the Authenticator future for "alex.vall.mainou@gmail.com" ??  It is not working and i cannot login.
Thanks

**Comment by avallfox** [comment]
The "find password" future is not working.
Google Authenticator is not working also.

**Comment by avallfox** [comment]
QTP is not working... I cannot login with "alex.vall.mainou@gmail.com"
¿Could you delete the account o send me an email with link to fix the problem?
Thx

**Comment by hangum** [comment]
- Can you use tadpoledb.com?
- alex.vall.mainou@gmail.com account has been alive again.
-- Email is well.
- OPT is checkout.

**Comment by avallfox** [comment]
Now its working fine ... !!!
Great Job .. !
Issue fixed !!

**Comment by hangum** [comment]
@avallfox  any help you?
Do you know? you can download TadpoleDBHub.
https://sourceforge.net/projects/tadpoledbhub/files/1.7.x/1.7.0/

Good day.
