### ISSUE TITLE
PostgreSQL 트리거 생성오류

### ISSUE THREAD

**Issue by sunghoonchung** [hangum/TadpoleForDBTools#723]
PostgreSQL 9.5에서 트리거 생성시 오류가 발생됩니다.
동일한 트리거문을 pgAdmin에서 실행하면 정상적으로 처리됩니다.
아마 특수기호 때문에 발생되는 오류이지 않나 싶습니다.

CREATE OR REPLACE FUNCTION TG_INSERT_TEST_TABLE()
RETURNS TRIGGER AS $BODY$
BEGIN
    IF ( NEW.BASE_DATE >= '20160301' AND
         NEW.BASE_DATE < '20160401' ) THEN
        INSERT INTO PT201603_TEST_TABLE VALUES (NEW.*);
    ELSIF ( NEW.BASE_DATE >= '20160401' AND
            NEW.BASE_DATE < '20160501' ) THEN
        INSERT INTO PT201604_TEST_TABLE VALUES (NEW.*);
    ELSE
        RAISE EXCEPTION 'Date out of range.  Fix the TG_INSERT_TEST_TABLE() function!';
    END IF;
    RETURN NULL;
END;
$BODY$
LANGUAGE plpgsql;

==[ 에러 메시지 ]============
- SQL 상태 코드: 42601
- SQL 에러 코드: 0
- 메시지 : ERROR: unterminated dollar-quoted string at or near "$BODY$
LANGUAGE plpgsql"
  Position: 1

**Comment by hangum** [comment]
안녕하세요.

올챙이에서는 트리거, 프로시저, 펑션등은 생성하는 에디터가 별도로 존재합니다.
<img width="372" alt="trigger_create" src="https://cloud.githubusercontent.com/assets/1335915/14036763/d8995d40-f27f-11e5-9541-862e9864d4b3.png">

일반 쿼리 창에서 실행하실때는 프로시저 전체를 블럭 설정하시고 실행하시면 실행 되시겠습니다. 
<img width="543" alt="trigger" src="https://cloud.githubusercontent.com/assets/1335915/14036815/46f49c8c-f280-11e5-8b26-cd6fd65d1eaa.png">

혹시, 안되시면 관련 스크립트를 보내 주시면 좀더 검토해 보겠습니다.

**Comment by sunghoonchung** [comment]
와우.. 빠른 답변 감사합니다. 확인해보고 결과 공유하겠습니다.

**Comment by hangum** [comment]
@sunghoonchung  네.  개선점이나 버그 있으시면 언제든 환영합니다 .

**Comment by hangum** [comment]
v1.7.1 버전에는 오브젝트를 컴파일 에디터 여는 엑션을 툴바에 추가했습니다 .

![objectcompile](https://cloud.githubusercontent.com/assets/1335915/14235410/74ec5ce6-fa38-11e5-84f4-fa2fc29be124.png)

**Comment by hangum** [comment]
사용하시면서 에러나면 이야기 해주십시오.
