### ISSUE TITLE
지역화 이슈정리

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#724]
- 지역화 관련 이슈가 있으면 여기에 정리해 봐요.  저를 맨션해서 이슈를 달아주시면 볼게요.

- 처음 작성했던 영문 명을 보고 싶을때
깃허브 1.7.0 브렌치에서 검색해서 사용했습니다. 
![search](https://cloud.githubusercontent.com/assets/1335915/14063216/d615673e-f401-11e5-9b12-8b7b18b48fdf.png)
- 명사등은 일반적으로 하나를 만들었습니다.  예를 들어 '확인','에러', '경고' 등은 하나를 만들었습니다.
그렇지 않는 아이들은 클래스명 뒤에 숫자가 붙어 있을거에요. 
- MessageDialog 를 사용할때는 다음을 사용했어요. 
1) 데이터 값 검증 오류는 경고를 보여 주도록 했습니다. 예를 들어이름이 공백입니다. 
MessageDialog.openWarning(null, Messages.get().Warning, "이름이 공백입니다.");
2) 에러면 openError를 사용했습니다.

**Comment by iamsunhan** [comment]
SystemAdminWizardUseType_7

* 다른 사용자와 함께 올챙이를 사용 할때 선택하십시오.
  Next 버튼을 눌러 시스템 어드민을 입력해야합니다.

  Next  버튼을 눌러.. 시스템 어드민 정보를 입력하는 건가요? 아니면... 어드민으로 로그인을 해야 하는건가요? 이유는 왜 그런건지.. 알고 싶습니당.

**Comment by iamsunhan** [comment]
AboutAction_2

En: Tadpole DB Hub - To flow Project  (1.0.0-2013.08.04.000-100)
Ko: Tadpole DB Hub - 흘러가기 프로젝트  (1.0.0-2013.08.04.000-100)

**Comment by iamsunhan** [comment]
ApplicationActionBarAdvisor_1

En: &Manage
Ko: 관리

어떤 내용들을 관리할 수 있는 메뉴인가요?

**Comment by iamsunhan** [comment]
ApplicationWorkbenchWindowAdvisor_2

관리자에게 문의하여 주십시오.(adi.tadpole@gmail.com)

**Comment by iamsunhan** [comment]
한국명이 '올챙이' 인가요? '테드폴' 인가요?

**Comment by iamsunhan** [comment]
BugIssueAction_0 의 '이슈나 버그 등록' 과.. BugIssueAction_1 의 '이슈나 버그 등록'과는 어떻게 다른가요?

**Comment by hangum** [comment]
아움. 한글은 올챙이로 해야겠어요.

**Comment by hangum** [comment]
아바웃 페이지에들어가는 글로 어드민 소개 글이에요.

**Comment by hangum** [comment]
하나는 타이틀이고 하나는 툴팁인데요. 지금은 하나로 쓰고있어요.  두개를 하나로 만들어 주세요

**Comment by iamsunhan** [comment]
LoginDialog_10

Please email conform message to system 
시스템이 보낸 이메일을 확인해 주세요

**Comment by iamsunhan** [comment]
LoginDialog_12

Login as Manager
메니저로 로그인

**Comment by iamsunhan** [comment]
LoginDialog_17

Please input the confirmation key sent by the email.
이메일로 보낸 확인 키를 입력하여 주십시오.

**Comment by iamsunhan** [comment]
LoginDialog_22 '접속 가능한 IP'　 와 LoginDialog_23 '로그인 IP' 는 다른 의미인가요?

**Comment by iamsunhan** [comment]
LoginDialog_23, LoginDialog_26 처럼 내용이 동일한 아이들은 하나로 합치면 안되나용? 소스 내에서도?

**Comment by iamsunhan** [comment]
LoginDialog_6

initialize user
초기 사용자는

**Comment by iamsunhan** [comment]
LoginDialog_7
regist email
확인

**Comment by iamsunhan** [comment]
LoginDialog_9

En: Remember
Kr: 정보 기억

**Comment by iamsunhan** [comment]
NewVersionViewDialog_0

새로운 버전이 나왔습니다. 사용해 보세요.

**Comment by iamsunhan** [comment]
NewVersionViewDialog_7

Information URL
정보 URL

어떤 정보 URL 인지 확인부탁드립니다.

**Comment by iamsunhan** [comment]
다음과 같이 진행되고 있어요.. 한글도 일단 좀 수정했어요.. 근데 이건..개인차가 있을 수 있어서.. 나중에 커밋 전에 .. 의견 공유가 필요한 것 같아요.. 

- 명령형 --> 청유형으로 변경 
  '입력하십시오.' --> '입력해 주세요.'

- 올챙이 --> 테드폴

- 'XX정보가 공백입니다.' --> 'XX를 입력해 주세요.'

- 패스워드, 암호, 비밀번호 --> 비밀번호로 통일

**Comment by iamsunhan** [comment]
AbstractShortCutDialog_22 

En: Remove Line
Kr: 라인 지우기

 
AbstractShortCutDialog_*

**Comment by iamsunhan** [comment]
LoginDialog_20

Please input the email key.
이메일 키를 입력하여 주십시오.

이메일 키.. 라는게 어떤건가요? 이메일로 보낸 인증키..같은건가요?

**Comment by iamsunhan** [comment]
LoginDialog_22

	Allow ip is 
	가능한 아이피는

**Comment by hangum** [comment]
사용자 가입하면 가입한 이메일로 인증키를 보내요.  다음 로그인할때 그 키로 인증해야 하구요. 

이 과정은 어드민이 smtp정보를 넣었을때만 작동합니다.

**Comment by hangum** [comment]
어드민이 사용자가 로그인 가능한 ip를 지정 할수 있는데요. 가능한 ip는 ? 이런 메시지 에요.

**Comment by iamsunhan** [comment]
움... 결국 올챙이에 접속 가능한 아이피들이나 대역대를 지정하는 거죠?

**Comment by hangum** [comment]
네네

**Comment by iamsunhan** [comment]
NewVersionViewDialog_DoesnotCheck

Does not check for updates.
업데이트를 확인하지 않습니다.

**Comment by iamsunhan** [comment]
SelectPerspectiveDialog_5

Select perspective
권한 화면 모음 선택

**Comment by iamsunhan** [comment]
AdminUserListComposite_8

허용유무
Approval 

뭐에 대한 허용 유무인가요?

**Comment by iamsunhan** [comment]
움... 어드민 리스트 매뉴. ..항목 .설명이 좀 필요할 것 같아요..  매뉴얼에도 없는 것 같아서.. 
영문 기준.. 
Is regist DB
Approval
User Confirm
User Delete
각 어떤 의미와 기능인지.. 설명 부탁드립니다.

**Comment by iamsunhan** [comment]
NewUserDialog_31

Has been registered. Sending a request key by e-mail.
Please login.
등록하였습니다. 이메일로 요청키를 보냈습니다.
로그인하여 주십시오. 

신규 사용자 등록용 메시지 같은데...  요청키..가 어떤건가요??? 위에 나온..확인키..들과는 다른건가요?

**Comment by iamsunhan** [comment]
관리자(Manager)와.. 어드민(Administrator)가 혼용되고 있는 것 같아서요....... 의미가 다르면 .. 확실히 구분을..아니면 하나로 통일을..하는게 필요할 것 같습니다.

**Comment by iamsunhan** [comment]
SendMessageDialog_18

user cancle action
사용자 취소 액션

**Comment by iamsunhan** [comment]
UserLoginHistoryDialog_8

Please input the email.
이메일을 입력해 주십시오.

**Comment by iamsunhan** [comment]
CheckNumberString

 must be number. Please check.  
 숫자이어야 합니다. 확인하여 주십시오.

**Comment by iamsunhan** [comment]
ResourceSaveDialog_10

Does not support REST API.
REST API 를 지원하지 않습니다.

REST API 가 전체가 지원 안된다는 얘기인가요? 아니면 특정 디비가?

**Comment by iamsunhan** [comment]
ResourceSaveDialog_11

API URL Information
API URL 정보


이건 URL 만 나오는건가요? 아니면. .. 다른 정보도 함께 표시 되는건가요?

**Comment by iamsunhan** [comment]
CsvToRDBImportDialog_16

SQL Statement / Result Message
SQL 문

이거 어떤 뜻인가요?

**Comment by iamsunhan** [comment]
CsvToRDBImportDialog_btnCheckButton_text

Check Button
Check Button


??????

**Comment by iamsunhan** [comment]
CsvToRDBImportDialog_btnCopyNew_text

Copy && New
Copy && New

?????

**Comment by iamsunhan** [comment]
CsvToRDBImportDialog_btnSaveLog_text

Save Log
저장 로그

저장로그..라는게.. 저장된 로그인가요. 아니면 로그를 저장하라는 뜻인가요?
영문이랑 한글이랑 뜻이 ... ..

**Comment by iamsunhan** [comment]
날짜 표기 되는거요..... 프로젝트 릴리즈일자...나.. 사용자 생성 일자... 디비 등록일자..이런거.. 
선택언어가 영어이면 외국 형식으로 월/일/년 (미국식) ... 일/월/년(유럽식)으로 변경하는게 좋을 것 같습니다.

**Comment by iamsunhan** [comment]
설치 후 맨 처음에 나오는 ... 이용 약관 화면.. 
한글로만 나오고..영어로는 선택이 안되네요..

**Comment by hangum** [comment]
@iamsunhan  영문 드릴까요?

**Comment by iamsunhan** [comment]
DBOthresConfigDialog_3

DB to the lock state
DB 잠금 상태로 만들기

어떤 의미 인가요?????

**Comment by iamsunhan** [comment]
TransactionConnectionListEditor_0 / TransactionConnectionListEditor_1

 General Connection Pool / Transaction Connection 이라는 말이 실제 사용하는 말인가요? 구글링해도... 안나오는 것 같아서요....

**Comment by iamsunhan** [comment]
MongodbResultComposite_10

Please select the data.
데이터를 선택해 주십시오.


어떤 데이터를 선택하는 거예요?

**Comment by iamsunhan** [comment]
MongoDBPreferencePage_2

Find Page

이건 어떤 것을 찾는 거예요?

**Comment by iamsunhan** [comment]
이 .. 지역화 작업을 하다보니.. 몇 가지 느낀게 있는데... 

- 메시지 파일이 .. 각 디렉토리에 패키지별로 떨어져 있어서...  어찌 보면...  해당 패키지 관련 메시지들만 있어서..좋은 것 같기는 하지만...  동일한 UI 메시지 (OK, Confirm, ...... ) 이 각 메시지 파일별로 반복 되고 있어요... 그래서 불필요한 작업들이 많거나, 일관성이 깨지기도 합니다... 예를 들어 어떤 곳은 Cancel 인데.. 어떤 곳은 CANCEL 로 표시 되거나... 동일한 한국어 문장에 대해 .. 영문 번역이 각각 다른 경우...  .. 

- 사용자 UI 용 메시지와 클래스들에서 발생하는 에러 메시지들이 섞여 있고..구분하기도 어려워요..  에러 메시지의 경우... 해당 에러에 대한 정확한 내역이나 디렉션이 포함 되어야 하고... Definition 에서도 이게 .. 에러 메시지인지.. 구분할 수 있는게 좋을 것 같다는 생각입니다... 뭐.. prefix 를 ERR_ ....   / FATAL_ ....  / WARN_ ... 등 에러 등급별로 ..따로 붙고... 뭐 .. 각 메시지별..원인이나... 사용자가 할 수 있는 조치들이 같이 정의 되고 ... 사용자에게 보여지면 좋을 것 같아요.. 

- 동일한 메시지가 반복 되는 경우도 많습니다.  용도가 다른건지..는 잘 모르겠는데.... 한 메시지 파일내에 (예를들면..) Confirm 이 여러번 보인다든지.. 하는 일이 있어요... 만약 용도가 다른거라면.. (어떤거는 버튼용..어떤거는 툴팁용... 등) .. 이것도 하나로 통일하는게...  나중을 위해서도 좋을 것 같다는 생각이 듭니다... 

- 메시지의 Definition을 보고.. 메시지의 정체를 파악할 수 있었으면 좋겠어요... 현재는 LayOutAction_0 이런식이여서.. 전혀 어떤 내용인지 파악이 안되는데다가....  만약 메시지 정리로 중간에 숫자가 없어지면... 정말로 의미 없는 definition 이 될 것 같습니다..

**Comment by iamsunhan** [comment]
아.... 이런 .. 메시지 파일도...변화가 많네요.... 새로 다운 받은거... 특히.. 약관...이랑 이런거... ㅎㅎㅎㅎㅎ

**Comment by iamsunhan** [comment]
번역하면서..잘 몰라서 찾아봤더니..... 현재 테드폴 에서는 ... REST랑.. RESTful 이랑 좀 혼용 되서 쓰이는 것 같아요.. REST API / RESTful Service 이렇게 .. 정의하는게 맞는거 같은..느낌적인 느낌을..구글링에서....

**Comment by iamsunhan** [comment]
TadpoleTableComposite_driverMsg


%s driver doesn't found.

Please upload driver to the system admin.
Menu->Admin->JDBC Driver Manager.

%s

----

%s driver가 발견되지 않았습니다.

시스템 어드민에게 드라이버를 업로드 해주세요.
메뉴->Admin->JDBC Driver Manager.

%s

----------
 이거..잘 이해가 안되는데... 드라이버가 없으니.. 등록을 하라는 얘긴가요? 시스템관리자를 통해서??  즉... 드라이버를 시스템 어드민에게 주면... 그 사람이 등록해 줄꺼다? 이런건가요? 아니면.. 저 ..매뉴로 가서... 본인이 등록 하라는 건가요?

**Comment by hangum** [comment]
드라이버는 시스템 관리지민 업로드 힐수 있어요.

**Comment by iamsunhan** [comment]
TadpoleEditor_12

do save error
do save error

???????

**Comment by iamsunhan** [comment]
TadpoleTableComposite_driverMsg 관련.. 

그렇다면.. 일반 사용자들은 .. 적당한 드라이버가 없으니.. 관리자에게 요청 후 사용하라는 메시지만 띄우는게 좋지 않을까요.... 아래 매뉴도 있고.. 한국어 설명 또한 명확하지가 않아서...

**Comment by iamsunhan** [comment]
TadpoleEditor_9

new save error
new save error

?????

**Comment by iamsunhan** [comment]
움.. 지금  일단.. 메시지파일들 변경은 끝낸 상태고...  화면 하나씩 보고.. 기능 확인하면서.. 제대로 .. 메시지들이 옮겨진건지... 확인하고 있어요..  

- 한글 --> 영어 직역 ... 아니고.. 좀 더 부드럽게 변경할 수 있는 것들은.. 영어식 표현으로 바꿨어요.. 구글 같은데서... 외국애들이 많이 쓰는 표현들로.... 뭐  Homepage --> Website   /  Personal --> Individual / Create ERD --> New ERD / Input OTP Code --> Enter OTP 등.... ...  그리고... 제가 베이스 지식이 없는 것들...Google Analysis / NoSQL 계열.. / Amazon 등... 은 소프트웨어에서 나오는 메시지들을 이미지로 구글링해서 .. 나오는 것들과 비슷한 것들이랑 맞추려고 최대한 노력했어요.... 이런 것들요.. 이런 것들 찾느라고 시간이 좀 걸렸어요...  흡흡흡.. 

- 기존 메시지 파일에서.. 메뉴 같은 것들 중에.... 외국애들도 ... 안쓰는 말이고... 저도 잘 모르겠는 것들은.. 기능을 눌러보면서..   고치긴 했는데.. 이건.. 나중에 다시 점검이 필요할 것 같아요... 
- 한글 오타가 좀 많이서 한글 파일들도 수정을 했어요.. 
- 한글 버전 메뉴 / 메시지가 바뀐 것들도 있어요.. 
- 한글화가 이미 진행된 단어들은 ...가능하면 한글로 표시하려고 했어요...  리프레쉬 --> 새로고침 / 임포트 --> 가져오기  등.. 
- 한가지 의미인데 .. 여러개로 나뉘어 있는 것들은 통일을 했어요... Delimiter, Separator, 구분자, 분리자...

**Comment by iamsunhan** [comment]
NewUserDialog_31

등록하였습니다. 이메일로 요청키를 보냈습니다.
로그인하여 주십시오. 

Thank you for registering.
We've sent a confirmation key in the registration e-mail.
Please enter at the time of login.

----
음.. 이런게 ..뭐랄까 .. 상당히.. 사용자 입장에서 .. 무슨 말하는지 모를 메시지..라고나 할까요...
(사용자 등록으로 보이는게..)등록이 완료 되었고....  (뭐에 쓰이는지 모를)요청키(?)도 보냈다고..하는데...
그냥 갑자기.. "로그인" 하라고... 

저.. 보낸 요청키(?) 라는 것을 이용해서 로그인 해야 하는 건가요?
요청키..랑 확인키..는 어떻게 다른거예요??

**Comment by iamsunhan** [comment]
흑흑.. 어떤거는 메시지파일에 ... 내용이 있고.. 어떤거는 ... 자바 파일에 박혀 있어요 ㅠㅠ.. 
		lblLogDir.setText("Log dir");
		 이런거요.. ㅠㅠ

**Comment by iamsunhan** [comment]
제가 알기로는...... 
Settings / Configu  ... 시스템에 전반적인 설정 사항 
Preferences  ...  개인적인 취향을 담은 설정.. (폰트,, 창배열..등)

으로 알고 있어요.. 구분이 없어보여서.... ㅎㅎ
