### ISSUE TITLE
사용 중 발견한 버그 목록

### ISSUE THREAD

**Issue by lahuman** [hangum/TadpoleForDBTools#726]
1. 오라클 힌트가 제외되고 쿼리가 실행됩니다. (1.6.6 버젼 기준)

2. SQL 템플릿에서 공통 을 삭제 할 실제 삭제 되었으나, 화면을 재로딩 할때 까지 안없어짐(1.7 기준)

이상입니다.

**Comment by hangum** [comment]
억... 
빠르게 수정하겠습니다.
