### ISSUE TITLE
올챙이 로그아웃 후 메인화면이 뜨는 문제(로그인 창이 안 뜸)

### ISSUE THREAD

**Issue by hunylee** [hangum/TadpoleForDBTools#728]
첫번째 사진은 종료 버튼 누른 후 종료/로그아웃/취소가 있음. 
<img width="1259" alt="2016-04-01 3 40 11" src="https://cloud.githubusercontent.com/assets/1106559/14199578/9d11deae-f820-11e5-839f-8e01a47d6303.png">

두번째 사진은 로그아웃 후 팝업창(페이지유지/페이지 나가기) 페이지 나가기 누르면 로그인 아닌 올챙이 메인화면으로 돌아감
<img width="1256" alt="2016-04-01 3 40 24" src="https://cloud.githubusercontent.com/assets/1106559/14199577/9d1165e6-f820-11e5-9819-48f5fdf3ff6b.png">

**Comment by hangum** [comment]
저는 의도대로 잘 동작하는데 어떻게 봐야할지 모르겠네요. 
동영상 올려주실수 있으면 디버깅하는데 도움이 많이 될듯합니다.
