### ISSUE TITLE
블럭을 지정하여 쿼리 실행시 맨끝에 위치한 세미콜론을 자동으로 제거하는 기능

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#729]
블럭을 지정하여 쿼리 실행시 맨끝에 위치한 세미콜론을 자동으로 제거하는 기능이 유용할 수도 있지만 DDL을 실행하는 경우나 pl/sql 블럭을 실행할 경우 맨 마지막의 세미콜론도 유요한 경우가 있습니다.

;;  세미콜론을 두개 연속으로 찍어서 사용하면 문제가 없긴 합니다...^^;

프로시져나, 트리거 수정창이 별도로 마련되어 있긴하나 sql에디터에서 예전방식으로 블럭지정 후 ddl을 수행할 경우 오류가 발생하여 오브젝트가 invalid상태로 생성이 됩니다.

**Comment by hangum** [comment]
- Oracle, Tibero의 경우 ; 문자를 제거하지 않도록 수정했습니다.
