### ISSUE TITLE
SQL 에디터가 열릴때 ..

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#732]
SQL에디터가 열릴때 자동저장되었던 내용이 에디터에 다시 표시될때 새로 추가된 내용과 자동저장되었다 복구된 내용이 구분되지 않아서 혼란스러울 때가 있습니다.

자동 복구되어 로딩된 내용과 새로 추가된 내용을 구분할 수 있도록 하면 좋을듯 합니다.

예를 들어 복구된 내용의 하단에

---------------------// 자동복구 영역 //----------------------

이런식으로 영역을 표시해 주면 좋겠네요.

추가로 저장된 리소스는 다음번 자동복구시에 표시되지 않도록 사용자가 명시적으로 저장을 했으면 자동저장 캐쉬를 비워주도록 해서 다음번 오픈시 에디터장이 깨끗하게 열리면 좋을듯 합니다.

**Comment by hangum** [comment]
반영하였습니다. 

![Uploading 스크린샷 2016-04-03 오후 7.12.55.png…]()
