### ISSUE TITLE
오라클의 제약조건 리스트가 표시되지 않습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#738]
fk, check 제약조건등이 표시되지 않습니다.

**Comment by hangum** [comment]
@jeongjaehong  이거 수정됬죠?

**Comment by jeongjaehong** [comment]
테이블뷰의 Sub뷰 형태로 UI 를 조정하여 제약조건 탭에 check, not null, fk등의 제약조건에 대한 내용을 표시하도록 수정되었습니다.

[https://github.com/hangum/TadpoleForDBTools/pull/759](https://github.com/hangum/TadpoleForDBTools/pull/759)
