### ISSUE TITLE
에디터창에서 DESC 명령어가 수행이 안됨

### ISSUE THREAD

**Issue by lunar999** [hangum/TadpoleForDBTools#739]
DESC 테이블명; 

해당 쿼리가 실행이 되지 않네요

티베로 버전은 5 입니다

==[ 에러 메시지 ]============
- SQL 상태 코드: JDBC-15146:ERRPS
- SQL 에러 코드: -15146
- 메시지 : JDBC-15146:PSM compilation error.

**Comment by hangum** [comment]
확인해 보겠습니다

**Comment by hangum** [comment]
이것도 다른 툴에서 되는지 확인 부탁드려요. 
메시지는 디비에서 주는 메시지라서요.

**Comment by lunar999** [comment]
SQLGate에서는 정상 동작합니다.

**Comment by hangum** [comment]
네.  코드 확인 해볼게요.

**Comment by hangum** [comment]
티베로 기술 지원에 문의하였습니다.

**Comment by hangum** [comment]
올챙이에서는 에디터에서 F4키를 누르시면 테이블 목록 팝업이 표시 합니다. 
이것을 사용하여 주십시오. 


<img width="505" alt="table information" src="https://cloud.githubusercontent.com/assets/1335915/14347246/0151d0b6-fcf1-11e5-9b2e-a716bab2caff.png">

**Comment by hangum** [comment]
에디터에서 desc명령이 먹도록 수정했습니다. 
desc 테이블 명을 을 입력하면 위의 다이얼로그가 나옵니다.
