### ISSUE TITLE
오브젝트 탐색기 - Table 변경 건

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#742]
오브젝트 탐색기의 테이블 변경을 다음과 같이 했으면 좋겠습니다.
현재 UI는 Index, trigger가 흩어져 있어서 보기가 직관적이지 않습니다.
그래서 테이블 아래 그림과 같이 정보를 모으면 UI가 좀더 직관적으로 변하여 좋을듯합니다. 
지금 보여주지 않는 참조키 탭도 추가하구요. 
![object-table](https://cloud.githubusercontent.com/assets/1335915/14360558/f06f4b20-fd31-11e5-8b57-58bad359098d.png)

@jeongjaehong  이렇게 하면 될까? 뭐가 추가되면 좋을까요?

**Comment by jeongjaehong** [comment]
Foreign Keys라는 표현보다는 제약조건(Constraints)으로 표현하면 좋을거 같습니다. ^^; 
Not null 이나 기타 제약조건도 같이 표시하면 좋을거 같네요~

**Comment by hangum** [comment]
@jeongjaehong 형 오늘 시간되면 마무리좀 해줘요. 

![table_column](https://cloud.githubusercontent.com/assets/1335915/14589936/3a078bfe-0529-11e6-90fb-cbcd43dd7cdd.png)

**Comment by hangum** [comment]
- SQLite
-- 인덱스 탭에가면 상세 정보가 나오지 않는데, 원래 없을까요?
<img width="359" alt="sqlite_index" src="https://cloud.githubusercontent.com/assets/1335915/14604555/2a1be510-05af-11e6-801b-2d5cc1b944c9.png">
-- 제약조건 탭에가면 에러 쿼리(tableConstraintsList)가 정의 되어 있지 않습니다. 
-- 원래 없어야 할까요?
--

**Comment by jeongjaehong** [comment]
SQLite의 경우에는 해당 테이블을 정의하는 DDL을 추출해서  스크립트 내에 NOT NULL, CHECK등과 같은 명칭으로 파싱을 해서 표시해야 해서 제약조건 UI 형태로 표현하기에 난해합니다.  ㅡㅡ;

필요하다면 하나의 단일 TextView를 통해서 해당 Table의 Create 스크립트를 보여주는 정도로 UI를 이원하 하여 처리해 줘야 할듯 합니다.

**Comment by hangum** [comment]
@jeongjaehong  그럼 sqlite는 없애 버려야 할까요?

**Comment by hangum** [comment]
인덱스 이름 눌렀을 경우 컬럼 최신으로 갱신되지 않는 오류수정했어요. 

- sqlite 제약조건 탭없앴어요. 
- pgsql 제약조건 에러 나요. 부자형 고쳐줘요. 
- cubrid 는 제가 볼게요.
