### ISSUE TITLE
쿼리 결과 조회 후 컬럼보기에서 메시지창이 표시됩니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#745]
쿼리결과 에서 컬럼보기 기능을 이용하여 Blob컬럼의 이미지 정보를 조회후 창을 닫으면 열을 선택하라는 메시지 창이 한번더 표시됩니다.

컬럼의 데이터 타입이 문자이거나 숫자일때는 표시되지 않습니다.

![capture 11](https://cloud.githubusercontent.com/assets/859932/14418713/bb9dc0da-fffb-11e5-8037-bd3a6538a060.png)

![capture 12](https://cloud.githubusercontent.com/assets/859932/14418719/c244cb68-fffb-11e5-8f91-a9baf09fbb68.png)

**Comment by hangum** [comment]
확인해볼게요.

**Comment by hangum** [comment]
https://github.com/hangum/TadpoleForDBTools/issues/747 수정하면서 수정했어요.
