### ISSUE TITLE
Query ExecuteViewer의 Ui 에 대해서..

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#746]
핀버튼 옆에는 하나의 버튼만 표시하고 클릭에 따라서 버튼 이미지를 vertical 혹은 horizontal을 의미하는 이미지로 변경해 주면 어떨까요?

![capture 13](https://cloud.githubusercontent.com/assets/859932/14419055/04f46804-fffe-11e5-9108-328ac93e9261.png)

**Comment by hangum** [comment]
우선 고정 버튼을 위로 옮기기가 전체 ux에 맞지 않아요.  요청 상태는 하나만 있고 결과탭만 확장하는 구조입니다. 
그래서 핀버튼이 결과에 있어야 ui가 형성이 될듯해요. 
<img width="1076" alt="resultset" src="https://cloud.githubusercontent.com/assets/1335915/14435128/4b1d8880-0051-11e6-95d1-a1d6ceb95d76.png">

아이콘 이쁘네요. 저거 주세요.

**Comment by jeongjaehong** [comment]
다운로드(Export)기능을 버튼만 놔두고 버튼 클릭시에 Export 포맷 및 옵션을 조정하는 대화상자를 오픈하는 방식으로 바꾸면 하단에도 버튼 배치를 위한 충분한 공간이 확보될듯 합니다. ^^;

그리고 아이콘은 IconFind에서 검색햇던건데..유료 아이콘이네요..ㅡㅡ;
