### ISSUE TITLE
버전 업데이트 기능

### ISSUE THREAD

**Issue by hadesyi** [hangum/TadpoleForDBTools#754]
도움말에 신규버전 확인으로 새버전이 나오면 다운로드 페이지로 링크만 되는데
새로 설치 하면 기존 데이터 베이스 정보가 날아가서 다시 설정 하기가 귀찮습니다.

새로운 버전이 나오면 시스템만 업데이트 되고 다른 유저 환경 정보는 유지가 되면 좋겠습니다.

그럼 다음 버전 기대 하겠습니다.
도움말에 신규버전 확인으로 새버전이 나오면 다운로드 페이지로 링크만 되는데
새로 설치 하면 기존 데이터 베이스 정보가 날아가서 다시 설정 하기가 귀찮습니다.

새로운 버전이 나오면 시스템만 업데이트 되고 다른 유저 환경 정보는 유지가 되면 좋겠습니다.

그럼 다음 버전 기대 하겠습니다.

**Comment by hangum** [comment]
의견 감사합니다.
말씀하시는 기능은 상용버전에 기능을 추가하려고 준비 중에 있습니다. 
너그러운 마음으로 이해부탁드리겠습니다. 

다른 불편사항이나 애로점 버그는 없었는지요?

**Comment by hadesyi** [comment]
쿼리 히스토리 기능 제가 원하는 기능이 있는데 에디터창 하단 요청한쿼리 히스토리에서는 잘작동이 되나 manage-SQL audit 에서는 작동이 안되네요 제가 사용법을 몰라서 그런건지 오라클, 마리아디비 다 안되네요. 윈도우10 64bit  버전은 1.7.1 버전입니다.

**Comment by hangum** [comment]
안녕하세요. 
혹시 1번의 검색 조건에 기간, 수행시간을 입력하실수 있습니다. 
보통 쿼리가 수행시간이 500ms 이하라 검색안되는 쿼리가 많을 수 있어요. 

2번으로 쿼리를 지속적으로 돌려볼수있습니다. 
혹시 계속 문제가 되시면 꼭 리포팅 부탁드려요. 

![sqlaudit](https://cloud.githubusercontent.com/assets/1335915/14624803/d9097b82-0618-11e6-9df0-493f1017d1f9.png)

**Comment by hadesyi** [comment]
수행 시간을 줄이니깐 검색이 되네요 그런데 오해의 소지가 있을거 같습니다. 저는 현재 검색 수행시간이 500까지로 생각을 했습니다. 결색 결과 수행시간이 500밀리 이하라고는 생각을 못했네요. ^^

**Comment by jeongjaehong** [comment]
"수행시간" 보다는 "소요시간(ms)" 로 표기하는게 좋아 보입니다.

**Comment by hangum** [comment]
@hadesyi  @jeongjaehong  의견을 반영해서 다음과 같이 수정했습니다. 
검색일을 기존 7일에서 1일로 줄였고, 레이블을 소요시간(ms)로 수정했고 기존 500ms에서 50ms로 줄였습니다. 그리고 그 뒤에 (이상) 이라는 글을 붙여 이해하기 쉽게 만들고요.
그리드 결과도(2) 기존 초에서 ms로 바꾸어서 검색 조건과 보여지는 값을 일반화 시켰습니다.
감사합니다. 

![sqlaudit](https://cloud.githubusercontent.com/assets/1335915/14634131/90aeb8be-065b-11e6-848c-dc708eff7854.png)
