### ISSUE TITLE
sql문을 application언어로 변경 기능 추가 

### ISSUE THREAD

**Issue by hadesyi** [hangum/TadpoleForDBTools#757]
sql문을 application언어로 변경 에서 mybatis템플릿도 추가해주시면 감사하겠습니다.

**Comment by hangum** [comment]
@hadesyi  
네. 알겠습니다. http://www.mybatis.org/mybatis-3/sqlmap-xml.html 식의 템플릿이면 좋을지요?

**Comment by hadesyi** [comment]
네 그렇게 해주시면 좋겠습니다. ^^

**Comment by jeongjaehong** [comment]
@hadesyi 이렇게 하면 될까요?

![image](https://cloud.githubusercontent.com/assets/859932/14707020/252fa870-07fd-11e6-969c-5bcca10169c8.png)

**Comment by jeongjaehong** [comment]
@hadesyi 이슈는 닫도록 하겠습니다.   

테이블을 선택하고 팝업메뉴를 이용해서 DDL스크립트 생성하는 형식으로 해서 insert, update, delete 맵을 생성하는 기능이 있으면 좋을까요? ^^;

필요하시면 신규 이슈로 등록 바랍니다.

**Comment by hangum** [comment]
@jeongjaehong  수고하셨어요. 
@hadesyi  이슈등록해줘요~~

**Comment by hangum** [comment]
@jeongjaehong  쿼리 문장 분석해서 insert, select, delete, update 자동으로 해줄수 있을듯해요. 
해줘해줘..

**Comment by jeongjaehong** [comment]
insert, update, delete는 별도로 팝업메뉴 만들어서 Create SQLMap ....하위메뉴에 select, insert, update, delete로 만들어도 괞잖을거 같은데....

**Comment by hangum** [comment]
메뉴말고 그냥 쿼리 문장 분석해서 알아서 해줘도 될듯해요

이건 형꺼 이어서 내가 해볼게요

**Comment by hangum** [comment]
@hadesyi  쿼리를 분석해서 select, insert, update, delete 로 나오도록 수정했습니다. 
![mybatis](https://cloud.githubusercontent.com/assets/1335915/14740207/20e2fa9e-08c8-11e6-8a9e-2acf4ca8add8.png)

뭔가 또 필요하신게 있으실까요?

**Comment by jeongjaehong** [comment]
select 결과셋을 ui와 연결하기위한 javascript소스를 생성해 주는 기능도 개발자들 노가다를 많이 줄여주고 업무효율을 높여줄 수 있을것 같습니다.

리얼그리드나, 가우스 그리드, axisj 그리드등...

![capture 23](https://cloud.githubusercontent.com/assets/859932/14781247/5eae57b4-0b1c-11e6-8931-5ebf082d4471.png)
![capture 22](https://cloud.githubusercontent.com/assets/859932/14781248/5eb0dc3c-0b1c-11e6-85c6-ff8e3f259906.png)

**Comment by hangum** [comment]
<img width="853" alt="2016-05-12 1 51 18" src="https://cloud.githubusercontent.com/assets/1335915/15204474/a76a8e30-1848-11e6-9b27-a189fcbc1929.png">
