### ISSUE TITLE
제약조건 뷰와 관련해서 콘솔에 오류로그가 출력됩니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#762]
이런 오류가 발생하는데..아무래도 해당 Action이 생성되지 않은 상태여서 발생하는 오류인듯 합니다.

![image](https://cloud.githubusercontent.com/assets/859932/14707602/8486d1a6-0800-11e6-803a-ff8a2e597fbc.png)

**Comment by hangum** [comment]
어느 디비였어요?
