### ISSUE TITLE
사용자 의견

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#763]
1. oracle jdbc 추가하기 전 DB를 연결하다가 임시저장 -> 등록 후 화면닫기를 하고나서 화면 흐름이 좀 어색합니다. 삭제할때에도 계속 이슈를 뱉어내고. 물론 제가 잘못한 것은 알겠지만.
깔끔하게 끊을 수 있는 방법이 있으면 좋겠어요.
마찬가지로, 입력 다 해놓고 mysql -> oracle로 db를 변경하면 지금까지 입력한 내용이 싹 다 사라지는 부분은 공통 요소는 그대로 두심이 어떨지 싶습니다.
---------------->
동일한 디비이면 입력 후에 그대로 두는데, 디비가 틀리면 디비마다 입력 해야하는 정보가 달라서 놔둘수가 없습니다. 
입력 할때, 디비를 좀더 분명히 알 수 있도록 고민해 보겠습니다. 

2. 제가 가로/세로 휠이 되는 마우스인데요. 검색 결과를 네비게이션 할 때 가로 휠을 돌려도 세로로 스크롤이 됩니다.
그리고, 이것 또한 제 잘못입니다. 
user단위 export 기능이 있을 것이라고 생각했는데, 없군요. 
---------------->
user 단윈 export기능은 어떤 것인지 알려주시면 좋겠습니다.

**Comment by jeongjaehong** [comment]
User단위 익스포트는 로그인한 유저(스키마) 기준으로 소유한 모든 객체(테이블, 뷰, ...)의 스크립트 또는 테이블의 데이터를 익스포트 하는 기능을 얘기하는듯 합니다.

**Comment by hangum** [comment]
1. 번의 경우 jdbc 드라이버가 없는 경우, 데이터베이스 정보를 입력하기 전에 팝업을 띄워서 드라이버를 설정하고 디비 정보를 입력할 수있도록 합니다

**Comment by hangum** [comment]
일단 로그인 다이얼로그는 이걸로 만족해야겠네요. 
그룹타이필 폰트 바꾸거나 하는게 어려울듯해요. 
<img width="534" alt="2016-04-22 4 26 58" src="https://cloud.githubusercontent.com/assets/1335915/14734690/173774a0-08a7-11e6-96a9-dd8b1c2addf4.png">

**Comment by hangum** [comment]
2. 디비 드라이버가 발견되지 않았을 경우 다음과 같은 팝업을 띄워서 드라이버를 입력 받을수 있도록 합니다. 

![drivernotfound](https://cloud.githubusercontent.com/assets/1335915/14740089/37a76a54-08c7-11e6-8e22-328b1bd5e675.png)

**Comment by hangum** [comment]
드라이버는 다음(https://github.com/hangum/TadpoleForDBTools/issues/765)로 이어갑니다.
