### ISSUE TITLE
SQL to Application 소스 만들기 기능 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#767]
SQL을 Application 으로 만들기 기능에 대해서 

- https://www.facebook.com/nilriri/posts/1069654789759986?notif_t=tagged_with_story&notif_id=1461579666894730
- https://www.facebook.com/nilriri/posts/1069656923093106?notif_t=tagged_with_story&notif_id=1461579928396724
- https://www.facebook.com/hangum/posts/1003551219681152?notif_t=like&notif_id=1461579693733638

**Comment by hangum** [comment]
- 헤더와 셈플 5건 만들도록 하였습니다. 
- 제약사항은 에디터에 SELECT 문이 있을 경우에 가능합니다.

**Comment by hangum** [comment]
수고하셨습니다.

**Comment by hangum** [comment]
변수가 꼬리가 꼬리를 뭅니다.

<img width="852" alt="2016-04-30 10 12 51" src="https://cloud.githubusercontent.com/assets/1335915/14933006/3f6d35ca-0ebc-11e6-88f8-b8566014bb74.png">

**Comment by hangum** [comment]
형 프리뷰 위젲 만들어 놨거든요.   거기에 요넘을 응용해서 뿌려주세요. 
@Tomas Jang님이 만들어 주셨어요. 
[index.html.zip](https://github.com/hangum/TadpoleForDBTools/files/243632/index.html.zip)


저는 리얼 그리드를 붙여보겠습니다.

**Comment by jeongjaehong** [comment]
https://github.com/hangum/TadpoleForDBTools/files/243632/index.html.zip  여기 보내주신 템플릿이 이미 적용된 템플릿과 뭐가 다른거에요? ^^;

소스를 뜯어보니...javascript 형식이 좀 다르긴 하네요.. ^^

@thomasJang

**Comment by thomasJang** [comment]
기본 기능도 좀 많이 넣어두고 해서용~ 기왕이면 이 샘플이 도움이 될것 같아 보내드렸었습니다.

**Comment by jeongjaehong** [comment]
네네... @thomasJang 님 감사합니다. ^^;
https://tadpolehub.com/ 에서 해당 미리보기 기능과 스크립트 생성기능 보시고 axisj 커뮤니티에도 좀 홍보 부탁드립니다..

사용자가 늘어가야 자꾸 기능도 개선되고 성능도 좋아지고 할것 같습니다.~

즐거운 하루 되십시오~
