### ISSUE TITLE
올챙이에서 실행되는 모든 쿼리에 해당 쿼리 실행주체를 식별할 수 있는 코드를 삽입하는건 어떨까요?

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#769]
https://www.facebook.com/nilriri/posts/1069656923093106?comment_id=1070767326315399&notif_t=like&notif_id=1461731781643474

음...예를 들어서..

select \* from dept; 라고 실행할때...

select /*\* tadpole7.1.0>sqleditor>paging-2*/ 
- 
  from dept;  

위와 같이 /*\* tadpole7.1.0>sqleditor>paging-2*/   이런 식별코드를 삽입해서..

dbms자체에서 세션에서 현재 실행중인 쿼리를 모니터링 하거나 할때..어떤 경로로 유입되어 실행되는 쿼리인지 식별이 용이하도록...

**Comment by hangum** [comment]
좋아요. 
requestquery 객체에 포함해 주면 될듯해요

**Comment by hangum** [comment]
@jeongjaehong  어떻게 생각하세요?
- 각 디비별로 주식이 문법적으로 용이한지 유무?
- 삽입하는 구문을 어떻게 할것인지?
- 삽입의 범위를 어디까지 할것인지?(예를 들어 올챙이의 테이블 목록 조회, 테이블 선택도 날려야 하는것인지 유무)

**Comment by jeongjaehong** [comment]
고민을 많이 해봐야겠네요..의견수렴도 필요하고..
/*+.....*/   이건 오라클 주석이니..  /**.....*/ 형식이나 /*#.....#*/ 형태로 한다거나 하면 될듯합니다.
Tadpole.{버젼}.{유저아이디}.{클래스-에디터.컴파일.테이블뷰등...}  등 일단 CRUD매트릭스 화면뷰를 어떻게 구성할지 구상해 보고 필요항목이랑 향우 확장성을 고려해서 항목들을 구성해 주면 좋을것같습니다.

**Comment by hangum** [comment]
현재 DBSAFER 연결할때 세션만 유일하면 된다고하네요.

**Comment by hangum** [comment]
v1.7.6 에서는 별도로 되도록 코드를 개선했습니다.
