### ISSUE TITLE
http://tadpoledb.com/ 가입시 발송되는 이메일에 한글이 깨져서 보입니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#770]
그리고 보내는 사람의 메일 주소도 개인 메일주소인듯 한데 올챙이 대표메일 주소로 보내는것이 좋을것 같습니다.

![capture 27](https://cloud.githubusercontent.com/assets/859932/14842519/19501cb2-0c83-11e6-94c6-010dbb052ee1.png)

**Comment by hangum** [comment]
앗.. 이거 수정해놔야겟네요

**Comment by hangum** [comment]
css가 깨지네. 이건 왜그럴까? ㅠㅠ hotmail.com은 잘보여지는데 구글이나 네이버는 깨지네. 

<img width="363" alt="2016-04-29 7 12 14" src="https://cloud.githubusercontent.com/assets/1335915/14903698/f1b6a6d8-0ddd-11e6-8f07-a4d1723090fc.png">
