### ISSUE TITLE
올챙이 에디터에서 SQL 쿼리에서 myBatis 타입 사용할 수 있게 해주세요.

### ISSUE THREAD

**Issue by freepow** [hangum/TadpoleForDBTools#771]
### myBatis
> SELECT *
     FROM BOARD
  WHERE ID = #{ID}

myBatis용 만들어주시면 잘 쓰겠습니다.
감사합니다

^______________^

**Comment by hangum** [comment]
다음버전에서 사용하실수 있도록 하겠습니다.

**Comment by hangum** [comment]
mybatis의 변수가 작업되도록 했습니다.

에디터에서 다음의 쿼리가 변수로 처리되도록 작업되었습니다.
<img width="343" alt="2016-05-10 5 01 45" src="https://cloud.githubusercontent.com/assets/1335915/15126302/590a06ae-166c-11e6-91a8-89a870a0e903.png">

**Comment by hangum** [comment]
${} 는 적용되지 않도록 코드를 막았습니다. 
관련 내용은 다음을 참조하세요.
http://www.hpenterprisesecurity.com/vulncat/ko/vulncat/java/sql_injection_ibatis_data_map.html
