### ISSUE TITLE
타임존 설정

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#781]
디비의 타임존과 어플리케이션 서버의 타임존 설정
엔진디비의 timezone을 utc로 설정
MySQL일 경우 Datetime -> Timestamp로 교체  now() -> utc_timestamp()
자바에서 데이터 저장 및 가져오기시에 Date, Calendar를  utc -> local time zone, local time zone -> utc로 수정

**Comment by jeongjaehong** [comment]
1. 저장(insert, update)할때는 before 트리거를 이용하여 사용자의 timezone정보를 바탕으로 gmt+00:00으로 변환해서 저장한다.

2. 조회(select)할때는 사용자정의함수를 생성하여 사용자정보의 timezone정보를 이용하여 사용자의 시간대에 맞게 변환하여 리턴한다.
 
select uf_convert(u.create_time, user_seq) as create_time 
from user_info u;

참고 : http://stackoverflow.com/questions/805538/in-mysql-caculating-offset-for-a-time-zone

**Comment by jeongjaehong** [comment]
mysql> SELECT CONVERT_TZ(NOW(),'US/Pacific','UTC');
+--------------------------------------+
| CONVERT_TZ(NOW(),'US/Pacific','UTC') |
+--------------------------------------+
| 2012-11-16 20:10:30 |
+--------------------------------------+
1 row in set (0.00 sec)

**Comment by hangum** [comment]
현재까지 상황 정리
- Application 서버와 디비서버의 타임존을 동일하게 UTC로 설정합니다. 
- 어드민 설정에 서버가 사용하는 TimeZone을 설정합니다. (UTC 로 설정)
- 사용자가 시간을 입력하거나, 조회하는 값을 UTC 로 변환하도록 코드를 만듭니다.
- 사용자에게 보여줄때 UTC시간을 사용자 시간으로 변환하여 보여줍니다.
