### ISSUE TITLE
ERD기능 보완

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#782]
연결된 데이터베이스의 스키마 정보를 이용하여 ERD 를 리버스 엔지니어링 해서 실시간으로 조회하는 기능이 유용한데 display를 좀더 다듬으면 보기에 더 좋을듯 합니다.

우선 제약조건명을 표시하고... 실제 제약조건에 사용된 컬럼을 툴팁형태로 표시해 주면 좋을듯 합니다.

지금은 컬럼명이 각각 표시되면서 서로 중복되어 표시되기도 하거니와 테이블 다이어 그램 위치가 가까울 경우에는 서로 겹쳐서 뷰가 깨져 보이는 현상이 발생하고 있습니다.

![capture 30](https://cloud.githubusercontent.com/assets/859932/15107370/63e47ec2-160a-11e6-97f6-0a84f6fa7c00.png)

**Comment by hangum** [comment]
rap gef 에서는 tooltip 이 잘 먹지 않네요. 
좀더 해볼게요. 

기존과 틀려진 부분은 양쪽 끝에 위치해 있던 레이블을 중앙으로 옮겼습니다. 
<img width="832" alt="2016-06-05 5 37 56" src="https://cloud.githubusercontent.com/assets/1335915/15804548/b6a121b8-2b47-11e6-87de-35336b07abac.png">
