### ISSUE TITLE
테이블 데이터 직접 수정 기능 중 

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#785]
![tabledata](https://cloud.githubusercontent.com/assets/9150735/15318103/72024704-1c5f-11e6-81ac-67309df11681.png)

데이터를 수정한 후에 '저장' 버튼을 누르면 나오는 이 화면은.. 좀 불필요하지 않나 싶습니다. 어차피 사용자는 update나 insert 가 일어나는 것을 알고 있고... 그냥 저장하고 리프레시 하던지.. 구지 한번 더 확인을 해야한다면...'데이터를 변경하시겠습니까' .. 정도의 확인창만 있어도 충분할 것 같아요...  ..

**Comment by hangum** [comment]
네. 현재 데이트 타입이라던가 특수 타입은 전체 적으로 처리를 잘 못하고 있는 실정이라서요.
사용자가 확인하고 업데이트 하는것이 필요해 보입니다.

좀더 안정성 있게 만든다면, 말씀하신 것 처럼 해도 문제가 없지 싶습니다.

2016-05-17 18:46 GMT+09:00 iamsunhan <notifications@github.com>:

> [image: tabledata]
> <https://cloud.githubusercontent.com/assets/9150735/15318103/72024704-1c5f-11e6-81ac-67309df11681.png>
>
> 데이터를 수정한 후에 '저장' 버튼을 누르면 나오는 이 화면은.. 좀 불필요하지 않나 싶습니다. 어차피 사용자는 update나
> insert 가 일어나는 것을 알고 있고... 그냥 저장하고 리프레시 하던지.. 구지 한번 더 확인을 해야한다면...'데이터를
> 변경하시겠습니까' .. 정도의 확인창만 있어도 충분할 것 같아요... ..
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hangum/TadpoleForDBTools/issues/785>
>



-- 
__________________________
Google Talk: hangum@gmail.com
blog  : http://hangumkj.blogspot.com/
FaceBook : https://www.facebook.com/hangum
Tadpole DB Hub : https://github.com/hangum/TadpoleForDBTools

HyunJong Cho

**Comment by hangum** [comment]
이건 기능이 좀더 안정화 될때까지는 기존 방식을 유지 할게요.
