### ISSUE TITLE
table 형식의 정보 

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#786]
![tableinfo](https://cloud.githubusercontent.com/assets/9150735/15351554/c5318302-1d1a-11e6-9f7c-66c13acbdb77.png)
![columninfo](https://cloud.githubusercontent.com/assets/9150735/15351555/c533cb08-1d1a-11e6-80db-f24f6c636fb9.png)

어떤거거는 null 정보에 null 이라고 나오고.. 어떤거는 공백으로 나오네요.. 하나로 통일하는게 좋을 것 같습니다. 
개인적으로는 걍 공란으로 두는게 .. 깔끔하고 좋을 것 같네요...

**Comment by hangum** [comment]
공백으로 수정하는 것으로 하겠습니다.

**Comment by hangum** [comment]
혹시 문제가 다시 보이면 말해주셔요.
