### ISSUE TITLE
'Cancel' and 'OK' buttons

### ISSUE THREAD

**Issue by sunhanintech** [hangum/TadpoleForDBTools#788]
![cancelok](https://cloud.githubusercontent.com/assets/9150735/15421302/71cdefa4-1ead-11e6-96ed-ed8e81f6eaef.png)

별거 아니지만..  Cancel 이랑 OK 버튼 위치가 바뀌었네요... 보통 OK 가 오른쪽... 아닌가용...

**Comment by hangum** [comment]
엇 그렇네요. 
이거 코드로 조절하는 것이 아니고 프레임웍에서 나오는 기본 인데요. 
확인해보겠습니다.

**Comment by hangum** [comment]
다이얼로그 전체를 돌아다니며 수정해야겠네요. --;;

**Comment by hangum** [comment]
http://www.eclipse.org/articles/article.php?file=Article-Preferences/article.html
제 이클립스도 분명 오른쪽에 OK 버튼인데, 아티클에 사진보면 애는 OK가 왼쪽이네요. 음... 

Eclipse 에서도 애내들이 섞여 있네요.   뭔가 설정이 있는지 공부해 보겠습니다.

**Comment by hangum** [comment]
이클립스 RAP 의 Dialog 소스에는 확인이 왼쪽, 취소가 오른쪽으로 되어 있네요. 
조절을 할 수 있겠는데, 전체 정렬 문제라 좀더 여기 저기 살펴보고 수정할 수있도록 하겠습니다. 

	/**
	 * Adds buttons to this dialog's button bar.
	 * <p>
	 * The <code>Dialog</code> implementation of this framework method adds
	 * standard ok and cancel buttons using the <code>createButton</code>
	 * framework method. These standard buttons will be accessible from
	 * <code>getCancelButton</code>, and <code>getOKButton</code>.
	 * Subclasses may override.
	 * </p>
	 * 
	 * @param parent
	 *            the button bar composite
	 */
	protected void createButtonsForButtonBar(Composite parent) {
		// create OK and Cancel buttons by default
		createButton(parent, IDialogConstants.OK_ID, IDialogConstants.get().OK_LABEL,
				true);
		createButton(parent, IDialogConstants.CANCEL_ID,
				IDialogConstants.get().CANCEL_LABEL, false);
	}

	/*
	 * @see Window.initializeBounds()
	 */
	protected void initializeBounds() {
		Shell shell = getShell();
		if (shell != null) {
			if (shell.getDisplay().getDismissalAlignment() == SWT.RIGHT) {
				// make the default button the right-most button
				Button defaultButton = shell.getDefaultButton();
				if (defaultButton != null
						&& isContained(buttonBar, defaultButton)) {
					defaultButton.moveBelow(null);
					((Composite) buttonBar).layout();
				}
			}
		}
		
		super.initializeBounds();
	}
