### ISSUE TITLE
mssql float 데이터 타입에 대한 표시 오류

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#791]
float 타입의 컬럼 값이 ms sql server기본 도구에서의 조회결과와 다르게 올챙이 에서는 소숫점 아래 3자리 까지만 표시됩니다.

![image](https://cloud.githubusercontent.com/assets/859932/15458789/4b53085e-20d9-11e6-8afd-f998324f147f.png)

**Comment by jeongjaehong** [comment]
상세보기 화면에서는 정상적으로 표시됩니다....

결과 그리드에서 임의로 소숫점 아래 자리값을 버림하지 않고 그대로 표시하면 좋겠습니다.

![image](https://cloud.githubusercontent.com/assets/859932/15458857/0193d224-20da-11e6-9fd9-351f924cd24a.png)

**Comment by hangum** [comment]
흠... ....
