### ISSUE TITLE
쿼리 전체 실행버튼 클릭시 여러개의 select결과를 pin으로 자동고정하여 표시

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#794]
쿼리 전체 실행버튼 클릭시 여러개의 select결과를 pin으로 자동고정하여 결과가 모두 표시되었으면 좋겠습니다.

![image](https://cloud.githubusercontent.com/assets/859932/15560879/1a160bca-232b-11e6-87f9-d6fa277cba72.png)

**Comment by hangum** [comment]
select 쿼리를 100개 실행하면 100개를 그렇게 해야하나 싶어요?
한계가 있어야 할듯한데, 어떻게하면 좋을가요?

**Comment by hangum** [comment]
- 아래 그림처럼 전체 실행 했을 때에 5개까지 핀으로 자동으로 실행되도록 코드를 수정하겠습니다. 
<img width="566" alt="all" src="https://cloud.githubusercontent.com/assets/1335915/15796604/7736c42c-2a3b-11e6-98bf-5cfba4629fb1.png">

**Comment by hangum** [comment]
@jeongjaehong  테스트 해주세요.
