### ISSUE TITLE
Tadpolehub.com 에서 MongoDB를 등록할때 "JDBC 드라이버가 발견되지 않았습니다."

### ISSUE THREAD

**Issue by can1001** [hangum/TadpoleForDBTools#799]
안녕하세요!

Tadpolehub.com 에서 MongoDB를 등록하려고 할때, 
아래와 같이 "JDBC 드라이버가 발견되지 않았습니다."  라고 하여 

jdbc 버전 차이인가 싶어서
jdbc 3.2.2를 추가로 등록해도 같은 현상이 발생합니다.

[
![image](https://cloud.githubusercontent.com/assets/7550699/15595140/8ccb2a02-23f7-11e6-804f-d9a1c2563834.png)
](url)

**Comment by can1001** [comment]
[
![image](https://cloud.githubusercontent.com/assets/7550699/15595259/66a20f2a-23f8-11e6-9162-74fb25f588ff.png)
](url)

**Comment by hangum** [comment]
드라이버 검증 오류였구요. 
나오지 않도록 수정했습니다.

**Comment by can1001** [comment]
우와! 
벌써 수정하셨어요.
총알배송, 로켓배송보다 빠르십니다.
감사합니다.

**Comment by hangum** [comment]
서버에 반영되었습니다. ^^
