### ISSUE TITLE
2개의 테이블 상호간에 FK가 2개가 존재할 경우 명칭이 겹쳐서 보입니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#811]
![image](https://cloud.githubusercontent.com/assets/859932/15880756/32f2ab68-2d6b-11e6-9ada-262a583c96df.png)

![image](https://cloud.githubusercontent.com/assets/859932/15880767/4bcc978e-2d6b-11e6-857d-0758672e863a.png)

**Comment by hangum** [comment]
![image](https://cloud.githubusercontent.com/assets/1335915/15896739/81ff59d4-2dcc-11e6-89f9-16f5a7cc1425.png)
로 수정되었습니다.
