### ISSUE TITLE
가입 후 최초 로그인

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#823]
![2016-06-13 18 43 15](https://cloud.githubusercontent.com/assets/9150735/16003276/c4f15f4e-3196-11e6-80a9-3df5eb6fe3e1.png)

가입할 때는... 정상적으로 처리 메시지가 나오는데...  로그인 하려고 하면.. 이렇게  시스템 관리자의 확인이 필요하다고 나옵니다... 

여기서.. 

1. 처음 가입시에 .. 관리자의 허가가 필요하다면.. 가입 요청이 완료 되었다고 알려주고.. 관리자의 승인을 기다리라..든지...  (확인키가 가는 경우)확인키를 메일로 받으면..그걸로 로긴하라든지..하는 디렉션이 있어야 할 것 같습니다.  

2. 시스템 관리자의 어떤 확인이 필요한지 정보가 부족합니다.. 가입 승인인지.. 아니면.. 다른 여차저차한..  프로세스인지...

**Comment by hangum** [comment]
1. 시스템 어드민이 이메일을 설정해야하는데, 설정하지 않아서 그렇습니다. 
관리자 -> 시스템설정 -> smtp에서 설정할수있습니다.
![image](https://cloud.githubusercontent.com/assets/1335915/16017009/e5239bfa-31d8-11e6-9591-38d8d2d12844.png)

2. 메시지 부족한 것은 시스템 어드민영역이라 어디까지 해야할지 좀 고민되긴하네요. ㅠㅠ;; 

이슈는 종료하겠습니다.

**Comment by iamsunhan** [comment]
@hangum  '시스템 관리자의 확인이 필요합니다' 이거.. 가.. 꼭.. 해당 사용자의 가입처리 문제나..혹은 문제가 있다는 걸로 들려서요... 가입처리를 기다리게 되요...  물론 시스템 관리자한테 연락해서 .. 빨리 처리해 달라고 할 것 같지만.. 사실은..  시스템 관리자가 설정 해야 할 것을 하지 않아서 그런거잖아요.... 이런 메시지의 부족을 얘기하는거에요..
