### ISSUE TITLE
로그인정보기억

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#824]
이거.. 한번 누르면... 다시 로그인정보기억... 안하는게 안되요...ㅠㅠ 다시 접속하면 .. 여전히 기억하고 있고... 여전히 체크박스에 체크 되어있습니다.  엔진 디비를 몽땅 다 날려도 이건 없어지지 않네요..  

크롬 사용하고 있습니다.

**Comment by hangum** [comment]
아네. 채크하면 지울수 있도록 하겠습니다.

**Comment by hangum** [comment]
반영했습니다.
