### ISSUE TITLE
[문의] 시스템관리자 정보 분실시 

### ISSUE THREAD

**Issue by iamsunhan** [hangum/TadpoleForDBTools#825]
시스템 관리자 로그인 정보를 분실 했을 때... 는 어떤 복구 방법이 있나요?

**Comment by hangum** [comment]
복구방법이 따로없습니다.

제가 바이너리와 시스템 디비를 보내서 분석해야할 듯합니다.

**Comment by iamsunhan** [comment]
아..큰일이네요!!!!!!

제가 이거.... 로긴을 못하고 있어요....  '시스템관리자의 확인이 필요합니다' 이 메시지만 계속 나와서.... ㅠㅠ  발표 자료 만들어야 하는데 말이죠...ㅠㅠㅠ
