### ISSUE TITLE
팝업메뉴 위치 및 구성과 내보내기(다운로드)기능 보완.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#828]
![capture 19](https://cloud.githubusercontent.com/assets/859932/16065451/c751a8ac-32e5-11e6-8ea4-f1ecb8f75260.png)

**Comment by hangum** [comment]
괸찮은 아이디어 인데요.

**Comment by hangum** [comment]
아래 처럼 수정했어요. 
![image](https://cloud.githubusercontent.com/assets/1335915/19555902/a05713f4-96f9-11e6-8a24-efaeaa1785d7.png)
