### ISSUE TITLE
메뉴 용어가 실제 기능과 다른것 같습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#830]
"DML빌더" 라는 팝업메뉴 명칭이 실제 기능과는 다른것 같습니다.

"DDL 템플릿" 이나 "DDL문 셈플" 이라는 표현이 더 알맞을것 같습니다.

![image](https://cloud.githubusercontent.com/assets/859932/16067911/0b7371ee-32fc-11e6-884c-9d644143aecd.png)

**Comment by hangum** [comment]
@iamsunhan  어떻게 생각하세요?

**Comment by iamsunhan** [comment]
Generator / Builder / Template 모두 사용하는 표현으로 알고 있습니다. 
개인적으로  DDL 문 샘플.. 은 저 창에서 .. 저 기본 템플릿으로 반영도 하시고 하실 수 있어서... 기능이랑은 좀 안맞는 것 같습니다.

**Comment by iamsunhan** [comment]
아니면 .. 모두 
'Query Editor for...  '  라고 매뉴를 만들고 .. 그 아래 둬도 괜찮지 싶네요..

**Comment by iamsunhan** [comment]
한글명 매뉴는 
'쿼리에디터' : 일반 쿼리 에디터 열기
'쿼리에디터 ...' : CREATE TABLE 등 특정.. 쿼리와 함께 오픈

**Comment by iamsunhan** [comment]
저 .. DML  오타는 오늘 바꿔두었습니다...

**Comment by iamsunhan** [comment]
이거 ..어케 할까용??? 템플릿으로 바꿀까요?

**Comment by hangum** [comment]
저는 그냥 둬도 좋겠어요. 
빌더에 맞는 화면을 하나씩 만들어 가는것도 좋겠다 싶어요. 뭔가 UI가 나오고......
