### ISSUE TITLE
조회결과 표시할때 컬럼 폭의 최대값을 지정할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#831]
컬럼의 사이즈가 클경우 조회 결과를 표시할때 컬럼 폭(width)이 너무 넓어서 스크롤을 한참해야 합니다. ㅡㅡ; 최대 사이즈를 정해서 일정 크기 이상일 경우 200px까지만 표시하고 나머지는 “…”으로 표시하면 좋읅것 같습니다.

![capture 20](https://cloud.githubusercontent.com/assets/859932/16068629/44f5cbfa-3302-11e6-8aba-f657b18450f6.png)

**Comment by hangum** [comment]
환경에서 결과가 문자일 경우 보여줄 한계로 정할 수있습니다.
![image](https://cloud.githubusercontent.com/assets/1335915/16068671/b1f61b1a-3302-11e6-8d0f-7d3dd6260e58.png)
