### ISSUE TITLE
쿼리 결과 그리드 기능 보완

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#832]
blob나 clob 외에도 varchar, char 컬럼의 경우도 특정 자리수( 500정도? )를 초과하는 경우 멀티라인 에디터에 여러줄로 데이터를 표시하거나 한번에 확인하기 쉽도로 ui를 개선하면 좋겠습니다.

![capture 23](https://cloud.githubusercontent.com/assets/859932/16068812/2c078c44-3304-11e6-8287-486823d9c8ed.png)

**Comment by hangum** [comment]
해달 컬럼 데이터에 줄바꿈 문자가 있으면 해당 텍스트의 hight를 행 사이즈만큼 키우면 되겠네요.

**Comment by jeongjaehong** [comment]
데이터가 엄청 클수도 있으므로 무한정 커지는거 보다는 최대사이즈를 정해놓고 정해진 최대 사이즈 범위 내에서 크기를 키워주고 그보다도 클 경우는 스크롤이 생기도록 하면 좋을듯 합니다.

**Comment by hangum** [comment]
@jeongjaehong  아 그래야겠네요. 5줄이상이면 스크롤이라거나... 이 화면도 제대로 만들려면 장난아니게 복잡하겠네요.

**Comment by hangum** [comment]
첫번째 행의 텍스트 크기가 50자가 넘을 경우 첨부한 그림처럼 멀티 텍스트로 되도록 수정했습니다. 

![image](https://cloud.githubusercontent.com/assets/1335915/19555078/483661d2-96f6-11e6-8e31-ca7d8faedd30.png)
