### ISSUE TITLE
문자열 ';' 포함시 쿼리 실행 오류 

### ISSUE THREAD

**Issue by lahuman** [hangum/TadpoleForDBTools#850]
안녕하세요! 오늘 올챙이를 쓰다가 발견한 버그 입니다.

Select string_agg (email, ';') from user;

을 실행 하면 문자열 ;에서 쿼리가 끊기면서 오류가 납니다.

늘 발전하는 올챙이를 응원합니다. 오늘도 행복하셔요.

**Comment by hangum** [comment]
감사합니다.  빠르게 패치 해 보겠습니다

**Comment by hangum** [comment]
사용하시는 버전이 어떻게 되시는 지요?
최신 1.7.2 버전은 정상적으로 실행됩니다. 

string_agg가 postgresql이죠?
