### ISSUE TITLE
DML 문(SELECT,UPDATE,), DCL문(DROP,REVOKE)등은 대문자로 설정할수 없나요?

### ISSUE THREAD

**Issue by johnredan** [hangum/TadpoleForDBTools#851]
select '1' as num from dual; 
이라고 치면

SELECT '1' AS num
FROM    dual
; 
로 바꿔줄수 있는 기능이나 아니면 

SELECT '1' AS num FROM dual; 

이라도 되는 기능 없는지...

**Comment by johnredan** [comment]
넵 
-----Original Message-----

**Comment by hangum** [comment]
네 지금당장은 이슈가 많아서 바로 시작하기 어려운데 고민하고 있겠습니다. 
코드 정렬 기능에 넣어볼까 싶었는데 다음과 같은 어려움이 있었습니다. 

- 각 디비 별, 버전 별로 키워드를 정의해야한다. 
- 각 디비 별로 키워드가 대소문자는 기본으로 대소문자인지가 정의 되어 있고 설정으로 바꿀 수있다.
