### ISSUE TITLE
데이터 베이스 목록을 더블클릭하여 에디터 창을 오픈할때...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#857]
아래 첨부한 그림과 같이 필터를 입력하는 칸에 유저명이 자동으로 입력되는 현상이 발생합니다.

![image](https://cloud.githubusercontent.com/assets/859932/16917218/a05baed0-4d3b-11e6-86fb-4a5ad5800dc3.png)

**Comment by hangum** [comment]
이번 스키마 관련 수정으로 입력되지 않도록 수정할게요
