### ISSUE TITLE
상세 내역 테이블의 커럼 조절

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#864]
상세 내역 테이블의 컬럼을 지금까지 2,000바이트씩 잘라 너었으나, 앞으로는 mysql 은 longtext 컬럼으로 만들고 
상세와 디테일의 관계를 1:1로 만들려고 합니다. 

Target tables 
- schema_history_detail - source 컬럼 
- user_db_resource_data - datas 컬럼 (이 테이블은 group_seq 컬럼도 없애야합니다. )
- executed_sql_resource_data - datas 컬럼
- tadpole_template  - sql 컬럼

**Comment by hangum** [comment]
ALTER TABLE `schema_history_detail` 
CHANGE COLUMN `source` `source` LONGTEXT NULL DEFAULT NULL COMMENT '라인단위의 DDL문장' ;

ALTER TABLE `user_db_resource_data` 
CHANGE COLUMN `datas` `datas` LONGBLOB NULL DEFAULT NULL COMMENT '' ;

ALTER TABLE `executed_sql_resource_data` 
CHANGE COLUMN `datas` `datas` LONGTEXT NULL DEFAULT NULL COMMENT 'SQL내용' ;

ALTER TABLE `tadpole_template ` 
CHANGE COLUMN `sql` `sql` LONGTEXT NULL DEFAULT NULL COMMENT 'SQL내용' ;

**Comment by jeongjaehong** [comment]
괞잖을것 같습니다...

다만 ui에서 longtext로 저장된 내용을 제대로 표시해 주는지 확인해 봐야 할것 같습니다.

**Comment by hangum** [comment]
@jeongjaehong  LIKE검색은 잘 되더라고요. 화면에 뿌리는 것은 많을때 좀 고민이긴하네요. 
현재는 있는 만큼 다 뿌려 버리는데요.
