### ISSUE TITLE
쿼리 결과에서 컬럼값 복사를 할 수 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by bumjin** [hangum/TadpoleForDBTools#878]
select 해서 쿼리결과창에 나온 컬럼값을 복사하고 싶은데 
포커스 주고 ctrl+c 를 해봐도 클립보드에 복사가 안되서 불편합니다.
(현재는 행 결과 자세히 보기를 통해서나 겨우 컬럼 값 복사가 가능하네요.)

**Comment by hangum** [comment]
브라우저 보안(?) 문제로 기능구현에 한계가 있습니다. 
이 문제도 꾸준이 이슈로 나오고 있는데요. 

다음과 같이 하면 어떨지요?
결과 태

**Comment by bumjin** [comment]
음.. 그러군요. 보안이유 ...제 생각엔 별도의 탭은  불편해서 만들어도 사용이 안될거 같습니다. 가능하다면 쿼리결과창에서 ctrl+c 했을때 브라우저 보안문제로 복사가 되지 않는다는  경고창이 떠서 알려주는것이 어떨지요.

**Comment by hangum** [comment]
@bumjin  새로운 탭을 만들어 결과를 html로 보면 ctrl+c는 될거에요. 
웹에서 테이블 데이터를 다루시는것처럼은 가능하게 되실듯합니다. 

그래도 안쓰게 될까요?

**Comment by jeongjaehong** [comment]
일반그리드(클립보드사용안되는...)와 HTML그리드 중에서 어떤 뷰로 쿼리 결과를 표시할것인지를 선택하고...
쿼리 결과가 선택된 뷰로 표시되도록 하면 어떨까요?

1. 환경설정에서 Grid , HTML 중 하나를 선택하는 옵션처리 추가.
2. 에디터 상단의 트랜젝션 버튼 옆에 쿼리 결과 표시방법을 선택하는 도구모음 추가.
3. 도구모음에는 환경설정에서 선택한 값이 기본값으로 선택 (그리드,HTML)되고 쿼리 실행전에 변경하여 실행.
4. 쿼리 결과가 html로 표시되면 마우스로 드래그 하여 선택하고 클립보드를 사용하여 복사/붙여넣기가 가능하게 구현하면 좋을것 같네요..^^;

**Comment by bumjin** [comment]
말씀하신대로 환경설정에서 Grid와 html을 선택할 수 있다면 그 방법도 좋을거 같습니다.
(만약 그렇게 구현된다면 Grid와 html의 사용자 입장에서의 장단점설명이 필요할 거 같습니다.
그리고 Grid가 만약 디폴트일때 ctrl+c 시도시 복사가 안됨을 인지할 수 있는 알림까지 있으면 좋을거 같습니다.)

항상 수고 많으십니다. ^^

2016-07-27 19:44 GMT+09:00 jeongjaehong <notifications@github.com>:

**Comment by hangum** [comment]
@bumjin  이슈에 클립보드 문제는 여러번 리포팅되었고 논의 되어 있습니다. 
검색을 부탁드려요.  웹브라우저에서 ctrl + c안되고 하는것까지는 안되요 말하기에는 일반 c/s에서 안되는 기능까지 말해야 하는 기능을 설명을 해야할지도 모르겠다는 생각도 듭니다. 

사용하실때 최대한 웹브라우저에서 동작하는 구나를 인지해 주시면 좋겠어요. --;;
