### ISSUE TITLE
저장된 리소스를 다시 불러올때 SQL Editor, Compile Editor 중에서 처음 리소스를 저장할때...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#887]
저장된 리소스를 다시 불러올때 SQL Editor, Compile Editor 중에서 처음 리소스를 저장할때 열려있던 에디터가 열리면서 리소스가 로딩되었으면 좋겠습니다.

가령 pl/sql블럭일 경우 

sql editor에서 실행할 경우 마우스로 블럭을 설정해야 하거나...

컴파일 에디터를 열어서 다시 붙여넣기 해서 작업을 해야해서 번거롭습니다.

ex)
declare 
  param1 int;
begin
    for rec in (select \* from sample_table) loop
        dbms_output.put_line(rec.name);
    end loop;

```
simpleproc2 (param1 ) ;
```

end;

https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:45027262935845

**Comment by hangum** [comment]
자면서해요 ㅠㅠ

**Comment by hangum** [comment]
@jeongjaehong  저장하려는 쿼리가 섞여 있으면 어떻게 분리해야 할까요?
create procedure 문 조금 ?? 조금 이렇게요. 처음만 보고 판단해서 기면 넘기고 아니면 해야할까요?

**Comment by jeongjaehong** [comment]
애초에 리소스를 저장할때 어떤 에디터(SqlEditor   or  ObjectCompiler)에서 생산된 리소스 인지 구분해서 저장하면 다시 오픈할때 해당 에디터를 오픈해서 리소스 내용을 Open하면 될거 같아~~

**Comment by hangum** [comment]
API Hub 랑 해서 리소스 테이블을 손봐야 겠네요.

**Comment by hangum** [comment]
v1.7.6 에서는 분리 하도록 개선되었습니다.
