### ISSUE TITLE
데이터베이스 연결관리자 기능개선.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#899]
진행중인 트랜젝셕 쿼리가 dba에 의해서 강제로 kill이 되었을 경우 ...

틀랜젝션을 진행중이던 에디터 창에서는 더이상 쿼리가 진행되지 않고 소켓에러가 발생합니다.

이때 관리메뉴의 데이터베이스 연결관리자를 통해서 현재 연결된 켄넥션 목록에서 기존 연결을 끊어주면 새로운 컨넥션이 생성되기는 합니다.

일반컨넥션과 트랜젝션 컨넥션을 하나의 뷰에서 확인할 수 있도록 하는것이 좋을것 같습니다.

또한 커넥션 목록을 표시할때 해당 컨넥션이 유효한 컨넥션인지 연결이 끊긴 컨넥션이지 구분할 수 있으면 좋겠습니다.

**Comment by hangum** [comment]
강제로 킬 되었을때, 쿼리 에디터에서 소켓에러가 나면 연결관리자를 열어주는것도 검토해봐야겠어요

**Comment by hangum** [comment]
쿼리 에디터에서 소켓 에러가 날 경우, 연결 관리자를 다이얼로그 팝업에서 확인 하여 사용자가 처리 할 수 있으면 좋겠습니다.
