### ISSUE TITLE
Chrome 53.0.2785.116  버전에서 한글깨짐.

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#912]
크롬 53.0.2785.116 버전에서 SQL 에디터에서  한글 입력시 한글이 이상하게 입력됩니다.
올챙이에서 사용하고 있는 Ace에디터 전반적인 문제이며, 버그 리포팅하여 결과를 지켜보고 있습니다. 

참고로 github도 ace 에디터를 사용하고 있으며, 파일 수정을 통해 테스트 해볼수 있습니다. 
에이스 에디터 메인 페이지(https://ace.c9.io/#nav=about)에서도 테스트 해볼 수있습니다. 

- 일본어나 다른 2byte 코드에서도 동일한 문제가 나는지 궁금하네요.

**Comment by hangum** [comment]
여기에도 문제를 올렸습니다. 
https://github.com/ajaxorg/ace/issues/3097

**Comment by ysoftman** [comment]
크롬 53.0.2785.116 맥/윈도우 모두 github 에서 edit file 사용시 한글 중복이 발생하고 있는데 ace editor 를 사용하고 있었군요. 53.0.2785.143 (64-bit) 버전으로 업데이트했는데 해당 이슈는 해결되지 않은것 같네요.

**Comment by hangum** [comment]
엔터프라이즈 버전은 패치가 되어서 배포 중입니다. 
오픈소스 버전도 순서대로 배포를 해야겠네요.

**Comment by hangum** [comment]
1.7.3 버전에는 수정되었습니다.
