### ISSUE TITLE
환경설정 저장시 에러창.

### ISSUE THREAD

**Issue by bboradoli** [hangum/TadpoleForDBTools#914]
![20160924_tadpole01](https://cloud.githubusercontent.com/assets/5905500/18795819/4eb94a9c-8201-11e6-94fa-da6aa1bfe118.PNG)

안녕하세요.
짬짬히 간단히 쓰고 있는데, 환경설정에서 폰트 및? 기본적인 것 설정 후,
저장을 하려 하는데

결과가 문자일 경우 보여줄 한계는 1~1000 이라는 창을 보고,
설정을 다시 보니 -1 이라고 되어 있어, 다음과 같이 100으로 값을 조정하고

적용? 확인을 누르니 다음과 같은 창이 뜹니다.
제가 알려드릴수 있는 부분은 여기까지네요.. 확인 부탁드려요~

**Comment by hangum** [comment]
불편을 드려죄송합니다.

@bboradoli 님의 패스워드를 업데이트 하다가 나는 에러 같습니다. 
아마도 사용자 설정들어가셔서 수정하신 후에, RDB를 수정하고 저장을 하는 중에 사용자 설정 정보를 수정하는 듯합니다.  

버그가 확실하구요.  수정해서 빠르게 패치 하도록 하겠습니다.

**Comment by hangum** [comment]
패스워드를 수정하신듯하구요. 
정해진 컬럼자리보다 많이 차지해서 나오는 에러였습니다. 
관련 패치를 하겠습니다.

**Comment by hangum** [comment]
저녁에 반영하겠습니다. 
감사합니다.

**Comment by hangum** [comment]
@bboradoli  서비스에 반영했습니다.
