### ISSUE TITLE
셈플 디비 자동생성

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#916]
현재는 신규 사용자가 등록되면 자동으로 셈플디비가 등록되는데요. 
운영디비 환경에서는 불필요합니다. 

시스템어드민의 설정으로 하지 않을수 있으면 좋겠습니다.

**Comment by jeongjaehong** [comment]
셈플디비를 생성하는 시점이 언제 일까요??

신규사용자 등록시 옵션으로 셈플디비(SQLite)생성 여부를 선택할 수 있어도 좋을듯 합니다. (기본값은 선택안함?? )
사용자 등록 후 관리자가 승인 또는 데이터베이스 권한 부여할때 셈플디비 생성여부를 결정하는것도 좋아 보입니다.

-- 셈플디비는 삭제시에 서버의 데이터베이스 파일까지 삭제가 되나요?  
-- 연결정보만 제거 되나요?

**Comment by hangum** [comment]
@jeongjaehong  SQLite를 삭제하면 연결정보만 삭제해요. 디비를 삭제하지 않아요.

**Comment by hangum** [comment]
유저등록시 생성유무를 선택할 수 있도록 UI를 수정하겠습니다.
