### ISSUE TITLE
시스템로그 수집

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#917]
시스템 로그를 수집 기능 추가.
현재는 로그 디렉토리만 보여주고 있는데요.  
사용자가 이것을 커맨드로 다운로드 받고 처리하기에 불편함이 있습니다. 
 
시스템 로그 디렉토리를 압축해서 다운받을수 있는 기능이 있으면 좋겠습니다.

**Comment by jeongjaehong** [comment]
네네...로그를 통째로 압축해서 지정된 메일에 첨부할 수 있도록 UI로 제공하거나 

파일로 다운로드 받을 수 있는 ui가 제공되면 좋겠네요.. ^^;

이슈 등록할때 옵션에서 해당 로그를 첨부하는 옵션이 있어도 좋겠네요... 

로그내용을 첨부전에 검토할 수 있다거나...  로그파일을 암호화 해야할 필요성도 있을까요? 혹여 로그에 민감정보가 포함될 수도 있을까 싶어서...^^;
