### ISSUE TITLE
환경설정 확인 메세지 정보 부족

### ISSUE THREAD

**Issue by RavenKyu** [hangum/TadpoleForDBTools#918]
환경설정-설정에서 비밀번호만 변경 후, 확인을 눌렀으나 아래의 메세지 출력.

어떠한 항목이 잘못되었는지 알 수가 없습니다.

![image](https://cloud.githubusercontent.com/assets/1933975/19104837/ade26492-8b19-11e6-8b8a-c6be339ba9e9.png)

**Comment by hangum** [comment]
rdb의 환경값을 수정 한 후에 적용을 누르지 않고 이 값을 수정하려고 하는듯합니다. 
프리퍼런스 값을 수정하면 화면단위로 적용 해주세요

우선 rdb의 값을 수정하고 적용을 누르고 이 화면을 수정하세여.

**Comment by jeongjaehong** [comment]
설정값을 변경하고 다른페이지나 탭으로 이동하려고 할때 validation체크를 수행 후 메시지를 보여주도록 하면 좋을것 같습니다.

오류 메시지 표시후에 해당 오류가 발생한 탭으로 전환 후에 해당 항목에 포커스를 주도록 해도 좋을듯 합니다.

에러난 항목의 입력값을 빨간색 폰트로 표시해 준다거나...^^;

**Comment by hangum** [comment]
validation 을 구현해야겠네요.

**Comment by hangum** [comment]
프리퍼런스 입력값이 잘못 입력되면 다른화면으로 넘어가지 못하도록 수정했습니다. 
상단에 에러메시지가 출력되도록 수정했습니다. 
![image](https://cloud.githubusercontent.com/assets/1335915/19186377/f5fb6014-8cc0-11e6-8722-b458d1617e7e.png)
