### ISSUE TITLE
데이터 베이스 삭제 기능

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#919]
데이터베이스 관리에 데이터베이스 삭제 기능 추가. 

디비패스워드 입력기능이 동작할때 올바른 패스워드를 치지 않는 이상 디비를 삭제할수가 없습니다.
하여서 데이터베이스 삭제 기능이 필요합니다.

**Comment by jeongjaehong** [comment]
데이터베이스 연결목록에서 제거하는 기능을 얘기하는 건가요? 
 좌측의 데이터베이스 목록에서 우측버튼 누르고 삭제하는것과 동일한 기능인거죠?
관리자 메뉴에 있는 데이터 베이스 관리 화면에서의 삭제 기능을 얘기하는거면 삭제시에 관련된 리소스나 해당 디비를 사용하도록 지정된 유저나 사용권한등도 정리를 해야하거나 또는 신규 로그인(접속)만 하지 못하도록 연결을 잠그도록 하는것도 고려해야 할것 같습니다.

**Comment by hangum** [comment]
데이터베이스 연결 제거요.  툴바에 제거 기능을 추가했어요. 

![image](https://cloud.githubusercontent.com/assets/1335915/19169670/73f06f80-8c50-11e6-8af1-185d1ad43295.png)
