### ISSUE TITLE
리눅스에서 Stand Alone 실행 시 기본 브라우저 사용

### ISSUE THREAD

**Issue by Mabin-J** [hangum/TadpoleForDBTools#920]
우분투에 세팅된 기본 브라우저가 Chromium인데, firefox가 실행이 됩니다.

**Comment by hangum** [comment]
사용자가 디폴트 브라우저를 선택할 수있도록 환경을 수정 하도록 하겠습니다. 
감사합니다. 

패치는 미안요~

**Comment by hangum** [comment]
감사합니다. 수정된 내용이 잘 반영됩니다.
