### ISSUE TITLE
excel upload

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#926]
현재는 csv를 업로드 할수 있는데, excel파일도 업로드 할수있으면 좋겠습니다.

**Comment by hangum** [comment]
@jeongjaehong  이것좀 맡아줘요

**Comment by jeongjaehong** [comment]
​apache poi 라이브러리 사용하면 되려나?? ^^;

얼마전에 어떤분이 sheet가 40여개에 전체 데이터 건수가 대략 1백만건 정도 된다는데 파일 업로드 중에 서버가 뻗어
버린다고...ㅡㅡ;

poi에서 sheet별로 나눠서 분할작업이 가능한지 알아봐야 겠네...^^;
​

2016-10-17 10:07 GMT+09:00 Cho HyunJong <notifications@github.com>:

> 것좀 맡아줘요




───────────────────────────────────────────────
  샬롬!

  zzz/)/)
    z(__ )
      (")("))o .....nilriri™~
  행복한 일만 가득한 하루 되세요~

  e-mail : jeongjaehong@gmail.com
  Blog : http://nilriri.blogspot.com/
  Phone : +82)010-5210-6848 (5*2=10,6*8=48)
───────────────────────────────────────────────

**Comment by hangum** [comment]
아하~ 데이터 많으면 대략 지옥이겠네요.

**Comment by hangum** [comment]
@jeongjaehong  이것좀 맡아줘~
