### ISSUE TITLE
mysql - 컬럼 코멘트 수정시 오류

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#936]
디비가 mysql 인 경우에 
- 컬럼 타입이 프라이머리키나, 포린키가 걸려 있는경우 오류
- 컬럼 타입이 timstamp 인 경우도 오류

**Comment by jeongjaehong** [comment]
컬럼 타입이나 제약조건 유무를 체크해서 "your_previous_column_definition"부분을 상황에 맞게 스크립트를 생성해 줘야 겠네요..

ALTER TABLE YourTable
MODIFY COLUMN your_column
your_previous_column_definition COMMENT "Your new comment"

 ALTER TABLE Example
    -> MODIFY COLUMN `id`
    -> int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Look, I''m a comment!';

http://stackoverflow.com/questions/2162420/alter-mysql-table-to-add-comments-on-columns
