### ISSUE TITLE
에디터에 작업중인 스키마명 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#940]
에디터 상단 툴바에 스키마 목록 표시
에디터에서 작업할때 스키마가 없을 경우 연결시 작업하는 기본 스키마로 작업하는데, 에디터가 어느 스키마에서 작업 중인지 명시적으로 알수 있었으면 좋겠습니다. 

하여서 에디터 디비 명 옆에 스키마 명을 표시하여 주도록 하는 기능이 있었으면 좋겠습니다. 

![image](https://cloud.githubusercontent.com/assets/1335915/21337718/06ee3104-c6b3-11e6-9bf2-6609ece2dc7b.png)

**Comment by jeongjaehong** [comment]
현재 작업대상이 되는 기본 스키마 정보를 표시하면 좋겠다는 거죠? 

대상스키마를 변경할 수 있게 하려면 작업이 많이 커지겠네요...

테스트 해봐야 할 것도 많을것 같구요...

**Comment by hangum** [comment]
Mysql : use 데이터베이스명;
oracle:
Tibero:
Mssql:
Postgresql:
Altibase:
Cubrid:
Hive:
Tajo:
SQLite: 없음

**Comment by jeongjaehong** [comment]
alter session 권한이 없는 경우도 고려해야 할듯 합니다.
오라클의 경우는 connect 유저명/비밀번호@tnsname으로도 가능한데... jdbc에서도 사용이 가능한지는 모르겠네요.
 
ui에서 다른 콤보박스나 드롭다운리스트 박스 같은걸로 스키마 목록을 표시하고 선택을 바꿀수있는 기능은 dbms별로 나눠서 작업해도 좋을듯 합니다. 

use 명령어를 쓸수 있는 mysql, mssql같은 경우는 지원을 하는 형태로..

에디터 ui구성이 많이 복잡해 질까요?

**Comment by hangum** [comment]
@jeongjaehong  use 명령을 완벽히 막을수 없다면 지원해야 하는게 맞는듯해요. 

현재는 디스플레이 이름옆에 인스턴스 명이 보여지도록 했어요. 
![image](https://cloud.githubusercontent.com/assets/1335915/21757765/ea5b2014-d676-11e6-917c-45416ffb8e2d.png)

**Comment by hangum** [comment]
다음과 같이 수정하여 반영했습니다. 

![image](https://cloud.githubusercontent.com/assets/1335915/21917154/09089bc6-d989-11e6-8346-791478496af6.png)
