### ISSUE TITLE
select 문이 아닌경우 쿼리 실행시 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleForDBTools#955]
select 문이 아닌경우 쿼리를 실행시
- update, delete 문의 경우 where 문이 없으면 실행이 안되도록 
- where 문의 경우 어떤 결과가 있는지 보고 지울수 있도록 .

**Comment by jeongjaehong** [comment]
where 절이 없는 경우 모든 데이터가 삭제되는 오류를 방지하기 위해서 인가요?

사용자 실수를 방지한다는 의미에서 좋은것 같습니다.

꼭 필요한 경우는 truncate문을 사용하거나 delete from TABLE_NAME where 1=1 처럼 항상 참이 조건을 추가하여 명시적으로 모든 데이터를 지우겠다고 했을 경우만 실행되도록 하는것도 나쁘지 않아 보이네요...^^;

**Comment by hangum** [comment]
네. 

where 절이 없는 경우 삭제하지 못하도록 옵션을 줄 생각이에요.
