### ISSUE TITLE
Docker Descriptioin 실행 커맨드 관련 수정 건의

### ISSUE THREAD

**Issue by warnee** [hangum/TadpoleForDBTools#956]
현재 하기 올챙이 docker hub 에는
https://hub.docker.com/r/hyunjongcho/tadpoledbhub/

실행 예제로 하기와 같이 써있습니다.
Image run : docker run -it --rm -p 32768:8080 hyunjongcho/tadpoledbhub:latest

이때 옵션으로 --rm 을 추가한 경우에는 여러가지 이유(서버재부팅등)로 컨테이너를 내릴시
해당 컨테이너가 삭제 됩니다. 

올챙이의 경우 DB 접속 정보와 유저정보들을 등록해서 사용하는데
이 경우 컨테이너가 삭제되며 해당 정보들이 다 사라집니다.
그래서 다시 run 하는 경우 다시 DB접속 정보등을 다 입력해야 되는 불편함이 발생합니다.

그래서 하기와 같이 document 의 수정이 있으면 어떨까 하고 건의 드립니다.

최초실행시 name을 옵션으로 해서 컨테이너를 생성
docker run -it -p 32768:8080 --name tadpoledbhub hyunjongcho/tadpoledbhub:latest

컨테이너 재시작시 name으로 재 시작
docker start tadpoledbhub

감사합니다.

**Comment by hangum** [comment]
감사합니다. 
반영했습니다.

**Comment by warnee** [comment]
docker swarm join \
    --token
SWMTKN-1-1h4prtlkb21wq9vjd4yjm0o3a1zf1qb7270vl5dtfzib55y55m-dv50b3klbtdapzbfpwdq2ompv
\
    192.168.21.138:2377

2017-03-08 14:54 GMT+09:00 Cho HyunJong <notifications@github.com>:
