### ISSUE TITLE
MongoDB Search에서 함수 사용

### ISSUE THREAD

**Issue by ChangshinLee-NBT** [hangum/TadpoleForDBTools#962]
JSON Search의 {Search} 항목에서
{
created_at: new Timestamp(new Date(2012, 0, 21), 0)
}
나
{created_at:{$gte: ISODate("2017-03-14T00:00:00.0Z"), $lt: ISODate("2017-03-15T00:00:00.0Z")}}
으로 실행하면

findBasic 
쿼리 내용

이라는 Problem Occurred 팝업이 뜨면서 실행이 되지 않습니다.

**Comment by hangum** [comment]
@ChangshinLee-NBT  
사용하시는 셈플 데이터 몇개와 검색 예제 부탁드려요.

**Comment by ChangshinLee-NBT** [comment]
샘플 데이터 
`
/* 1 */
{
    "_id" : ObjectId("58c8729310c24f10c99da2c0"),
    "index" : "j",
    "description" : "Device ID 359803065925129",
    "created_at" : ISODate("2017-03-14T22:45:39.000Z"),
    "updated_at" : ISODate("2017-03-14T22:45:39.000Z")
}

/* 2 */
{
    "_id" : ObjectId("58c8729310c24f11479da2a8"),
    "index" : "j",
    "description" : "Device ID 359803065925129",
    "created_at" : ISODate("2017-03-14T22:45:39.000Z"),
    "updated_at" : ISODate("2017-03-14T22:45:39.000Z")
}

/* 3 */
{
    "_id" : ObjectId("58c8734610c24f10d89da52b"),
    "index" : "b",
    "description" : "2",
    "created_at" : ISODate("2017-03-14T22:48:38.000Z"),
    "updated_at" : ISODate("2017-03-14T22:48:38.000Z"),
    "user_id" : 437420,
    "email" : "winstonvandenberg@gmail.com"
}
`

쿼리 1:
db.getCollection('fraud_logs').aggregate([{$match: {created_at: {$gte: ISODate("2017-03-14T00:00:00.0Z"), $lt: ISODate("2017-03-15T00:00:00.0Z")}}}, {$group: {_id: "$index", count: {$sum: 1}}}])

쿼리 2:
db.getCollection('fraud_logs').find({created_at:{$gte: ISODate("2017-03-14T00:00:00.0Z"), $lt: ISODate("2017-03-15T00:00:00.0Z")}}).sort({created_at: -1})

참고로 로보몽고에서는 정상 동작합니다.

**Comment by hangum** [comment]
@ChangshinLee-NBT  
테드폴허브에서 몽고디비 사용은 몽고디비 자바 드라이버를 사용하고 있는데요.
json parser에서 해당 사항을 지원하고 있지 않습니다. 
https://jira.mongodb.org/browse/JAVA-565

그래서 몽고디비 지라에 있는 것처럼 
{date:ISODate("2012-05-01T12:30")}  는  { "date" :
{ "$date" : "2012-08-31T17:30:01.882Z"}
} 으로 바꾸셔서 검색하셔야 합니다.  

감사합니다.

**Comment by ChangshinLee-NBT** [comment]
고맙습니다. 더불어 궁금한 것이 생겼는데, 현재 테드폴에서는 db.getCollection('fraud_logs').find( ... ) 만 지원하는 것같은데, db.getCollection('fraud_logs').aggregate(...) 도 지원하나요?

**Comment by hangum** [comment]
@ChangshinLee-NBT 
aggregate는 아직 지원하고 있지 않습니다.
일반 쿼리도 아직 지원하고 있지 않습니다. --;;

**Comment by ChangshinLee-NBT** [comment]
답변 감사드립니다 ^^

**Comment by hangum** [comment]
@ChangshinLee-NBT  엔터프라이즈 버전을 구매하실때까지 쭈욱~~~~ . 감사합니다.
