### ISSUE TITLE
티베로의 플랜 보기 기능 보완이 필요합니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#972]
오라클 그룹으로 지정하여 오라클과 동일한 방식으로 플랜을 확인하도록 되어 있어서 정상 작동하지 않습니다.

아래 첨부 문서는 티베로에서 제공하는 문서입니다.

[FILE-20140901-000008_140901123958_1.pdf](https://github.com/hangum/TadpoleForDBTools/files/953482/FILE-20140901-000008_140901123958_1.pdf)

**Comment by hangum** [comment]
메뉴얼대로 다음과 같은 과정을 거칩니다.
-- 사용자 쿼리
SELECT SP_NAME, WS_NAME FROM SYS.TBL_FOR_WM_SP;

-- 사용자 쿼리로 쿼리 아이디 검색
select sql_id, sql_text
       from v$sqltext
      where sql_text like '%SELECT SP_NAME, WS_NAME FROM SYS.TBL_FOR_WM_SP%';
      
      select sql_id, sql_text
       from v$sqltext
      where sql_text like '%-- 사용자 쿼리%';
      
-- 쿼리 아이디로 플랜 검색
SELECT SUBSTRB(TO_CHAR(ID), 1, 3) || LPAD(' ', LEVEL * 2) || UPPER(OPERATION) || DECODE(OBJECT_NAME, NULL, NULL, ': '||OBJECT_NAME) || ' (Cost:' || COST || ', %%CPU:' || DECODE(COST, 0, 0, TRUNC((COST-IO_COST)/COST * 100))|| ', Rows:' || CARDINALITY || ') ' || DECODE(PSTART, '', '', '(PS:' || PSTART || ', PE:' || PEND || ')') AS "Execution Plan"
FROM (SELECT * FROM V$SQL_PLAN WHERE SQL_ID =    '5tr694jmbbctr'   )
    START WITH DEPTH = 1
    CONNECT BY PRIOR ID = PARENT_ID AND PRIOR SQL_ID = SQL_ID
    ORDER SIBLINGS BY POSITION;

특이점은 사용자 쿼리에 줄바꿈이 있을 경우 검색이 안되고 줄바꿈 문자를 공백으로 바꾸어서 검색해야합니다.

**Comment by jeongjaehong** [comment]
쿼리를 실행시킬때 올챙이에서 uuid형식의 문자열을 임의로 생성 시켜서 쿼리문에 끼워 넣어서.. v$sqltext를 검색할때 해당 uuid로 검색하게 할 수는 없을까요? ^^

사용자 쿼리  : select * from dept; 라고 했을때 
올챙이 쿼리 : select /*AD2334ESFAS453*/ * from dept; 형태로 특정문자열을 추가함.

select sql_id, sql_text
   from v$sqltext
  where sql_text like 'select /*AD2334ESFAS453*/%';  로 sql_id를 검색함.  물론 주석으로 처리한 uuid가 v$sqltext의 sql_text에 그대로 남아있다는 전제가 되어야 겠네요..^^

이렇게 하면 v$sqltext 를 검색하는 비용도 줄어들고 좀더 효율적일것 같습니다.

**Comment by hangum** [comment]
좋은 생각이네요. 반영해 놓을게요.
