### ISSUE TITLE
postgres cursor 실행 안됩니다.

### ISSUE THREAD

**Issue by lastday1225** [hangum/TadpoleForDBTools#994]
select 함수();
fetch all in "커서";

요렇게 했을때 커서를 인지하지 못해 에러가 납니다.
커서에 대한 기능을 테스트 할 수 없습니다.

참고로 pgadmin에서는 정상 작동합니다.

**Comment by hangum** [comment]
확인해 보겠습니다.

**Comment by hangum** [comment]
감사합니다. 문제점을 수정했습니다. 
아래의 투토러일을 참조했습니다. 
 https://www.postgresql.org/docs/current/static/plpgsql-cursors.html#AEN54814

예제는 
CREATE TABLE test (col text);
INSERT INTO test VALUES ('123');

CREATE FUNCTION reffunc(refcursor) RETURNS refcursor AS '
BEGIN
    OPEN $1 FOR SELECT col FROM test;
    RETURN $1;
END;
' LANGUAGE plpgsql;

BEGIN;
SELECT reffunc('funccursor');
FETCH ALL IN funccursor;
COMMIT;

감사합니다. 

![image](https://user-images.githubusercontent.com/1335915/27812340-22897f00-60a9-11e7-8547-370ab8dd2834.png)
